/**
 * Runtime v1 → v2 migration manifest.
 *
 * The bulk is machine-generated by diffing the v1/v2 `documentation.json`
 * (`manifest.generated.ts`, produced by `scripts/build-candidate-manifest.ts`).
 * This module layers the **curated corrections** on top — the things the docs
 * diff cannot infer:
 *
 *  - `tone` is migrated by the single global rule (with per-component
 *    validation), so the generated per-component `tone` remaps are dropped to
 *    avoid transforming the same attribute twice.
 *  - semantic prop renames the generator can only see as removals
 *    (`mds-label labelAction → label`).
 *  - the preferred slot → attribute lift for `mds-button` (`label`).
 *
 * Re-run the generator on each alpha/beta and review the diff; keep the
 * corrections here.
 */
import { generatedManifest } from './manifest.generated.js';
import { type Manifest } from './schema.js';

const curate = (base: Manifest): Manifest => {
  const m = structuredClone(base);

  // Curated tone mapping. `weak` exists in every component's v2 tone set, so
  // `quiet → weak` validates everywhere (including mds-banner / mds-label, which
  // dropped `text`); `ghost → outline` applies where `outline` exists.
  if (m.global.tone) {
    m.global.tone.map = { ghost: 'outline', quiet: 'weak' };
  }

  for (const component of Object.values(m.components)) {
    // `tone` is handled by the global rule; drop the generated per-component
    // tone remaps so the attribute is not transformed twice.
    component.rules = component.rules.filter(
      (r) => !(r.kind === 'enumRemap' && r.prop.prop === 'tone'),
    );
  }

  // D — mds-label: `labelAction` was renamed to `label` (the diff only shows a removal).
  const label = m.components['mds-label'];
  if (label) {
    label.rules = label.rules.filter(
      (r) => !(r.kind === 'propRemove' && r.prop.prop === 'labelAction'),
    );
    label.rules.unshift({
      kind: 'propRename',
      from: { attr: 'label-action', prop: 'labelAction' },
      to: { attr: 'label', prop: 'label' },
      confidence: 'review',
      note: 'v1 `labelAction` maps to v2 `label`.',
    });
  }

  // B — boolean inversions the name heuristic cannot pair (the diff only shows
  // removals): the v2 prop shares no stem with the v1 name.
  const curatedInversions = [
    {
      tag: 'mds-accordion',
      from: { attr: 'closable', prop: 'closable' },
      to: { attr: 'disable-close', prop: 'disableClose' },
    },
    {
      tag: 'mds-notification',
      from: { attr: 'visible', prop: 'visible' },
      to: { attr: 'dismissed', prop: 'dismissed' },
    },
  ] as const;
  for (const { tag, from, to } of curatedInversions) {
    const component = m.components[tag];
    if (!component) continue;
    component.rules = component.rules.filter(
      (r) => !(r.kind === 'propRemove' && r.prop.prop === from.prop),
    );
    component.rules.unshift({
      kind: 'booleanInvert',
      from: { ...from },
      to: { ...to },
      oldDefault: true,
      newDefault: false,
      confidence: 'review',
    });
  }

  // F2 — preferred: lift mds-button slotted text into `label` (not derivable from the docs diff).
  const button = m.components['mds-button'];
  if (button && !button.rules.some((r) => r.kind === 'slotToAttr')) {
    button.rules.unshift({
      kind: 'slotToAttr',
      slot: 'default',
      to: { attr: 'label', prop: 'label' },
      confidence: 'review',
    });
  }

  // Behavior guard: v2 mds-dropdown enables auto-placement by default (v1 was
  // off). Add `disable-auto-placement` to dropdowns that set neither prop, to
  // preserve the v1 behavior. (mds-tooltip's auto-placement default did not
  // flip, so no guard there.)
  const dropdown = m.components['mds-dropdown'];
  if (dropdown && !dropdown.rules.some((r) => r.kind === 'ensureAttr')) {
    dropdown.rules.push({
      kind: 'ensureAttr',
      attr: { attr: 'disable-auto-placement', prop: 'disableAutoPlacement' },
      unless: [
        { attr: 'auto-placement', prop: 'autoPlacement' },
        { attr: 'disable-auto-placement', prop: 'disableAutoPlacement' },
      ],
      confidence: 'review',
      reason:
        'v2 enables auto-placement by default (v1 was off); added disable-auto-placement to preserve v1 behavior',
    });
  }

  // Behavior guards for flipped *visual* defaults (same prop, new default —
  // invisible to the docs diff): v1 `mds-banner` defaulted to variant="light"
  // (v2: primary) and v1 `mds-label` did not truncate (v2: word). Both v1
  // values still exist in v2, so pinning them preserves the v1 look.
  const visualGuards = [
    {
      tag: 'mds-banner',
      attr: { attr: 'variant', prop: 'variant' },
      value: 'light',
      reason:
        'v2 defaults variant to "primary" (v1 was "light"); added variant="light" to preserve the v1 look',
    },
    {
      tag: 'mds-label',
      attr: { attr: 'truncate', prop: 'truncate' },
      value: 'none',
      reason:
        'v2 defaults truncate to "word" (v1 did not truncate); added truncate="none" to preserve the v1 behavior',
    },
  ] as const;
  for (const { tag, attr, value, reason } of visualGuards) {
    const component = m.components[tag];
    if (
      !component ||
      component.rules.some((r) => r.kind === 'ensureAttr' && r.attr.prop === attr.prop)
    )
      continue;
    component.rules.push({
      kind: 'ensureAttr',
      attr: { ...attr },
      value,
      unless: [{ ...attr }],
      confidence: 'review',
      reason,
    });
  }

  // Behavior guard: `mds-push-notification-item.deletable` defaults to true in
  // v1 but false in v2 (same name, no rename for the diff to see). Add
  // `deletable` to items that never set it, to preserve the v1 behavior.
  const pushItem = (m.components['mds-push-notification-item'] ??= {
    tag: 'mds-push-notification-item',
    react: 'MdsPushNotificationItem',
    rules: [],
  });
  if (!pushItem.rules.some((r) => r.kind === 'ensureAttr')) {
    pushItem.rules.push({
      kind: 'ensureAttr',
      attr: { attr: 'deletable', prop: 'deletable' },
      unless: [{ attr: 'deletable', prop: 'deletable' }],
      confidence: 'review',
      reason:
        'v2 defaults deletable to false (v1 was true); added deletable to preserve v1 behavior',
    });
  }

  return m;
};

export const manifest: Manifest = curate(generatedManifest);

export default manifest;
