/**
 * Runtime v1 → v2 migration manifest.
 *
 * The bulk is machine-generated by diffing the v1/v2 `documentation.json`
 * (`manifest.generated.ts`, produced by `scripts/build-candidate-manifest.ts`).
 * This module layers the **curated corrections** on top — the things the docs
 * diff cannot infer:
 *
 *  - `tone` is migrated by the single global rule (with per-component
 *    validation), so the generated per-component `tone` remaps are dropped to
 *    avoid transforming the same attribute twice; the three text-capable
 *    components override `quiet → text`.
 *  - semantic prop renames the generator can only see as removals
 *    (`mds-label labelAction → label`) or missed entirely (`mds-tooltip arrow`).
 *  - slot → attribute lifts for `label` (`mds-button` preferred;
 *    `mds-breadcrumb-item` / `mds-tab-item` mandatory — v2 dropped their slot).
 *  - CSS custom properties the docs diff recorded as removals but that are
 *    renames in the shipped CSS.
 *
 * Re-run the generator on each alpha/beta and review the diff; keep the
 * corrections here.
 */
import { generatedManifest } from './manifest.generated.js';
import { type Manifest } from './schema.js';

const curate = (base: Manifest): Manifest => {
  const m = structuredClone(base);

  // Curated tone mapping. `weak` exists in every component's v2 tone set, so
  // `quiet → weak` validates everywhere (including mds-banner / mds-label, which
  // dropped `text`); `ghost → outline` applies where `outline` exists. The three
  // components whose v2 tone set gained `text` follow the documented design
  // intent (`quiet → text`) via per-tag overrides.
  if (m.global.tone) {
    m.global.tone.map = { ghost: 'outline', quiet: 'weak' };
    const quietToText = { ghost: 'outline', quiet: 'text' };
    m.global.tone.overrides = {
      'mds-button': { ...quietToText },
      'mds-radial-menu': { ...quietToText },
      'mds-radial-menu-item': { ...quietToText },
    };
  }

  for (const component of Object.values(m.components)) {
    // `tone` is handled by the global rule; drop the generated per-component
    // tone remaps so the attribute is not transformed twice.
    component.rules = component.rules.filter(
      (r) => !(r.kind === 'enumRemap' && r.prop.prop === 'tone'),
    );
  }

  // D — mds-label: `labelAction` was renamed to `label` (the diff only shows a removal).
  const label = m.components['mds-label'];
  if (label) {
    label.rules = label.rules.filter(
      (r) => !(r.kind === 'propRemove' && r.prop.prop === 'labelAction'),
    );
    label.rules.unshift({
      kind: 'propRename',
      from: { attr: 'label-action', prop: 'labelAction' },
      to: { attr: 'label', prop: 'label' },
      confidence: 'review',
      note: 'v1 `labelAction` maps to v2 `label`.',
    });
  }

  // B — boolean inversions the docs diff could not pair: either the v2 prop
  // shares no stem with the v1 name (the diff only shows removals), or the pair
  // is missing from the diff entirely (mds-tooltip `arrow`).
  const curatedInversions = [
    {
      tag: 'mds-accordion',
      from: { attr: 'closable', prop: 'closable' },
      to: { attr: 'disable-close', prop: 'disableClose' },
    },
    {
      tag: 'mds-notification',
      from: { attr: 'visible', prop: 'visible' },
      to: { attr: 'dismissed', prop: 'dismissed' },
    },
    {
      tag: 'mds-tooltip',
      from: { attr: 'arrow', prop: 'arrow' },
      to: { attr: 'hide-arrow', prop: 'hideArrow' },
    },
  ] as const;
  for (const { tag, from, to } of curatedInversions) {
    const component = m.components[tag];
    if (!component) continue;
    component.rules = component.rules.filter(
      (r) => !(r.kind === 'propRemove' && r.prop.prop === from.prop),
    );
    component.rules.unshift({
      kind: 'booleanInvert',
      from: { ...from },
      to: { ...to },
      oldDefault: true,
      newDefault: false,
      confidence: 'review',
    });
  }

  // F2 — lift slotted text into `label` (not derivable from the docs diff).
  // mds-button keeps reading slotted text in v2, so the lift is the preferred
  // form; mds-breadcrumb-item and mds-tab-item no longer render a slot at all,
  // so there the lift is mandatory — v2 silently drops slotted content.
  const slotLifts = [
    { tag: 'mds-breadcrumb-item', react: 'MdsBreadcrumbItem' },
    { tag: 'mds-button', react: 'MdsButton' },
    { tag: 'mds-tab-item', react: 'MdsTabItem' },
  ] as const;
  for (const { tag, react } of slotLifts) {
    const component = (m.components[tag] ??= { tag, react, rules: [] });
    if (component.rules.some((r) => r.kind === 'slotToAttr')) continue;
    component.rules.unshift({
      kind: 'slotToAttr',
      slot: 'default',
      to: { attr: 'label', prop: 'label' },
      confidence: 'review',
    });
  }

  // G — CSS custom properties the docs diff saw as removals (or could not see
  // at all) but that are really renames, verified against the shipped component
  // CSS on both branches. Three flavours:
  //  - real renames (banner gap, header backdrop, filter `shodow → shadow`);
  //  - "doc-only v1 name" cases where the shipped v1 CSS already used the v2
  //    name, so overrides written against the documented name were silently
  //    inert — the rename activates them (explanatory note attached);
  //  - typo'd v1 names corrected in v2 (#566): v1 shipped the misspelled name,
  //    so the working v1 name is renamed to the corrected v2 one.
  const docOnlyNote = (shipped: string): string =>
    `the v1 name was documented but never shipped (the CSS always read \`--${shipped}\`); this override was inert in v1 and becomes effective after the rename`;
  const cssVarRenames: Array<{
    tag: string;
    from: string;
    to: string;
    valueFormatChanged?: boolean;
    note?: string;
  }> = [
    {
      tag: 'mds-banner',
      from: 'mds-banner-gap',
      to: 'mds-banner-content-gap',
      valueFormatChanged: true,
      note: 'v1 accepted a "row column" gap shorthand; v2 takes a single gap value',
    },
    {
      tag: 'mds-file',
      from: 'mds-file-preview-icon-bacground',
      to: 'mds-file-preview-icon-background',
    },
    {
      tag: 'mds-filter',
      from: 'mds-filter-wrapper-shodow-opacity',
      to: 'mds-filter-wrapper-shadow-opacity',
    },
    {
      tag: 'mds-filter-item',
      from: '-mds-filter-item-count-background-selected',
      to: 'mds-filter-item-count-background-selected',
      note: docOnlyNote('mds-filter-item-count-background-selected'),
    },
    {
      tag: 'mds-filter-item',
      from: '-mds-filter-item-count-color-default',
      to: 'mds-filter-item-count-color-default',
      note: docOnlyNote('mds-filter-item-count-color-default'),
    },
    {
      tag: 'mds-filter-item',
      from: '-mds-filter-item-count-color-selected',
      to: 'mds-filter-item-count-color-selected',
      note: docOnlyNote('mds-filter-item-count-color-selected'),
    },
    {
      tag: 'mds-header',
      from: 'mds-header-backdrop-filter',
      to: 'mds-header-backdrop-blur-strength',
      valueFormatChanged: true,
      note: 'v1 took a full backdrop-filter value (e.g. blur(10px)); v2 takes the blur length only',
    },
    {
      tag: 'mds-tab',
      from: 'mds-tab-item-transition-duration',
      to: 'mds-tab-transition-duration',
      note: docOnlyNote('mds-tab-transition-duration'),
    },
    {
      tag: 'mds-tab',
      from: 'mds-tab-item-transition-timing-function',
      to: 'mds-tab-transition-timing-function',
      note: docOnlyNote('mds-tab-transition-timing-function'),
    },
    {
      tag: 'mds-video-wall',
      from: 'mds-video-wall-noise-fitler',
      to: 'mds-video-wall-noise-filter',
    },
  ];
  for (const { tag, from, to, valueFormatChanged, note } of cssVarRenames) {
    const component = m.components[tag];
    if (!component) continue;
    // Drop the stale generated removal for either spelling: the docs diff
    // recorded `--mds-video-wall-noise-filter` (the rename target) as removed
    // while v2 still shipped the typo.
    component.rules = component.rules.filter(
      (r) => !(r.kind === 'cssVarRemove' && (r.name === from || r.name === to)),
    );
    component.rules.push({
      kind: 'cssVarRename',
      from,
      to,
      ...(valueFormatChanged ? { valueFormatChanged } : {}),
      ...(note ? { note } : {}),
    });
  }

  // G3 / A2 - global (non-component) CSS custom-property migrations for the
  // semantic color system.
  //  - Seed rename (A2): the bare `--tone-<family>` primitive became
  //    `--tone-<family>-seed`. A consumer that referenced the bare token keeps
  //    the pure-extreme value; a note points background users at a surface role.
  //  - Surface-candidate reports: a neutral tone used as a *background* (the bare
  //    token or any scale step) is a surface, but the exact role is contextual
  //    (and often the component's own default, C2 territory), so it is REPORTED
  //    for manual migration, never rewritten. In a background context the report
  //    wins over the seed rename, so a background is never seed-renamed.
  const toneFamilies = ['porcelain', 'kaolin', 'neutral', 'fireclay', 'bisque'] as const;
  const neutralSteps = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10'];
  m.global.cssVars = [
    ...toneFamilies.map((family) => ({
      kind: 'cssVarRename' as const,
      from: `tone-${family}`,
      to: `tone-${family}-seed`,
      note: 'A2: the bare tone primitive is now the off-scale `-seed` escape hatch (the pure extreme); if it was used as a surface/background, migrate it to a `--magma-surface-*` role instead',
    })),
    { kind: 'cssVarSurfaceReport' as const, from: 'tone-neutral' },
    ...neutralSteps.map((step) => ({
      kind: 'cssVarSurfaceReport' as const,
      from: `tone-neutral-${step}`,
    })),
  ];

  // Behavior guard: v2 mds-dropdown enables auto-placement by default (v1 was
  // off). Add `disable-auto-placement` to dropdowns that set neither prop, to
  // preserve the v1 behavior. (mds-tooltip's auto-placement default did not
  // flip, so no guard there.)
  const dropdown = m.components['mds-dropdown'];
  if (dropdown && !dropdown.rules.some((r) => r.kind === 'ensureAttr')) {
    dropdown.rules.push({
      kind: 'ensureAttr',
      attr: { attr: 'disable-auto-placement', prop: 'disableAutoPlacement' },
      unless: [
        { attr: 'auto-placement', prop: 'autoPlacement' },
        { attr: 'disable-auto-placement', prop: 'disableAutoPlacement' },
      ],
      confidence: 'review',
      reason:
        'v2 enables auto-placement by default (v1 was off); added disable-auto-placement to preserve v1 behavior',
    });
  }

  // Behavior guards for flipped *visual* defaults (same prop, new default —
  // invisible to the docs diff): v1 `mds-banner` defaulted to variant="light"
  // (v2: primary) and v1 `mds-label` did not truncate (v2: word). Both v1
  // values still exist in v2, so pinning them preserves the v1 look.
  const visualGuards = [
    {
      tag: 'mds-banner',
      attr: { attr: 'variant', prop: 'variant' },
      value: 'light',
      reason:
        'v2 defaults variant to "primary" (v1 was "light"); added variant="light" to preserve the v1 look',
    },
    {
      tag: 'mds-label',
      attr: { attr: 'truncate', prop: 'truncate' },
      value: 'none',
      reason:
        'v2 defaults truncate to "word" (v1 did not truncate); added truncate="none" to preserve the v1 behavior',
    },
  ] as const;
  for (const { tag, attr, value, reason } of visualGuards) {
    const component = m.components[tag];
    if (
      !component ||
      component.rules.some((r) => r.kind === 'ensureAttr' && r.attr.prop === attr.prop)
    )
      continue;
    component.rules.push({
      kind: 'ensureAttr',
      attr: { ...attr },
      value,
      unless: [{ ...attr }],
      confidence: 'review',
      reason,
    });
  }

  // Behavior guard: `mds-push-notification-item.deletable` defaults to true in
  // v1 but false in v2 (same name, no rename for the diff to see). Add
  // `deletable` to items that never set it, to preserve the v1 behavior.
  const pushItem = (m.components['mds-push-notification-item'] ??= {
    tag: 'mds-push-notification-item',
    react: 'MdsPushNotificationItem',
    rules: [],
  });
  if (!pushItem.rules.some((r) => r.kind === 'ensureAttr')) {
    pushItem.rules.push({
      kind: 'ensureAttr',
      attr: { attr: 'deletable', prop: 'deletable' },
      unless: [{ attr: 'deletable', prop: 'deletable' }],
      confidence: 'review',
      reason:
        'v2 defaults deletable to false (v1 was true); added deletable to preserve v1 behavior',
    });
  }

  return m;
};

export const manifest: Manifest = curate(generatedManifest);

export default manifest;
