.base-price-table:
  variables:
    COMPONENT: mds-price-table

# TEST
price-table-publish-test:
  extends: [.base-stencil-publish-test, .base-price-table]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
price-table-publish:
  extends: [.base-stencil-publish, .base-price-table]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, price-table-publish-test]

# INSTALL TEST
price-table-install-test:
  extends: [.base-stencil-install-test, .base-price-table]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, price-table-publish]
