.base-list:
  variables:
    COMPONENT: mds-list

# TEST
list-publish-test:
  extends: [.base-stencil-publish-test, .base-list]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
list-publish:
  extends: [.base-stencil-publish, .base-list]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, list-publish-test]

# INSTALL TEST
list-install-test:
  extends: [.base-stencil-install-test, .base-list]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, list-publish]
