.base-list-item:
  variables:
    COMPONENT: mds-list-item

# TEST
list-item-publish-test:
  extends: [.base-stencil-publish-test, .base-list-item]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
list-item-publish:
  extends: [.base-stencil-publish, .base-list-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, list-item-publish-test]

# INSTALL TEST
list-item-install-test:
  extends: [.base-stencil-install-test, .base-list-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, list-item-publish]
