.base-list-item:
  variables:
    COMPONENT: mds-list-item

# ISOLATE
list-item-isolate:
  extends: [.base-isolate, .base-list-item]
  dependencies: [base-stencil-build]

# TEST
list-item-publish-test:
  extends: [.base-stencil-publish-test, .base-list-item]
  dependencies: [base-stencil-build, list-item-isolate]

# PUBLISH
list-item-publish:
  extends: [.base-stencil-publish, .base-list-item]
  dependencies: [base-stencil-build, list-item-isolate]
  needs: [base-stencil-build, list-item-isolate, list-item-publish-test]
