.base-icon:
  variables:
    COMPONENT: mds-icon

# ISOLATE
icon-isolate:
  extends: [.base-isolate, .base-icon]
  dependencies: [base-stencil-build]

# TEST
icon-publish-test:
  extends: [.base-stencil-publish-test, .base-icon]
  dependencies: [base-stencil-build, icon-isolate]

# PUBLISH
icon-publish:
  extends: [.base-stencil-publish, .base-icon]
  dependencies: [base-stencil-build, icon-isolate]
  needs: [base-stencil-build, icon-isolate, icon-publish-test]

# INSTALL TEST
icon-install-test:
  extends: [.base-stencil-install-test, .base-icon]
  dependencies: [icon-publish, icon-isolate]
