.base-icon:
  variables:
    COMPONENT: mds-icon

# TEST
icon-publish-test:
  extends: [.base-stencil-publish-test, .base-icon]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
icon-publish:
  extends: [.base-stencil-publish, .base-icon]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, icon-publish-test]

# INSTALL TEST
icon-install-test:
  extends: [.base-stencil-install-test, .base-icon]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, icon-publish]
