import './node_modules/normalize.css/normalize.css'
import './node_modules/@maggioli-common/mgg-icons/dist/mgg-icons.css'
import './node_modules/typeface-karla/index.css'
import './node_modules/typeface-roboto/index.css'
import './src/scss/import-global.scss'
