.base-bibliography:
  variables:
    COMPONENT: mds-bibliography

# TEST
bibliography-publish-test:
  extends: [.base-stencil-publish-test, .base-bibliography]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
bibliography-publish:
  extends: [.base-stencil-publish, .base-bibliography]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, bibliography-publish-test]

# INSTALL TEST
bibliography-install-test:
  extends: [.base-stencil-install-test, .base-bibliography]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, bibliography-publish]
