.base-bibliography:
  variables:
    COMPONENT: mds-bibliography

# ISOLATE
bibliography-isolate:
  extends: [.base-isolate, .base-bibliography]
  dependencies: [base-stencil-build]

# TEST
bibliography-publish-test:
  extends: [.base-stencil-publish-test, .base-bibliography]
  dependencies: [base-stencil-build, bibliography-isolate]

# PUBLISH
bibliography-publish:
  extends: [.base-stencil-publish, .base-bibliography]
  dependencies: [base-stencil-build, bibliography-isolate]
  needs: [base-stencil-build, bibliography-isolate, bibliography-publish-test]
