.base-pref-theme:
  variables:
    COMPONENT: mds-pref-theme

# TEST
pref-theme-publish-test:
  extends: [.base-stencil-publish-test, .base-pref-theme]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
pref-theme-publish:
  extends: [.base-stencil-publish, .base-pref-theme]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, pref-theme-publish-test]

# INSTALL TEST
pref-theme-install-test:
  extends: [.base-stencil-install-test, .base-pref-theme]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, pref-theme-publish]
