.base-accordion-timer-item:
  variables:
    COMPONENT: mds-accordion-timer-item

# TEST
accordion-timer-item-publish-test:
  extends: [.base-stencil-publish-test, .base-accordion-timer-item]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
accordion-timer-item-publish:
  extends: [.base-stencil-publish, .base-accordion-timer-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, accordion-timer-item-publish-test]

# INSTALL TEST
accordion-timer-item-install-test:
  extends: [.base-stencil-install-test, .base-accordion-timer-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, accordion-timer-item-publish]
