# IDENTITY CACHE
.identity-cache:
  cache:
    key:
      files:
        - yarn.lock
      prefix: "${CI_PROJECT_NAME}-identity"
    policy: pull

# IDENTITY BUILD
identity-build:
  extends: [.base-build, .identity-cache]
  script:
    - nx run identity:build
  artifacts:
    name: identity-build
    expire_in: 1 day
    paths:
      - projects/identity/dist
  cache:
    policy: pull-push
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(dev|main|pipeline)$/
      changes:
        - projects/identity/**/*

# IDENTITY PUBLISH TEST
identity-publish-test:
  extends: [.base-publish-test, .identity-cache]
  dependencies: [identity-build]
  stage: test
  variables:
    BUILD_DIR: projects/identity
    COMPONENT: identity
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(main|pipeline)$/
      changes:
        - projects/identity/package.json

# IDENTITY PUBLISH
identity-publish:
  extends: [.base-publish, .identity-cache]
  dependencies: [identity-build]
  needs: [identity-publish-test, identity-build]
  stage: publish
  variables:
    BUILD_DIR: projects/identity
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/identity/package.json

# IDENTITY INSTALL TEST
identity-install-test:
  extends: [.base-install-test, .identity-cache]
  needs: [identity-publish]
  variables:
    BUILD_DIR: projects/identity
    COMPONENT: identity
    PACK_NAME: maggioli-design-system-identity-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/identity/package.json
