.base-spinner:
  variables:
    COMPONENT: mds-spinner

# ISOLATE
spinner-isolate:
  extends: [.base-isolate, .base-spinner]
  dependencies: [base-stencil-build]

# TEST
spinner-publish-test:
  extends: [.base-stencil-publish-test, .base-spinner]
  dependencies: [base-stencil-build, spinner-isolate]

# PUBLISH
spinner-publish:
  extends: [.base-stencil-publish, .base-spinner]
  dependencies: [base-stencil-build, spinner-isolate]
  needs: [base-stencil-build, spinner-isolate, spinner-publish-test]

# INSTALL TEST
spinner-install-test:
  extends: [.base-stencil-install-test, .base-spinner]
  dependencies: [spinner-publish, spinner-isolate]
