.base-flex-table-header:
  variables:
    COMPONENT: mds-flex-table-header

# ISOLATE
flex-table-header-isolate:
  extends: [.base-isolate, .base-flex-table-header]
  dependencies: [base-stencil-build]

# TEST
flex-table-header-publish-test:
  extends: [.base-stencil-publish-test, .base-flex-table-header]
  dependencies: [base-stencil-build, flex-table-header-isolate]

# PUBLISH
flex-table-header-publish:
  extends: [.base-stencil-publish, .base-flex-table-header]
  dependencies: [base-stencil-build, flex-table-header-isolate]
  needs: [base-stencil-build, flex-table-header-isolate, flex-table-header-publish-test]

# INSTALL TEST
flex-table-header-install-test:
  extends: [.base-stencil-install-test, .base-flex-table-header]
  dependencies: [flex-table-header-publish, flex-table-header-isolate]

