.base-card-footer:
  variables:
    COMPONENT: mds-card-footer

# TEST
card-footer-publish-test:
  extends: [.base-stencil-publish-test, .base-card-footer]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
card-footer-publish:
  extends: [.base-stencil-publish, .base-card-footer]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, card-footer-publish-test]

# INSTALL TEST
card-footer-install-test:
  extends: [.base-stencil-install-test, .base-card-footer]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, card-footer-publish]
