.base-price-table-features-cell:
  variables:
    COMPONENT: mds-price-table-features-cell

# TEST
price-table-features-cell-publish-test:
  extends: [.base-stencil-publish-test, .base-price-table-features-cell]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
price-table-features-cell-publish:
  extends: [.base-stencil-publish, .base-price-table-features-cell]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, price-table-features-cell-publish-test]

# INSTALL TEST
price-table-features-cell-install-test:
  extends: [.base-stencil-install-test, .base-price-table-features-cell]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, price-table-features-cell-publish]
