.base-calendar:
  variables:
    COMPONENT: mds-calendar

# TEST
calendar-publish-test:
  extends: [.base-stencil-publish-test, .base-calendar]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
calendar-publish:
  extends: [.base-stencil-publish, .base-calendar]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, calendar-publish-test]

# INSTALL TEST
calendar-install-test:
  extends: [.base-stencil-install-test, .base-calendar]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, calendar-publish]
