.base-tab-bar-item:
  variables:
    COMPONENT: mds-tab-bar-item

# ISOLATE
tab-bar-item-isolate:
  extends: [.base-isolate, .base-tab-bar-item]
  dependencies: [base-stencil-build]

# TEST
tab-bar-item-publish-test:
  extends: [.base-stencil-publish-test, .base-tab-bar-item]
  dependencies: [base-stencil-build, tab-bar-item-isolate]

# PUBLISH
tab-bar-item-publish:
  extends: [.base-stencil-publish, .base-tab-bar-item]
  dependencies: [base-stencil-build, tab-bar-item-isolate]
  needs: [base-stencil-build, tab-bar-item-isolate, tab-bar-item-publish-test]

# INSTALL TEST
tab-bar-item-install-test:
  extends: [.base-stencil-install-test, .base-tab-bar-item]
  dependencies: [base-stencil-build, tab-bar-item-isolate]
  needs: [base-stencil-build, tab-bar-item-isolate, tab-bar-item-publish]
