version: '3.1'

services:

  designsystem:
    build:
      context: ../../
      dockerfile: ./doc/Dockerfile
    restart: unless-stopped
    container_name: designsystem
    expose:
      - "443"
    environment:
      - VIRTUAL_HOST=design-system.maggiolicloud.it
      - CERT_NAME=shared

networks:
  default:
    external:
      name: nginx-proxy
