.base-zero:
  variables:
    COMPONENT: mds-zero

# ISOLATE
zero-isolate:
  extends: [.base-isolate, .base-zero]
  dependencies: [base-stencil-build]

# TEST
zero-publish-test:
  extends: [.base-stencil-publish-test, .base-zero]
  dependencies: [base-stencil-build, zero-isolate]

# PUBLISH
zero-publish:
  extends: [.base-stencil-publish, .base-zero]
  dependencies: [base-stencil-build, zero-isolate]
  needs: [base-stencil-build, zero-isolate, zero-publish-test]

# INSTALL TEST
zero-install-test:
  extends: [.base-stencil-install-test, .base-zero]
  dependencies: [base-stencil-build, zero-isolate]
  needs: [base-stencil-build, zero-isolate, zero-publish]
