.base-radial-menu-item:
  variables:
    COMPONENT: mds-radial-menu-item

# TEST
radial-menu-item-publish-test:
  extends: [.base-stencil-publish-test, .base-radial-menu-item]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
radial-menu-item-publish:
  extends: [.base-stencil-publish, .base-radial-menu-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, radial-menu-item-publish-test]

# INSTALL TEST
radial-menu-item-install-test:
  extends: [.base-stencil-install-test, .base-radial-menu-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, radial-menu-item-publish]
