.base-status-bar:
  variables:
    COMPONENT: mds-status-bar

# TEST
status-bar-publish-test:
  extends: [.base-stencil-publish-test, .base-status-bar]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
status-bar-publish:
  extends: [.base-stencil-publish, .base-status-bar]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, status-bar-publish-test]

# INSTALL TEST
status-bar-install-test:
  extends: [.base-stencil-install-test, .base-status-bar]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, status-bar-publish]
