image : busybox:latest

variables:
    GIT_DEPTH: "1"

stages:
  - deploy

deploy-storybook:
  stage: deploy
  image: kroniak/ssh-client
  variables:
    DEPLOY_FOLDER: $CI_DEPLOY_PATH
    SERVER: $CI_SERVER_IP
  script:
    - chmod +x ./.deploy/deploy-storybook.sh
    - ./.deploy/deploy-storybook.sh
  environment:
    name: DeployWebApp
    url: $CI_PRODUCTION_URL
  allow_failure: false
  when: manual
  only:
    refs:
      - master