workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'

variables:
  # The GIT_DEPTH option makes the project clone process in each job a bit faster, pulling only the current commit, not the whole Git history.
  GIT_DEPTH: "1"
  # overlay2 filesystem for the Docker build, which is faster and less space consuming
  DOCKER_DRIVER: overlay2
  # Abilita debug gitlab-ci
  #CI_DEBUG_TRACE: "true"

#default:
#  tags:
#    - maggioli-network

stages:
  - build
  - build:isolate
  - test
  - deploy:storybook # TODO
  - publish
  - deploy:website # TODO

# BASE
.base-build:
  image: node:16.13
  stage: build
  variables:
    COMPONENT: to_be_extended
    BUILD_DIR: projects/stencil/src/components/$COMPONENT
    WORK_DIR: projects/stencil/.build/$COMPONENT
  before_script:
    - npm install -g nx yarn --force
    - yarn install
  script:
    - nx run design-tokens:build
    - nx run styles:build
    - nx run icons:build
    - nx run stencil:build
  cache:
    key: $COMPONENT-cache
    paths:
      - node_modules
      - projects/design-tokens/node_modules
      - projects/styles/node_modules
      - projects/icons/node_modules
      - projects/stencil/node_modules
    policy: pull-push
  artifacts:
    name: $COMPONENT-build
    expire_in: 1 day
    paths:
      - projects/design-tokens/dist
      - projects/design-tokens/config
      - projects/design-tokens/properties
      - projects/styles/dist
      - projects/icons/dist
      - projects/stencil/dist
      - $BUILD_DIR/readme.md
  rules:
    - if: $CI_COMMIT_BRANCH == "pipeline"
      changes: ["*", "${BUILD_DIR}/**/*"]

.base-isolate:
  extends: .base-build
  stage: build:isolate
  script:
    - nx run stencil:publish.isolate.component --component=$COMPONENT
  artifacts:
    name: $COMPONENT-stencil-build
    expire_in: 1 day
    paths:
      - $WORK_DIR

.base-stencil-test:
  extends: .base-build
  image: atools/chrome-headless:java11-node16-latest
  stage: test
  script:
    - cd projects/stencil
    - npm run test # TODO: trovare modo per eseguire test solo per il componente modificato, ora vengono eseguiti i test su tutti i componenti
  allow_failure: true # TODO: fix test, ora falliscono
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "pipeline"
      changes: ["*", "${BUILD_DIR}/**/*"]

.base-publish-test:
  extends: .base-build
  stage: test
  variables:
    PACK_NAME: maggioli-design-system-${COMPONENT}-*.tgz
  script:
    - cd $WORK_DIR
    - npm pack && npm install $PACK_NAME && npm publish --access public --dry-run
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "pipeline"
      changes: [ "*", "${BUILD_DIR}/**/*" ]

.base-publish:
  extends: .base-build
  stage: publish
  script:
    - cd $WORK_DIR
    - npm publish --access public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes: ["*", "${BUILD_DIR}/**/*"]

include:
  - 'projects/stencil/src/components/**/.gitlab-ci.yml'
