.base-policy-ai:
  variables:
    COMPONENT: mds-policy-ai

# TEST
policy-ai-publish-test:
  extends: [.base-stencil-publish-test, .base-policy-ai]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
policy-ai-publish:
  extends: [.base-stencil-publish, .base-policy-ai]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, policy-ai-publish-test]

# INSTALL TEST
policy-ai-install-test:
  extends: [.base-stencil-install-test, .base-policy-ai]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, policy-ai-publish]
