.base-breadcrumb:
  variables:
    COMPONENT: mds-breadcrumb

# ISOLATE
breadcrumb-isolate:
  extends: [.base-isolate, .base-breadcrumb]
  dependencies: [base-stencil-build]

# TEST
breadcrumb-publish-test:
  extends: [.base-stencil-publish-test, .base-breadcrumb]
  dependencies: [base-stencil-build, breadcrumb-isolate]

# PUBLISH
breadcrumb-publish:
  extends: [.base-stencil-publish, .base-breadcrumb]
  dependencies: [base-stencil-build, breadcrumb-isolate]
