.base-paginator:
  variables:
    COMPONENT: mds-paginator

# TEST
paginator-publish-test:
  extends: [.base-stencil-publish-test, .base-paginator]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
paginator-publish:
  extends: [.base-stencil-publish, .base-paginator]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, paginator-publish-test]

# INSTALL TEST
paginator-install-test:
  extends: [.base-stencil-install-test, .base-paginator]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, paginator-publish]
