.base-paginator:
  variables:
    COMPONENT: mds-paginator

# ISOLATE
paginator-isolate:
  extends: [.base-isolate, .base-paginator]
  dependencies: [base-stencil-build]

# TEST
paginator-publish-test:
  extends: [.base-stencil-publish-test, .base-paginator]
  dependencies: [base-stencil-build, paginator-isolate]

# PUBLISH
paginator-publish:
  extends: [.base-stencil-publish, .base-paginator]
  dependencies: [base-stencil-build, paginator-isolate]
  needs: [base-stencil-build, paginator-isolate, paginator-publish-test]

# INSTALL TEST
paginator-install-test:
  extends: [.base-stencil-install-test, .base-paginator]
  dependencies: [paginator-publish, paginator-isolate]
