# ICONS BUILD
icons-build:
  extends: [.base-build]
  script:
    - nx run icons:build
  artifacts:
    name: stencil-build
    expire_in: 1 day
    paths:
      - projects/icons/dist
  cache:
    policy: pull-push
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(dev|main)$/
      changes:
        - projects/icons/**/*

# ICONS PUBLISH TEST
icons-publish-test:
  extends: [.base-publish-test]
  dependencies: [icons-build]
  stage: test
  variables:
    BUILD_DIR: projects/icons
    COMPONENT: icons
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/icons/package.json

# ICONS PUBLISH
icons-publish:
  extends: [.base-publish]
  dependencies: [icons-build]
  needs: [icons-publish-test, icons-build]
  stage: publish
  variables:
    BUILD_DIR: projects/icons
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/icons/package.json

# ICONS INSTALL TEST
icons-install-test:
  extends: [.base-install-test]
  needs: [icons-publish]
  variables:
    BUILD_DIR: projects/icons
    COMPONENT: icons
    PACK_NAME: maggioli-design-system-icons-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/icons/package.json
