.base-grid:
  variables:
    COMPONENT: mds-grid

# BUILD
grid-build:
  extends: [.base-build, .base-grid]

# ISOLATE
grid-isolate:
  extends: [.base-isolate, .base-grid]
  dependencies: [grid-build]

# TEST
grid-stencil-test:
  extends: [.base-stencil-test, .base-grid]
  dependencies: [grid-build, grid-isolate]

grid-publish-test:
  extends: [.base-publish-test, .base-grid]
  dependencies: [grid-build, grid-isolate]

# PUBLISH
grid-publish:
  extends: [.base-publish, .base-grid]
  dependencies: [grid-build, grid-isolate]

