.base-grid:
  variables:
    COMPONENT: mds-grid

# ISOLATE
grid-isolate:
  extends: [.base-isolate, .base-grid]
  dependencies: [base-stencil-build]

# TEST
grid-publish-test:
  extends: [.base-stencil-publish-test, .base-grid]
  dependencies: [base-stencil-build, grid-isolate]

# PUBLISH
grid-publish:
  extends: [.base-stencil-publish, .base-grid]
  dependencies: [base-stencil-build, grid-isolate]
  needs: [base-stencil-build, grid-isolate, grid-publish-test]
