/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MdsLabel {
    }
}
declare global {
    interface HTMLMdsLabelElement extends Components.MdsLabel, HTMLStencilElement {
    }
    var HTMLMdsLabelElement: {
        prototype: HTMLMdsLabelElement;
        new (): HTMLMdsLabelElement;
    };
    interface HTMLElementTagNameMap {
        "mds-label": HTMLMdsLabelElement;
    }
}
declare namespace LocalJSX {
    interface MdsLabel {
    }
    interface IntrinsicElements {
        "mds-label": MdsLabel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mds-label": LocalJSX.MdsLabel & JSXBase.HTMLAttributes<HTMLMdsLabelElement>;
        }
    }
}
