.base-label:
  variables:
    COMPONENT: mds-label

# TEST
label-publish-test:
  extends: [.base-stencil-publish-test, .base-label]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
label-publish:
  extends: [.base-stencil-publish, .base-label]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, label-publish-test]

# INSTALL TEST
label-install-test:
  extends: [.base-stencil-install-test, .base-label]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, label-publish]
