.base-pref-animation:
  variables:
    COMPONENT: mds-pref-animation

# ISOLATE
pref-animation-isolate:
  extends: [.base-isolate, .base-pref-animation]
  dependencies: [base-stencil-build]

# TEST
pref-animation-publish-test:
  extends: [.base-stencil-publish-test, .base-pref-animation]
  dependencies: [base-stencil-build, pref-animation-isolate]

# PUBLISH
pref-animation-publish:
  extends: [.base-stencil-publish, .base-pref-animation]
  dependencies: [base-stencil-build, pref-animation-isolate]
  needs: [base-stencil-build, pref-animation-isolate, pref-animation-publish-test]

# INSTALL TEST
pref-animation-install-test:
  extends: [.base-stencil-install-test, .base-pref-animation]
  dependencies: [base-stencil-build, pref-animation-isolate]
  needs: [base-stencil-build, pref-animation-isolate, pref-animation-publish]
