.base-flex-table-body:
  variables:
    COMPONENT: mds-flex-table-body

# ISOLATE
flex-table-body-isolate:
  extends: [.base-isolate, .base-flex-table-body]
  dependencies: [base-build]

# TEST
flex-table-body-publish-test:
  extends: [.base-publish-test, .base-flex-table-body]
  dependencies: [base-build, flex-table-body-isolate]

# PUBLISH
flex-table-body-publish:
  extends: [.base-publish, .base-flex-table-body]
  dependencies: [base-build, flex-table-body-isolate]
