.base-flex-table-body:
  variables:
    COMPONENT: mds-flex-table-body

# ISOLATE
flex-table-body-isolate:
  extends: [.base-isolate, .base-flex-table-body]
  dependencies: [base-stencil-build]

# TEST
flex-table-body-publish-test:
  extends: [.base-stencil-publish-test, .base-flex-table-body]
  dependencies: [base-stencil-build, flex-table-body-isolate]

# PUBLISH
flex-table-body-publish:
  extends: [.base-stencil-publish, .base-flex-table-body]
  dependencies: [base-stencil-build, flex-table-body-isolate]
  needs: [base-stencil-build, flex-table-body-isolate, flex-table-body-publish-test]

# INSTALL TEST
flex-table-body-install-test:
  extends: [.base-stencil-install-test, .base-flex-table-body]
  dependencies: [base-stencil-build, flex-table-body-isolate]
  needs: [base-stencil-build, flex-table-body-isolate, flex-table-body-publish]
