.base-file:
  variables:
    COMPONENT: mds-file

# ISOLATE
file-isolate:
  extends: [.base-isolate, .base-file]
  dependencies: [base-stencil-build]

# TEST
file-publish-test:
  extends: [.base-stencil-publish-test, .base-file]
  dependencies: [base-stencil-build, file-isolate]

# PUBLISH
file-publish:
  extends: [.base-stencil-publish, .base-file]
  dependencies: [base-stencil-build, file-isolate]
  needs: [base-stencil-build, file-isolate, file-publish-test]

# INSTALL TEST
file-install-test:
  extends: [.base-stencil-install-test, .base-file]
  dependencies: [file-publish, file-isolate]
