.base-details:
  variables:
    COMPONENT: mds-details

# ISOLATE
details-isolate:
  extends: [.base-isolate, .base-details]
  dependencies: [base-stencil-build]

# TEST
details-publish-test:
  extends: [.base-stencil-publish-test, .base-details]
  dependencies: [base-stencil-build, details-isolate]

# PUBLISH
details-publish:
  extends: [.base-stencil-publish, .base-details]
  dependencies: [base-stencil-build, details-isolate]
  needs: [base-stencil-build, details-isolate, details-publish-test]

# INSTALL TEST
details-install-test:
  extends: [.base-stencil-install-test, .base-details]
  dependencies: [details-publish, details-isolate]
