.base-table:
  variables:
    COMPONENT: mds-table

# ISOLATE
table-isolate:
  extends: [.base-isolate, .base-table]
  dependencies: [base-stencil-build]

# TEST
table-publish-test:
  extends: [.base-stencil-publish-test, .base-table]
  dependencies: [base-stencil-build, table-isolate]

# PUBLISH
table-publish:
  extends: [.base-stencil-publish, .base-table]
  dependencies: [base-stencil-build, table-isolate]
  needs: [base-stencil-build, table-isolate, table-publish-test]

# INSTALL TEST
table-install-test:
  extends: [.base-stencil-install-test, .base-table]
  dependencies: [base-stencil-build, table-isolate]
  needs: [base-stencil-build, table-isolate, table-publish]
