.base-table:
  variables:
    COMPONENT: mds-table

# TEST
table-publish-test:
  extends: [.base-stencil-publish-test, .base-table]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
table-publish:
  extends: [.base-stencil-publish, .base-table]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-publish-test]

# INSTALL TEST
table-install-test:
  extends: [.base-stencil-install-test, .base-table]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-publish]
