.base-tab-bar:
  variables:
    COMPONENT: mds-tab-bar

# ISOLATE
tab-bar-isolate:
  extends: [.base-isolate, .base-tab-bar]
  dependencies: [base-stencil-build]

# TEST
tab-bar-publish-test:
  extends: [.base-stencil-publish-test, .base-tab-bar]
  dependencies: [base-stencil-build, tab-bar-isolate]

# PUBLISH
tab-bar-publish:
  extends: [.base-stencil-publish, .base-tab-bar]
  dependencies: [base-stencil-build, tab-bar-isolate]
  needs: [base-stencil-build, tab-bar-isolate, tab-bar-publish-test]

# INSTALL TEST
tab-bar-install-test:
  extends: [.base-stencil-install-test, .base-tab-bar]
  dependencies: [tab-bar-publish, tab-bar-isolate]
