.base-tab-bar:
  variables:
    COMPONENT: mds-tab-bar

# TEST
tab-bar-publish-test:
  extends: [.base-stencil-publish-test, .base-tab-bar]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
tab-bar-publish:
  extends: [.base-stencil-publish, .base-tab-bar]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, tab-bar-publish-test]

# INSTALL TEST
tab-bar-install-test:
  extends: [.base-stencil-install-test, .base-tab-bar]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, tab-bar-publish]
