.base-card-media:
  variables:
    COMPONENT: mds-card-media

# TEST
card-media-publish-test:
  extends: [.base-stencil-publish-test, .base-card-media]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
card-media-publish:
  extends: [.base-stencil-publish, .base-card-media]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, card-media-publish-test]

# INSTALL TEST
card-media-install-test:
  extends: [.base-stencil-install-test, .base-card-media]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, card-media-publish]
