.base-price-table-list:
  variables:
    COMPONENT: mds-price-table-list

# ISOLATE
price-table-list-isolate:
  extends: [.base-isolate, .base-price-table-list]
  dependencies: [base-stencil-build]

# TEST
price-table-list-publish-test:
  extends: [.base-stencil-publish-test, .base-price-table-list]
  dependencies: [base-stencil-build, price-table-list-isolate]

# PUBLISH
price-table-list-publish:
  extends: [.base-stencil-publish, .base-price-table-list]
  dependencies: [base-stencil-build, price-table-list-isolate]
  needs: [base-stencil-build, price-table-list-isolate, price-table-list-publish-test]

# INSTALL TEST
price-table-list-install-test:
  extends: [.base-stencil-install-test, .base-price-table-list]
  dependencies: [base-stencil-build, price-table-list-isolate]
  needs: [base-stencil-build, price-table-list-isolate, price-table-list-publish]
