.base-flex-table-row:
  variables:
    COMPONENT: mds-flex-table-row

# ISOLATE
flex-table-row-isolate:
  extends: [.base-isolate, .base-flex-table-row]
  dependencies: [base-stencil-build]

# TEST
flex-table-row-publish-test:
  extends: [.base-stencil-publish-test, .base-flex-table-row]
  dependencies: [base-stencil-build, flex-table-row-isolate]

# PUBLISH
flex-table-row-publish:
  extends: [.base-stencil-publish, .base-flex-table-row]
  dependencies: [base-stencil-build, flex-table-row-isolate]
  needs: [base-stencil-build, flex-table-row-isolate, flex-table-row-publish-test]

# INSTALL TEST
flex-table-row-install-test:
  extends: [.base-stencil-install-test, .base-flex-table-row]
  needs: [flex-table-row-publish]

