.base-tab:
  variables:
    COMPONENT: mds-tab

# TEST
tab-publish-test:
  extends: [.base-stencil-publish-test, .base-tab]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
tab-publish:
  extends: [.base-stencil-publish, .base-tab]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, tab-publish-test]

# INSTALL TEST
tab-install-test:
  extends: [.base-stencil-install-test, .base-tab]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, tab-publish]
