.base-tab:
  variables:
    COMPONENT: mds-tab

# ISOLATE
tab-isolate:
  extends: [.base-isolate, .base-tab]
  dependencies: [base-stencil-build]

# TEST
tab-publish-test:
  extends: [.base-stencil-publish-test, .base-tab]
  dependencies: [base-stencil-build, tab-isolate]

# PUBLISH
tab-publish:
  extends: [.base-stencil-publish, .base-tab]
  dependencies: [base-stencil-build, tab-isolate]
  needs: [base-stencil-build, tab-isolate, tab-publish-test]

# INSTALL TEST
tab-install-test:
  extends: [.base-stencil-install-test, .base-tab]
  dependencies: [tab-publish, tab-isolate]
