.base-input-switch-group:
  variables:
    COMPONENT: mds-input-switch-group

# ISOLATE
input-switch-group-isolate:
  extends: [.base-isolate, .base-input-switch-group]
  dependencies: [base-stencil-build]

# TEST
input-switch-group-publish-test:
  extends: [.base-stencil-publish-test, .base-input-switch-group]
  dependencies: [base-stencil-build, input-switch-group-isolate]

# PUBLISH
input-switch-group-publish:
  extends: [.base-stencil-publish, .base-input-switch-group]
  dependencies: [base-stencil-build, input-switch-group-isolate]
  needs: [base-stencil-build, input-switch-group-isolate, input-switch-group-publish-test]

# INSTALL TEST
input-switch-group-install-test:
  extends: [.base-stencil-install-test, .base-input-switch-group]
  needs: [input-switch-group-publish]

