.base-input-switch:
  variables:
    COMPONENT: mds-input-switch

# ISOLATE
input-switch-isolate:
  extends: [.base-isolate, .base-input-switch]
  dependencies: [base-stencil-build]

# TEST
input-switch-publish-test:
  extends: [.base-stencil-publish-test, .base-input-switch]
  dependencies: [base-stencil-build, input-switch-isolate]

# PUBLISH
input-switch-publish:
  extends: [.base-stencil-publish, .base-input-switch]
  dependencies: [base-stencil-build, input-switch-isolate]
  needs: [base-stencil-build, input-switch-isolate, input-switch-publish-test]
