.base-input-switch:
  variables:
    COMPONENT: mds-input-switch

# TEST
input-switch-publish-test:
  extends: [.base-stencil-publish-test, .base-input-switch]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
input-switch-publish:
  extends: [.base-stencil-publish, .base-input-switch]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-switch-publish-test]

# INSTALL TEST
input-switch-install-test:
  extends: [.base-stencil-install-test, .base-input-switch]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-switch-publish]
