.base-note:
  variables:
    COMPONENT: mds-note

# TEST
note-publish-test:
  extends: [.base-stencil-publish-test, .base-note]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
note-publish:
  extends: [.base-stencil-publish, .base-note]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, note-publish-test]

# INSTALL TEST
note-install-test:
  extends: [.base-stencil-install-test, .base-note]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, note-publish]
