import chalk from 'chalk';
import path from 'path';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { BUILD_DIR, PROJECT_DIR } from './meta';

/**
 * Generate the corner axis: `build/css/corner.css`.
 *
 * Corner shape and corner radius are two halves of one decision. At the same
 * `border-radius` a squircle cuts a far smaller corner than a round one, so a
 * scale tuned for `round` reads rigid the moment the shape changes. This file
 * emits the shape AND the radius scale together, in one block per shape, so the
 * two can never drift apart - the reason it is generated rather than written by
 * hand.
 *
 * The default lives on a bare `:root`: install the design system and you get it
 * with no attribute to write, exactly like a theme nobody spells as
 * `data-theme-name="default"`. The deviation blocks are NOT prefixed with
 * `:root`, so `data-corner-shape` works on any element and the custom
 * properties inherit into that subtree, shadow DOM included.
 *
 * The pill stays out of the axis, by decision: `--magma-radius-full` resolves to
 * the same `--radius-full` under every shape. Past half the shorter side a
 * squircle stops producing a pill and draws the filled superellipse of an app
 * icon, so the components that spell a pill (chip, filter item, avatar, hr, ...)
 * keep the CSS default `round` by simply not declaring `corner-shape`.
 *
 * The squircle steps come from `design-tokens/tokens/sizing/radius.json`, where
 * they are the round scale multiplied by 1.715 - the factor that preserves the
 * AREA the corner cuts - and then snapped to the nearest existing primitive so
 * the scale stays inside the system.
 */

const TOKENS_CSS = path.resolve(PROJECT_DIR, '../design-tokens/dist/css/typography.css');
const OUT_FILE = path.resolve(BUILD_DIR, 'css', 'corner.css');

/** The shape a consumer gets without writing a single attribute. */
const DEFAULT_SHAPE = 'squircle';

/** Every shape that owns a scale. A shape with no `--radius-<shape>-*` steps
 * would produce a block identical to `round`, which is why the list is derived
 * from the emitted tokens rather than from the `corner-shape` keywords. */
const SHAPE_WITH_SCALE = 'squircle';

interface Scale {
  /** Step names in emission order, e.g. `['none', '3xs', ..., 'full']`. */
  steps: string[];
  /** Step names that have a `--radius-squircle-*` counterpart. */
  shaped: Set<string>;
}

/**
 * Read the emitted token sheet and split `--radius-*` into the base scale and
 * the per-shape one. Deriving the steps from the build output (rather than
 * hardcoding them here) means adding a step to `radius.json` is enough.
 */
const readScale = async (): Promise<Scale> => {
  const css = await readFile(TOKENS_CSS, 'utf8').catch((error) => {
    throw new Error(chalk.red(`[corner] cannot read ${TOKENS_CSS}: ${error}`));
  });

  const steps: string[] = [];
  const shaped = new Set<string>();
  const prefix = `${SHAPE_WITH_SCALE}-`;

  for (const [, name] of css.matchAll(/--radius-([a-z0-9-]+)\s*:/g)) {
    if (name.startsWith(prefix)) {
      shaped.add(name.slice(prefix.length));
    } else if (!steps.includes(name)) {
      steps.push(name);
    }
  }

  const orphans = [...shaped].filter((step) => !steps.includes(step));
  if (orphans.length > 0) {
    throw new Error(
      chalk.red(`[corner] --radius-${SHAPE_WITH_SCALE}-* steps with no base step: ${orphans}`),
    );
  }
  if (steps.length === 0) {
    throw new Error(chalk.red(`[corner] no --radius-* token found in ${TOKENS_CSS}`));
  }

  return { steps, shaped };
};

/**
 * One selector's worth of declarations: the shape itself, then every step of
 * the scale pointed at the source token that shape uses.
 */
const block = (selector: string, shape: string, scale: Scale): string => {
  const lines = [`  --magma-corner-shape: ${shape};`, ''];
  for (const step of scale.steps) {
    const source =
      shape === SHAPE_WITH_SCALE && scale.shaped.has(step)
        ? `--radius-${SHAPE_WITH_SCALE}-${step}`
        : `--radius-${step}`;
    lines.push(`  --magma-radius-${step}: var(${source});`);
  }
  return `${selector} {\n${lines.join('\n')}\n}`;
};

const main = async (): Promise<void> => {
  const scale = await readScale();

  const header = [
    '/*',
    '  GENERATED by projects/styles/scripts/corner.ts - do not edit.',
    '',
    '  The corner axis: one block per shape, each carrying the shape and the radius',
    '  scale tuned for it. The default sits on a bare :root, so nothing has to be',
    '  written to get it; the deviation blocks carry no :root prefix, so',
    '  data-corner-shape works on any element and inherits into its subtree.',
    '',
    `  --magma-radius-full is the same under every shape on purpose: the pill is out`,
    '  of the axis (see corner.ts).',
    '*/',
    '',
  ].join('\n');

  const blocks = [
    block(':root', DEFAULT_SHAPE, scale),
    ...['round', SHAPE_WITH_SCALE].map((shape) =>
      block(`[data-corner-shape='${shape}']`, shape, scale),
    ),
  ];

  await mkdir(path.dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, `${header}${blocks.join('\n\n')}\n`, 'utf8');

  console.info(
    `[corner] ${scale.steps.length} steps, ${scale.shaped.size} of them shaped -> ${OUT_FILE}`,
  );
};

main();
