import chalk from 'chalk';
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { BUILD_DIR } from './meta';
import { semantic, type ThemeDef } from '../../design-tokens/semantic.config';

/**
 * Generate the semantic color layer (A9) from design-tokens/semantic.config.ts:
 *  - build/css/semantic.css        the `--magma-*` layer components consume
 *  - build/tailwind/semantic.css   the Tailwind `@theme` bridge (--color-* re-exports)
 *  - build/css/themes.css          named-theme overrides (data-theme-name, spec 8)
 *
 * All are GENERATED and gitignored; they are staged under build/ (out of the
 * hand-authored source dirs) and the copy step ships them to dist. The
 * tracked contract is design-tokens/semantic.config.ts. Text roles come from A7's `--text-*`
 * primitives; surfaces/borders resolve through the `--magma-tint-*` indirection
 * so a named theme retints with one swap (B2, spec section 8).
 */

const {
  tint,
  surfaceRoles,
  borderRoles,
  textRoles,
  borderFocus,
  seed,
  hues,
  hueSteps,
  neutralHueSteps,
  accents,
  accentStateSteps,
  themes,
} = semantic;

const HEADER = (what: string) =>
  `/*\n  ${what}\n  GENERATED by scripts/semantic.ts from semantic.config.ts - do NOT edit by hand.\n` +
  `  Contract + rationale: semantic.config.ts and SEMANTIC_COLOR_SPEC.md.\n*/\n`;

// (magma token suffix, Tailwind color name) pairs, collected while building the
// layer so the bridge stays in exact sync with what the layer declares.
const bridge: Array<[string, string]> = [];
/** A bridged `--magma-<magma>: var(--<source>);` line; `tw` is its Tailwind color name. */
const alias = (magma: string, source: string, tw: string): string => {
  bridge.push([magma, tw]);
  return `  --magma-${magma}: var(--${source});`;
};

const layer: string[] = ['', ':root {'];

// 1. tint indirection (internal; not bridged to Tailwind). The tint block IS the
//    theme: a named theme repoints these to another family and retints surface,
//    border AND text together in one swap (spec 8). Text joins the block so the
//    foreground retints WITH its surface, kept to one coherent, contrast-paired
//    family (A7 verifies text against that same family's surfaces).
layer.push(
  '  /* Active tint = the theme (spec 8): a named theme retints surface + border + text by repointing --magma-tint-*. */',
);
surfaceRoles.forEach((r) => layer.push(`  --magma-tint-${r}: var(--surface-${tint}-${r});`));
borderRoles.forEach((r) => layer.push(`  --magma-tint-border-${r}: var(--border-${tint}-${r});`));
textRoles.forEach((r) => layer.push(`  --magma-tint-text-${r}: var(--text-${tint}-${r});`));
layer.push(`  --magma-tint-text-on-emphasis: var(--${seed});`);

// 2. surfaces (from the tint pointers)
layer.push('', '  /* Surfaces - elevation + same-plane prominence (spec 6.1) */');
surfaceRoles.forEach((r) => layer.push(alias(`surface-${r}`, `magma-tint-${r}`, `surface-${r}`)));

// 3. text roles - resolve through the tint-text indirection so a theme retints
//    the foreground with its surface (values are the by-target --text-*, A7).
layer.push(
  '',
  '  /* Text - prominence, by APCA target (spec 6.2 / 9, A7); retints via --magma-tint-text-* */',
);
textRoles.forEach((r) => layer.push(alias(`text-${r}`, `magma-tint-text-${r}`, `fg-${r}`)));
layer.push(alias('text-on-emphasis', 'magma-tint-text-on-emphasis', 'fg-on-emphasis'));

// 4. borders (from the tint pointers); focus follows an accent (theme-aware)
layer.push(
  '',
  '  /* Border - prominence (spec 6.3); focus follows the accent it is named after */',
);
borderRoles.forEach((r) =>
  layer.push(alias(`border-${r}`, `magma-tint-border-${r}`, `border-${r}`)),
);
layer.push(alias('border-focus', `magma-accent-${borderFocus}-emphasis`, 'border-focus'));

// 5. hues - colored families carry the full quintet; neutral omits surface (spec 6.4).
//    The neutral family's "emphasis" pair is NOT a saturated fill like the colored
//    hues: it is the INVERSE SURFACE role (a dark chip in light mode, light in dark -
//    toast, tooltip). It is emitted under role names --magma-surface-inverse /
//    --magma-on-inverse (Material inverseSurface), decoupled from the colored
//    <hue>-emphasis fills. The former --magma-neutral-emphasis / -on-emphasis names
//    stay as DEPRECATED aliases (one release) so existing consumers keep resolving.
Object.entries(hues).forEach(([hue, { family, partial }]) => {
  layer.push('', `  /* ${hue} (${family}) */`);
  const steps = partial ? neutralHueSteps : hueSteps;
  if (!partial)
    layer.push(alias(`${hue}-surface`, `${family}-${hueSteps.surface}`, `${hue}-surface`));
  layer.push(alias(`${hue}-fg`, `${family}-${steps.fg}`, `${hue}-fg`));
  layer.push(alias(`${hue}-border`, `${family}-${steps.border}`, `${hue}-border`));
  if (partial) {
    // inverse-surface role (renamed from neutral-emphasis / -on-emphasis)
    layer.push(alias('surface-inverse', `${family}-${steps.emphasis}`, 'surface-inverse'));
    layer.push(alias('on-inverse', seed, 'on-inverse'));
    layer.push('  /* deprecated: renamed to --magma-surface-inverse / --magma-on-inverse */');
    layer.push(alias(`${hue}-emphasis`, 'magma-surface-inverse', `${hue}-emphasis`));
    layer.push(alias(`${hue}-on-emphasis`, 'magma-on-inverse', `${hue}-on-emphasis`));
  } else {
    layer.push(alias(`${hue}-emphasis`, `${family}-${steps.emphasis}`, `${hue}-emphasis`));
    layer.push(alias(`${hue}-on-emphasis`, seed, `${hue}-on-emphasis`));
  }
});

// 6. accents (variant) - the standout colors (spec 8). Each accent role is a
//    THEME-AWARE quintet: the roles resolve through per-role tint pointers
//    (--magma-tint-accent-<role>-*), so a named theme repoints an accent exactly
//    like a surface. Steps reuse the colored-hue quintet (hueSteps); on-emphasis
//    is the seed (family-independent, spec 6.5). The former single --magma-accent-*
//    is kept as a DEPRECATED alias of accent-primary for one release.
Object.entries(accents).forEach(([role, family]) => {
  layer.push('', `  /* accent ${role} (${family}) */`);
  // tint pointers (internal; repointed per theme, not bridged to Tailwind)
  layer.push(`  --magma-tint-accent-${role}-surface: var(--${family}-${hueSteps.surface});`);
  layer.push(`  --magma-tint-accent-${role}-fg: var(--${family}-${hueSteps.fg});`);
  layer.push(`  --magma-tint-accent-${role}-border: var(--${family}-${hueSteps.border});`);
  layer.push(`  --magma-tint-accent-${role}-emphasis: var(--${family}-${hueSteps.emphasis});`);
  // interaction-state pointers (spec 6.6 accent exception): each names an existing
  // ramp step, so it mode-flips and retints per theme exactly like the quintet.
  Object.entries(accentStateSteps).forEach(([state, step]) =>
    layer.push(`  --magma-tint-accent-${role}-${state}: var(--${family}-${step});`),
  );
  // roles resolve through the tint pointers -> theme-aware
  layer.push(
    alias(`accent-${role}-surface`, `magma-tint-accent-${role}-surface`, `accent-${role}-surface`),
  );
  layer.push(alias(`accent-${role}-fg`, `magma-tint-accent-${role}-fg`, `accent-${role}-fg`));
  layer.push(
    alias(`accent-${role}-border`, `magma-tint-accent-${role}-border`, `accent-${role}-border`),
  );
  layer.push(
    alias(
      `accent-${role}-emphasis`,
      `magma-tint-accent-${role}-emphasis`,
      `accent-${role}-emphasis`,
    ),
  );
  Object.keys(accentStateSteps).forEach((state) =>
    layer.push(
      alias(
        `accent-${role}-${state}`,
        `magma-tint-accent-${role}-${state}`,
        `accent-${role}-${state}`,
      ),
    ),
  );
  layer.push(alias(`accent-${role}-on-emphasis`, seed, `accent-${role}-on-emphasis`));
});

// deprecated (one release): the former single accent == the primary accent
layer.push('', '  /* deprecated: use --magma-accent-primary-* (kept one release) */');
['surface', 'fg', 'border', 'emphasis', 'on-emphasis'].forEach((sub) =>
  layer.push(alias(`accent-${sub}`, `magma-accent-primary-${sub}`, `accent-${sub}`)),
);

layer.push('}', '');

const bridgeBody = bridge
  .map(([magma, tw]) => `  --color-${tw}: rgb(var(--magma-${magma}));`)
  .join('\n');
const bridgeCss = `${HEADER('Tailwind bridge for the semantic color layer.')}\n@theme {\n${bridgeBody}\n}\n`;
const layerCss = `${HEADER('Semantic color layer (--magma-*) - the contract components consume.')}${layer.join('\n')}`;

// Named themes (spec 8): one override block per theme. A theme repoints the
// --magma-tint-* block (surface + border + text) when its surface family differs
// from the base `tint`, AND repoints --magma-tint-accent-<role>-* for every
// accent it overrides - so a theme retints background, foreground AND accents in
// one swap. A theme that changes nothing (base tint, no accent override) emits
// nothing. String shorthand == surface family only (back-compat).
const normalizeTheme = (def: ThemeDef): { surface?: string; accents?: Record<string, string> } =>
  typeof def === 'string' ? { surface: def } : def;

const themeBlocks = Object.entries(themes)
  .map(([name, def]) => {
    const { surface, accents: accentOverride } = normalizeTheme(def);
    const rules: string[] = [];
    if (surface && surface !== tint) {
      surfaceRoles.forEach((r) =>
        rules.push(`  --magma-tint-${r}: var(--surface-${surface}-${r});`),
      );
      borderRoles.forEach((r) =>
        rules.push(`  --magma-tint-border-${r}: var(--border-${surface}-${r});`),
      );
      textRoles.forEach((r) =>
        rules.push(`  --magma-tint-text-${r}: var(--text-${surface}-${r});`),
      );
    }
    if (accentOverride) {
      Object.entries(accentOverride).forEach(([role, family]) => {
        rules.push(`  --magma-tint-accent-${role}-surface: var(--${family}-${hueSteps.surface});`);
        rules.push(`  --magma-tint-accent-${role}-fg: var(--${family}-${hueSteps.fg});`);
        rules.push(`  --magma-tint-accent-${role}-border: var(--${family}-${hueSteps.border});`);
        rules.push(
          `  --magma-tint-accent-${role}-emphasis: var(--${family}-${hueSteps.emphasis});`,
        );
        Object.entries(accentStateSteps).forEach(([state, step]) =>
          rules.push(`  --magma-tint-accent-${role}-${state}: var(--${family}-${step});`),
        );
      });
    }
    return rules.length ? `:root[data-theme-name='${name}'] {\n${rules.join('\n')}\n}` : '';
  })
  .filter(Boolean);
const themesCss = `${HEADER('Named themes - retint the --magma-tint-* block per data-theme-name (spec 8).')}\n${themeBlocks.join('\n\n')}\n`;

async function main() {
  const cssDir = join(BUILD_DIR, 'css');
  const tailwindDir = join(BUILD_DIR, 'tailwind');
  await mkdir(cssDir, { recursive: true });
  await mkdir(tailwindDir, { recursive: true });
  await writeFile(join(cssDir, 'semantic.css'), layerCss, 'utf8');
  await writeFile(join(tailwindDir, 'semantic.css'), bridgeCss, 'utf8');
  await writeFile(join(cssDir, 'themes.css'), themesCss, 'utf8');
  console.info(
    chalk.green(
      `Generated semantic layer: ${bridge.length} tokens + ${themeBlocks.length} named themes ` +
        `(build/css/semantic.css + build/tailwind/semantic.css + build/css/themes.css).`,
    ),
  );
}

main().catch((error) => {
  console.error(chalk.red(error instanceof Error ? (error.stack ?? error.message) : String(error)));
  process.exitCode = 1;
});
