import chalk from 'chalk';
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { BUILD_DIR } from './meta';
import { semantic } from '../../design-tokens/semantic.config';

/**
 * Generate the semantic color layer (A9) from design-tokens/semantic.config.ts:
 *  - build/css/semantic.css        the `--magma-*` layer components consume
 *  - build/tailwind/semantic.css   the Tailwind `@theme` bridge (--color-* re-exports)
 *
 * Both are GENERATED and gitignored; they are staged under build/ (out of the
 * hand-authored source dirs) and the copy step ships them to dist. The
 * tracked contract is design-tokens/semantic.config.ts. Text roles come from A7's `--text-*`
 * primitives; surfaces/borders resolve through the `--magma-tint-*` indirection
 * so a named theme retints with one swap (B2, spec section 8).
 */

const {
  tint,
  surfaceRoles,
  borderRoles,
  textRoles,
  borderFocus,
  seed,
  hues,
  hueSteps,
  neutralHueSteps,
} = semantic;

const HEADER = (what: string) =>
  `/*\n  ${what}\n  GENERATED by scripts/semantic.ts from semantic.config.ts - do NOT edit by hand.\n` +
  `  Contract + rationale: semantic.config.ts and SEMANTIC_COLOR_SPEC.md.\n*/\n`;

// (magma token suffix, Tailwind color name) pairs, collected while building the
// layer so the bridge stays in exact sync with what the layer declares.
const bridge: Array<[string, string]> = [];
/** A bridged `--magma-<magma>: var(--<source>);` line; `tw` is its Tailwind color name. */
const alias = (magma: string, source: string, tw: string): string => {
  bridge.push([magma, tw]);
  return `  --magma-${magma}: var(--${source});`;
};

const layer: string[] = ['', ':root {'];

// 1. tint indirection (internal; not bridged to Tailwind). The tint block IS the
//    theme: a named theme repoints these to another family and retints surface,
//    border AND text together in one swap (spec 8). Text joins the block so the
//    foreground retints WITH its surface, kept to one coherent, contrast-paired
//    family (A7 verifies text against that same family's surfaces).
layer.push(
  '  /* Active tint = the theme (spec 8): a named theme retints surface + border + text by repointing --magma-tint-*. */',
);
surfaceRoles.forEach((r) => layer.push(`  --magma-tint-${r}: var(--surface-${tint}-${r});`));
borderRoles.forEach((r) => layer.push(`  --magma-tint-border-${r}: var(--border-${tint}-${r});`));
textRoles.forEach((r) => layer.push(`  --magma-tint-text-${r}: var(--text-${tint}-${r});`));
layer.push(`  --magma-tint-text-on-emphasis: var(--${seed});`);

// 2. surfaces (from the tint pointers)
layer.push('', '  /* Surfaces - elevation + same-plane prominence (spec 6.1) */');
surfaceRoles.forEach((r) => layer.push(alias(`surface-${r}`, `magma-tint-${r}`, `surface-${r}`)));

// 3. text roles - resolve through the tint-text indirection so a theme retints
//    the foreground with its surface (values are the by-target --text-*, A7).
layer.push(
  '',
  '  /* Text - prominence, by APCA target (spec 6.2 / 9, A7); retints via --magma-tint-text-* */',
);
textRoles.forEach((r) => layer.push(alias(`text-${r}`, `magma-tint-text-${r}`, `fg-${r}`)));
layer.push(alias('text-on-emphasis', 'magma-tint-text-on-emphasis', 'fg-on-emphasis'));

// 4. borders (from the tint pointers); focus is an accent
layer.push('', '  /* Border - prominence (spec 6.3); focus is an accent, not a neutral level */');
borderRoles.forEach((r) =>
  layer.push(alias(`border-${r}`, `magma-tint-border-${r}`, `border-${r}`)),
);
layer.push(alias('border-focus', borderFocus, 'border-focus'));

// 5. hues - colored families carry the full quintet; neutral omits surface (spec 6.4).
//    The neutral family's "emphasis" pair is NOT a saturated fill like the colored
//    hues: it is the INVERSE SURFACE role (a dark chip in light mode, light in dark -
//    toast, tooltip). It is emitted under role names --magma-surface-inverse /
//    --magma-on-inverse (Material inverseSurface), decoupled from the colored
//    <hue>-emphasis fills. The former --magma-neutral-emphasis / -on-emphasis names
//    stay as DEPRECATED aliases (one release) so existing consumers keep resolving.
Object.entries(hues).forEach(([hue, { family, partial }]) => {
  layer.push('', `  /* ${hue} (${family}) */`);
  const steps = partial ? neutralHueSteps : hueSteps;
  if (!partial)
    layer.push(alias(`${hue}-surface`, `${family}-${hueSteps.surface}`, `${hue}-surface`));
  layer.push(alias(`${hue}-fg`, `${family}-${steps.fg}`, `${hue}-fg`));
  layer.push(alias(`${hue}-border`, `${family}-${steps.border}`, `${hue}-border`));
  if (partial) {
    // inverse-surface role (renamed from neutral-emphasis / -on-emphasis)
    layer.push(alias('surface-inverse', `${family}-${steps.emphasis}`, 'surface-inverse'));
    layer.push(alias('on-inverse', seed, 'on-inverse'));
    layer.push('  /* deprecated: renamed to --magma-surface-inverse / --magma-on-inverse */');
    layer.push(alias(`${hue}-emphasis`, 'magma-surface-inverse', `${hue}-emphasis`));
    layer.push(alias(`${hue}-on-emphasis`, 'magma-on-inverse', `${hue}-on-emphasis`));
  } else {
    layer.push(alias(`${hue}-emphasis`, `${family}-${steps.emphasis}`, `${hue}-emphasis`));
    layer.push(alias(`${hue}-on-emphasis`, seed, `${hue}-on-emphasis`));
  }
});

layer.push('}', '');

const bridgeBody = bridge
  .map(([magma, tw]) => `  --color-${tw}: rgb(var(--magma-${magma}));`)
  .join('\n');
const bridgeCss = `${HEADER('Tailwind bridge for the semantic color layer.')}\n@theme {\n${bridgeBody}\n}\n`;
const layerCss = `${HEADER('Semantic color layer (--magma-*) - the contract components consume.')}${layer.join('\n')}`;

async function main() {
  const cssDir = join(BUILD_DIR, 'css');
  const tailwindDir = join(BUILD_DIR, 'tailwind');
  await mkdir(cssDir, { recursive: true });
  await mkdir(tailwindDir, { recursive: true });
  await writeFile(join(cssDir, 'semantic.css'), layerCss, 'utf8');
  await writeFile(join(tailwindDir, 'semantic.css'), bridgeCss, 'utf8');
  console.info(
    chalk.green(
      `Generated semantic layer: ${bridge.length} tokens (build/css/semantic.css + build/tailwind/semantic.css).`,
    ),
  );
}

main().catch((error) => {
  console.error(chalk.red(error instanceof Error ? (error.stack ?? error.message) : String(error)));
  process.exitCode = 1;
});
