import chalk from 'chalk';
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { BUILD_DIR, PROJECT_DIR } from './meta';
import {
  semantic,
  accentInfix,
  accentTintOverride,
  contrastTintOverride,
  emphasisStateSteps,
  hueContrastOverride,
  scaleFamily,
  scaleStepList,
  scaleTintOverride,
  type ThemeDef,
} from '../../design-tokens/semantic.config';
import { readFile, readdir } from 'fs/promises';
import { resolve } from 'path';

/**
 * Generate the semantic color layer (A9) from design-tokens/semantic.config.ts:
 *  - build/css/semantic.css        the `--magma-*` layer components consume
 *  - build/tailwind/semantic.css   the Tailwind `@theme` bridge (--color-* re-exports)
 *  - build/css/themes.css          named-theme overrides (data-theme-name, spec 8)
 *
 * All are GENERATED and gitignored; they are staged under build/ (out of the
 * hand-authored source dirs) and the copy step ships them to dist. The
 * tracked contract is design-tokens/semantic.config.ts. Text roles come from A7's `--text-*`
 * primitives; surfaces/borders resolve through the `--magma-tint-*` indirection
 * so a named theme retints with one swap (B2, spec section 8).
 */

const {
  tint,
  surfaceRoles,
  borderRoles,
  textRoles,
  borderFocus,
  seed,
  hues,
  hueSteps,
  washSteps,
  shadowStep,
  hueRoles,
  neutralHueSteps,
  accents,
  accentStateSteps,
  themes,
} = semantic;

const HEADER = (what: string) =>
  `/*\n  ${what}\n  GENERATED by scripts/semantic.ts from semantic.config.ts - do NOT edit by hand.\n` +
  `  Contract + rationale: semantic.config.ts and SEMANTIC_COLOR_SPEC.md.\n*/\n`;

// (magma token suffix, Tailwind color name) pairs, collected while building the
// layer so the bridge stays in exact sync with what the layer declares.
const bridge: Array<[string, string]> = [];
/** A bridged `--magma-<magma>: var(--<source>);` line; `tw` is its Tailwind color name. */
const alias = (magma: string, source: string, tw: string): string => {
  bridge.push([magma, tw]);
  return `  --magma-${magma}: var(--${source});`;
};

const layer: string[] = ['', ':root {'];

// 1. tint indirection (internal; not bridged to Tailwind). The tint block IS the
//    theme: a named theme repoints these to another family and retints surface,
//    border AND text together in one swap (spec 8). Text joins the block so the
//    foreground retints WITH its surface, kept to one coherent, contrast-paired
//    family (A7 verifies text against that same family's surfaces).
layer.push(
  '  /* Active tint = the theme (spec 8): a named theme retints surface + border + text by repointing --magma-tint-*. */',
);
surfaceRoles.forEach((r) => layer.push(`  --magma-tint-${r}: var(--surface-${tint}-${r});`));
borderRoles.forEach((r) => layer.push(`  --magma-tint-border-${r}: var(--border-${tint}-${r});`));
textRoles.forEach((r) => layer.push(`  --magma-tint-text-${r}: var(--text-${tint}-${r});`));
layer.push(`  --magma-tint-text-on-emphasis: var(--${seed});`);
layer.push(...scaleTintOverride(scaleFamily(tint)));

// 1b. the active tint's RAMP, for the component sheets that still reach for a raw
//     step where no role covers the use yet (washes, scrims, shadows, decorative
//     fills). Pinned to --tone-neutral-* those uses split the theming in two: the
//     roles retint, the raw steps stay a static neutral. Routed through the tint
//     block they follow the theme like everything else.
//
//     NOT bridged to Tailwind on purpose (hence the raw push, not `alias`): this is
//     a transitional internal vocabulary on the way to naming those uses, not an
//     API to build on. Publishing `--color-scale-09` utilities would make the raw
//     step the easy choice again and freeze the step-indexed habit the semantic
//     layer exists to remove.
layer.push(
  '',
  '  /* Active tint ramp (spec 8) - transitional, for uses no role covers yet; not bridged to Tailwind. */',
);
scaleStepList().forEach((step) =>
  layer.push(`  --magma-scale-${step}: var(--magma-tint-scale-${step});`),
);

// 2. surfaces (from the tint pointers)
layer.push('', '  /* Surfaces - elevation + same-plane prominence (spec 6.1) */');
surfaceRoles.forEach((r) => layer.push(alias(`surface-${r}`, `magma-tint-${r}`, `surface-${r}`)));

// 2b. wash levels - neutral PILLS, not elevation. Same device as the colored
//    `--magma-<hue>-wash-*` of 6.4 and the same `washSteps` map, so the two
//    vocabularies cannot drift; what differs is what they name. A hue names its
//    own family directly (a theme never retints a hue), while the neutral levels
//    resolve through `--magma-tint-scale-*`, so they follow the active theme
//    exactly like the surfaces above.
//    Why they cannot BE surfaces, measured: the elevation ladder moves toward
//    white as it rises in light and toward the ink in dark, while a pill moves
//    toward the ink in BOTH modes (step 08 is #d0d0d0 on #f2f2f2 paper in light,
//    #6b6b6b on #1d1d1d in dark). No elevation role can hold that value - it
//    would have to be `sunken` in light and `raised` in dark. Naming a ramp step
//    gets the mode-flip for free, because the primitive itself flips.
//    Censused for #624: 144 component declarations were naming steps 10/09/08 as
//    a background for exactly this reason, with no role to reach for.
layer.push(
  '',
  '  /* Wash - neutral pills, by how marked they are (spec 6.1b); follows the theme via --magma-tint-scale-* */',
);
Object.entries(washSteps).forEach(([level, step]) =>
  layer.push(alias(`wash-${level}`, `magma-tint-scale-${step}`, `wash-${level}`)),
);

// 2c. shadow ink - the COLOUR a projected shadow is drawn with, not a shadow.
//    Named on the tint ramp's ink extreme, so it flips with the mode: black on a
//    light page, white on a dark one. That flip is the whole point - a pure black
//    shadow is invisible on a dark surface, which is the defect #641 documents on
//    the composite ring tokens.
//    The composite `--shadow-*` tokens live one layer down (design-tokens cosmetic
//    tokens) and name the primitive directly: they cannot reference a role without
//    inverting the layering, and at the ink extreme the difference is 1/255.
layer.push('', '  /* Shadow ink - the colour of a projected shadow (spec 6.1c) */');
layer.push(alias('shadow-ink', `magma-tint-scale-${shadowStep}`, 'shadow-ink'));

// 3. text roles - resolve through the tint-text indirection so a theme retints
//    the foreground with its surface (values are the by-target --text-*, A7).
layer.push(
  '',
  '  /* Text - prominence, by APCA target (spec 6.2 / 9, A7); retints via --magma-tint-text-* */',
);
textRoles.forEach((r) => layer.push(alias(`text-${r}`, `magma-tint-text-${r}`, `fg-${r}`)));
layer.push(alias('text-on-emphasis', 'magma-tint-text-on-emphasis', 'fg-on-emphasis'));

// 4. borders (from the tint pointers); focus follows an accent (theme-aware)
layer.push(
  '',
  '  /* Border - prominence (spec 6.3); focus follows the accent it is named after */',
);
borderRoles.forEach((r) =>
  layer.push(alias(`border-${r}`, `magma-tint-border-${r}`, `border-${r}`)),
);
layer.push(
  alias('border-focus', `magma-accent-${accentInfix(borderFocus)}emphasis`, 'border-focus'),
);

// 5. hues - a colored hue carries the SAME role vocabulary as the neutral
//    scaffolding, on its own family: wash levels (how marked the colored
//    background is), the text ladder and the border ladder. Text and border come
//    from the generated per-family role scales (`--text-success-*`), so the A7
//    guarantee - each step solved against the family's own surfaces - carries over
//    to every hue, and the spec 9.3 promotion applies to them verbatim.
//    Wash levels instead NAME ramp steps (see `washSteps`, shared with the
//    neutral band of 2b): a colored chip
//    moves toward the ink in both modes, which no elevation role can express, and
//    they are NOT called `surface-*` precisely so they cannot be read as the
//    colored parent of `--magma-surface-*`, which is a different thing.
//    The legacy quintet (`-surface`, `-fg`, `-border`) stays as a shortcut onto
//    these roles, so consumers keep resolving AND inherit the promotion.
//    A `partial` hue (neutral) is unchanged: it borrows ramp steps and its
//    emphasis pair is the inverse-surface role, not a colored fill (spec 6.4).
//    The neutral family's "emphasis" pair is NOT a saturated fill like the colored
//    hues: it is the INVERSE SURFACE role (a dark chip in light mode, light in dark -
//    toast, tooltip). It is emitted under role names --magma-surface-inverse /
//    --magma-on-inverse (Material inverseSurface), decoupled from the colored
//    <hue>-emphasis fills. The former --magma-neutral-emphasis / -on-emphasis names
//    stay as DEPRECATED aliases (one release) so existing consumers keep resolving.
Object.entries(hues).forEach(([hue, { family, roles, partial }]) => {
  layer.push('', `  /* ${hue} (${family}) */`);
  if (partial) {
    const steps = neutralHueSteps;
    layer.push(alias(`${hue}-fg`, `${family}-${steps.fg}`, `${hue}-fg`));
    layer.push(alias(`${hue}-border`, `${family}-${steps.border}`, `${hue}-border`));
    // inverse-surface role (renamed from neutral-emphasis / -on-emphasis)
    layer.push(alias('surface-inverse', `${family}-${steps.emphasis}`, 'surface-inverse'));
    layer.push(alias('on-inverse', seed, 'on-inverse'));
    layer.push('  /* deprecated: renamed to --magma-surface-inverse / --magma-on-inverse */');
    layer.push(alias(`${hue}-emphasis`, 'magma-surface-inverse', `${hue}-emphasis`));
    layer.push(alias(`${hue}-on-emphasis`, 'magma-on-inverse', `${hue}-on-emphasis`));
    return;
  }
  if (!roles) {
    // Not a fallback: without the role family there is nothing to point text and
    // border at, and silently dropping back to ramp steps would ship the very
    // hand-picked pairs this layer exists to remove.
    throw new Error(
      `semantic.config: hue "${hue}" is colored but declares no "roles" family; ` +
        `add the generated role family (e.g. roles: '${family.split('-').slice(1).join('-')}').`,
    );
  }
  // wash levels: named ramp steps, so they mode-flip with the primitive
  Object.entries(washSteps).forEach(([level, step]) =>
    layer.push(alias(`${hue}-wash-${level}`, `${family}-${step}`, `${hue}-wash-${level}`)),
  );
  // text + border: the family's own generated role scales (A7 guarantee)
  textRoles.forEach((r) =>
    layer.push(alias(`${hue}-text-${r}`, `text-${roles}-${r}`, `${hue}-fg-${r}`)),
  );
  borderRoles.forEach((r) =>
    layer.push(alias(`${hue}-border-${r}`, `border-${roles}-${r}`, `${hue}-border-${r}`)),
  );
  // the solid saturated fill has no counterpart in the generated scales (those
  // model tinted surfaces, not fills), so it keeps naming a ramp step - and so do
  // its interaction states, shared with the accents through emphasisStateSteps()
  // (spec 6.6). Stated directly on the family, not through a tint pointer: a
  // named theme retints the accents, never a hue.
  layer.push(alias(`${hue}-emphasis`, `${family}-${hueSteps.emphasis}`, `${hue}-emphasis`));
  Object.entries(emphasisStateSteps()).forEach(([state, step]) =>
    layer.push(alias(`${hue}-${state}`, `${family}-${step}`, `${hue}-${state}`)),
  );
  layer.push(alias(`${hue}-on-emphasis`, seed, `${hue}-on-emphasis`));
  // shortcuts onto the roles above (NOT onto the primitives): stated this way
  // they follow the contrast promotion instead of freezing the base step
  layer.push('  /* shortcuts: the roles above at their default prominence */');
  layer.push(alias(`${hue}-surface`, `magma-${hue}-wash-${hueRoles.surface}`, `${hue}-surface`));
  layer.push(alias(`${hue}-fg`, `magma-${hue}-text-${hueRoles.text}`, `${hue}-fg`));
  layer.push(alias(`${hue}-border`, `magma-${hue}-border-${hueRoles.border}`, `${hue}-border`));
});

// 6. accents (variant) - the standout colors (spec 8). Each accent role is a
//    THEME-AWARE quintet: the roles resolve through per-role tint pointers
//    (--magma-tint-accent-*), so a named theme repoints an accent exactly like a
//    surface. Steps reuse the colored-hue quintet (hueSteps); on-emphasis is the
//    seed (family-independent, spec 6.5). The GENERAL `accent` role carries NO
//    infix (--magma-accent-*), promoting the formerly deprecated single alias to
//    the canonical general accent; `ai` infixes (--magma-accent-ai-*). See
//    `accentInfix`.
Object.entries(accents).forEach(([role, family]) => {
  const infix = accentInfix(role);
  layer.push('', `  /* accent ${role} (${family}) */`);
  // tint pointers (internal; repointed per theme, not bridged to Tailwind): the
  // quintet steps + interaction states (spec 6.6 accent exception), each an
  // existing ramp step so it mode-flips and retints per theme like the quintet.
  // Shared with the theme overrides + playground via accentTintOverride().
  accentTintOverride(role, family).forEach((line) => layer.push(line));
  // roles resolve through the tint pointers -> theme-aware
  layer.push(
    alias(`accent-${infix}surface`, `magma-tint-accent-${infix}surface`, `accent-${infix}surface`),
  );
  layer.push(alias(`accent-${infix}fg`, `magma-tint-accent-${infix}fg`, `accent-${infix}fg`));
  layer.push(
    alias(`accent-${infix}border`, `magma-tint-accent-${infix}border`, `accent-${infix}border`),
  );
  layer.push(
    alias(
      `accent-${infix}emphasis`,
      `magma-tint-accent-${infix}emphasis`,
      `accent-${infix}emphasis`,
    ),
  );
  Object.keys(accentStateSteps).forEach((state) =>
    layer.push(
      alias(
        `accent-${infix}${state}`,
        `magma-tint-accent-${infix}${state}`,
        `accent-${infix}${state}`,
      ),
    ),
  );
  layer.push(alias(`accent-${infix}on-emphasis`, seed, `accent-${infix}on-emphasis`));
});

layer.push('}', '');

const bridgeBody = bridge
  .map(([magma, tw]) => `  --color-${tw}: rgb(var(--magma-${magma}));`)
  .join('\n');
const bridgeCss = `${HEADER('Tailwind bridge for the semantic color layer.')}\n@theme {\n${bridgeBody}\n}\n`;

// Contrast (spec 9.3): under `prefers-contrast: more` the text + border roles are
// promoted to a STRONGER same-family step by repointing the --magma-tint-* block, so
// the WHOLE scaffolding gains contrast UPSTREAM - every role that resolves through
// the tint pointers follows, with no per-component --tone-* sheet involved.
//
// Two selectors per scope, the same shape the global dark layer uses (see the
// design-tokens css-vars-rgb template) and the per-component `*-pref-contrast.css`
// sheets: the explicit `pref-contrast-more` class published by mds-pref-contrast,
// then an @media block covering `pref-contrast-system` and a page with no mds-pref
// controller at all. An explicit `pref-contrast-no-preference` matches neither, so
// opting out keeps the base steps.
const CONTRAST_LEVEL = 'more';

/**
 * The contrast blocks for one scope. `scope` is an extra `:root` qualifier (empty
 * for the base layer, `[data-theme-name='x']` for a named theme) and `family` the
 * surface family the promotions draw from - that pairing is what makes the
 * promotion family-independent. `extra` carries rules that belong to the BASE
 * scope only (the hue roles: a named theme does not retint them, so restating
 * them per theme would be dead weight). Empty string when nothing is promoted.
 */
const contrastBlocks = (scope: string, family: string, extra: string[] = []): string => {
  const rules = [...contrastTintOverride(family, CONTRAST_LEVEL), ...extra];
  if (!rules.length) return '';
  return [
    `:root${scope}.pref-contrast-${CONTRAST_LEVEL} {`,
    rules.join('\n'),
    '}',
    '',
    `@media (prefers-contrast: ${CONTRAST_LEVEL}) {`,
    `  :root${scope}.pref-contrast-system,`,
    `  :root${scope}:not([data-magma-pref]) {`,
    rules.map((rule) => `  ${rule}`).join('\n'),
    '  }',
    '}',
  ].join('\n');
};

// Every colored hue promotes its own text + border roles off the SAME table. They
// are stated as roles (not through a tint pointer) because a hue is not retinted
// by a theme; the quintet shortcuts are var() of these roles, so they follow.
const hueContrastRules = Object.entries(hues).flatMap(([hue, { roles, partial }]) =>
  partial || !roles ? [] : hueContrastOverride(hue, roles, CONTRAST_LEVEL),
);
const contrastPromotions =
  contrastTintOverride(tint, CONTRAST_LEVEL).length + hueContrastRules.length;
const contrastCss = contrastBlocks('', tint, hueContrastRules);
const contrastComment =
  '/* Contrast (spec 9.3): pref-contrast-more promotes text + border to stronger same-family steps, on the tint block and on every hue. */';
const layerCss =
  `${HEADER('Semantic color layer (--magma-*) - the contract components consume.')}${layer.join('\n')}` +
  (contrastCss ? `\n${contrastComment}\n${contrastCss}\n` : '');

// Named themes (spec 8): one override block per theme. A theme repoints the
// --magma-tint-* block (surface + border + text) when its surface family differs
// from the base `tint`, AND repoints --magma-tint-accent-<role>-* for every
// accent it overrides - so a theme retints background, foreground AND accents in
// one swap. A theme that changes nothing (base tint, no accent override) emits
// nothing. String shorthand == surface family only (back-compat).
const normalizeTheme = (
  def: ThemeDef,
): { surface?: string; accents?: Record<string, string>; scale?: string } =>
  typeof def === 'string' ? { surface: def } : def;

/** Every ramp family a theme points at, so they can be checked against the tokens. */
const rampFamilies = new Map<string, string>([['(base tint)', scaleFamily(tint)]]);

const themeBlocks = Object.entries(themes)
  .map(([name, def]) => {
    const { surface, accents: accentOverride, scale } = normalizeTheme(def);
    const rules: string[] = [];
    if (surface && surface !== tint) {
      surfaceRoles.forEach((r) =>
        rules.push(`  --magma-tint-${r}: var(--surface-${surface}-${r});`),
      );
      borderRoles.forEach((r) =>
        rules.push(`  --magma-tint-border-${r}: var(--border-${surface}-${r});`),
      );
      textRoles.forEach((r) =>
        rules.push(`  --magma-tint-text-${r}: var(--text-${surface}-${r});`),
      );
      // the ramp retints with the rest of the block, or the raw steps a component
      // still uses would stay on the base tint while its surfaces moved
      const family = scaleFamily(surface, scale);
      rampFamilies.set(name, family);
      rules.push(...scaleTintOverride(family));
    }
    if (accentOverride) {
      Object.entries(accentOverride).forEach(([role, family]) =>
        rules.push(...accentTintOverride(role, family)),
      );
    }
    const block = rules.length ? `:root[data-theme-name='${name}'] {\n${rules.join('\n')}\n}` : '';
    // A theme that retints the tint block must ALSO restate the contrast promotions
    // in its OWN family: `:root[data-theme-name='x']` and `:root.pref-contrast-more`
    // carry the same specificity, so without a theme-scoped block which one wins is
    // decided by the order semantic.css and themes.css happen to be loaded in - the
    // promotion would silently vanish under a named theme. Qualifying the scope with
    // the theme attribute makes it one selector stronger, and the family swap keeps
    // the theme contrasted within its own ramp instead of borrowing the base tint.
    // A theme that only overrides accents leaves the tint text/border alone, so the
    // base block already covers it and nothing extra is emitted.
    const themeContrast =
      surface && surface !== tint ? contrastBlocks(`[data-theme-name='${name}']`, surface) : '';
    return [block, themeContrast].filter(Boolean).join('\n\n');
  })
  .filter(Boolean);
const themesCss = `${HEADER('Named themes - retint the --magma-tint-* block per data-theme-name (spec 8).')}\n${themeBlocks.join('\n\n')}\n`;

/**
 * A theme is only eligible if its family ships a full ramp, not just a surface.
 * Surfaces can be opted in per group, so a family can have `--surface-x-*` and no
 * `--x-01..10` - and a ramp pointer that resolves to nothing would silently put
 * every `--magma-scale-*` consumer back on whatever the fallback chain finds. The
 * step list is checked against the emitted primitives rather than assumed.
 */
const assertRampsExist = async (): Promise<void> => {
  const tokensDir = resolve(PROJECT_DIR, '../design-tokens/dist/css');
  const files = (await readdir(tokensDir)).filter((f) => f.endsWith('.css'));
  const declared = new Set<string>();
  for (const file of files)
    for (const match of (await readFile(resolve(tokensDir, file), 'utf8')).matchAll(
      /^\s*(--[a-z0-9-]+)\s*:/gim,
    ))
      declared.add(match[1]);

  const missing: string[] = [];
  for (const [theme, family] of rampFamilies)
    for (const step of scaleStepList())
      if (!declared.has(`--${family}-${step}`)) missing.push(`${theme} -> --${family}-${step}`);

  if (missing.length) {
    throw new Error(
      `${missing.length} --magma-tint-scale-* pointer(s) have no primitive to resolve to:\n` +
        missing.map((m) => `  ${m}`).join('\n') +
        `\nA theme needs BOTH a surface and a full ramp. Either opt the family's group` +
        ` into the ramp, or name the ramp explicitly in semantic.config.ts themes,` +
        ` e.g. { surface: 'blue', scale: 'label-blue' }.`,
    );
  }
};

async function main() {
  await assertRampsExist();
  const cssDir = join(BUILD_DIR, 'css');
  const tailwindDir = join(BUILD_DIR, 'tailwind');
  await mkdir(cssDir, { recursive: true });
  await mkdir(tailwindDir, { recursive: true });
  await writeFile(join(cssDir, 'semantic.css'), layerCss, 'utf8');
  await writeFile(join(tailwindDir, 'semantic.css'), bridgeCss, 'utf8');
  await writeFile(join(cssDir, 'themes.css'), themesCss, 'utf8');
  console.info(
    chalk.green(
      `Generated semantic layer: ${bridge.length} tokens + ${themeBlocks.length} named themes ` +
        `+ ${contrastPromotions} pref-contrast-more promotions ` +
        `(build/css/semantic.css + build/tailwind/semantic.css + build/css/themes.css).`,
    ),
  );
}

main().catch((error) => {
  console.error(chalk.red(error instanceof Error ? (error.stack ?? error.message) : String(error)));
  process.exitCode = 1;
});
