/**
 * Build the generated base manifest from two Stencil `documentation.json` files.
 *
 *   FROM_VERSION=1.12.0 TO_VERSION=2.0.0-beta \
 *     yarn generate.candidate <v1 documentation.json> <v2 documentation.json> [out.ts]
 *
 * v2 docs come from a `dev` build; v1 docs from a one-off build of `support/v1.x`
 * in a separate worktree. The output is a TypeScript module
 * (`manifest.generated.ts`) consumed by `manifest.ts`, which layers the curated
 * corrections on top. Re-run on each alpha/beta and review the diff.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { generateCandidateManifest, type JsonDocs } from '../src/generate/diff-docs.js';

const [, , v1Path, v2Path, outPath = 'src/manifest/manifest.generated.ts'] = process.argv;

if (!v1Path || !v2Path) {
  console.error(
    'usage: yarn generate.candidate <v1 documentation.json> <v2 documentation.json> [out.ts]',
  );
  process.exit(2);
}

const v1 = JSON.parse(readFileSync(v1Path, 'utf8')) as JsonDocs;
const v2 = JSON.parse(readFileSync(v2Path, 'utf8')) as JsonDocs;

const manifest = generateCandidateManifest(v1, v2, {
  fromVersion: process.env.FROM_VERSION,
  toVersion: process.env.TO_VERSION,
});

const banner =
  '/* AUTO-GENERATED by scripts/build-candidate-manifest.ts — do not edit by hand.\n' +
  ' * Regenerate from the v1/v2 documentation.json; curate via manifest.ts. */\n';
const body = `import { type Manifest } from './schema.js';\n\nexport const generatedManifest: Manifest = ${JSON.stringify(manifest, null, 2)};\n`;

writeFileSync(outPath, `${banner}${body}`);
console.log(`Wrote ${outPath}: ${Object.keys(manifest.components).length} components.`);
