# STENCIL ANGULAR BUILD
stencil-angular-build:
  extends: .base-build
  needs: [base-stencil-build]
  script:
    - nx run stencil-angular:build
  artifacts:
    name: stencil-angular-build
    expire_in: 1 day
    paths:
      - projects/stencil/angular/dist
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - projects/stencil/**/*
        - .deploy/**/*

# STENCIL ANGULAR PUBLISH TEST
stencil-angular-publish-test:
  extends: .base-publish-test
  dependencies: [stencil-angular-build]
  variables:
    BUILD_DIR: projects/stencil/angular/dist/magma-angular
    COMPONENT: magma-angular
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/stencil/angular/magma-angular/package.json

# STENCIL ANGULAR PUBLISH
stencil-angular-publish:
  extends: .base-publish
  dependencies: [stencil-angular-build]
  needs: [stencil-angular-build, stencil-angular-publish-test]
  stage: publish
  variables:
    BUILD_DIR: projects/stencil/angular/dist/magma-angular
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/stencil/angular/magma-angular/package.json

# STENCIL ANGULAR INSTALL TEST
stencil-angular-install-test:
  extends: .base-install-test
  dependencies: [stencil-angular-build]
  needs: [stencil-angular-publish, stencil-angular-build]
  variables:
    BUILD_DIR: projects/stencil/angular/dist/magma-angular
    COMPONENT: magma-angular
    PACK_NAME: maggioli-design-system-magma-angular-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/stencil/angular/magma-angular/package.json
