.base-flex-table-footer:
  variables:
    COMPONENT: mds-flex-table-footer

# ISOLATE
flex-table-footer-isolate:
  extends: [.base-isolate, .base-flex-table-footer]
  dependencies: [base-stencil-build]

# TEST
flex-table-footer-publish-test:
  extends: [.base-stencil-publish-test, .base-flex-table-footer]
  dependencies: [base-stencil-build, flex-table-footer-isolate]

# PUBLISH
flex-table-footer-publish:
  extends: [.base-stencil-publish, .base-flex-table-footer]
  dependencies: [base-stencil-build, flex-table-footer-isolate]
  needs: [base-stencil-build, flex-table-footer-isolate, flex-table-footer-publish-test]

# INSTALL TEST
flex-table-footer-install-test:
  extends: [.base-stencil-install-test, .base-flex-table-footer]
  dependencies: [flex-table-footer-publish, flex-table-footer-isolate]
