export type InputTipItemVariantType =
  | 'count-almost'
  | 'count-almost-full'
  | 'count-empty'
  | 'count-full'
  | 'count-incomplete'
  | 'disabled'
  | 'readonly'
  | 'required'
  | 'required-success'
  | 'text'
