.base-table-row:
  variables:
    COMPONENT: mds-table-row

# TEST
table-row-publish-test:
  extends: [.base-stencil-publish-test, .base-table-row]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
table-row-publish:
  extends: [.base-stencil-publish, .base-table-row]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-row-publish-test]

# INSTALL TEST
table-row-install-test:
  extends: [.base-stencil-install-test, .base-table-row]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-row-publish]
