.base-tab-item:
  variables:
    COMPONENT: mds-tab-item

# TEST
tab-item-publish-test:
  extends: [.base-stencil-publish-test, .base-tab-item]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
tab-item-publish:
  extends: [.base-stencil-publish, .base-tab-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, tab-item-publish-test]

# INSTALL TEST
tab-item-install-test:
  extends: [.base-stencil-install-test, .base-tab-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, tab-item-publish]
