server {

    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    server_name _;
    root /usr/share/nginx/html;
    index index.php index.html index.htm;
    rewrite ^/svg/(.*)$ /storybook/svg/$1 last;

    location ~ ^/storybook {
        root /usr/share/nginx/html; # the directory (/storybook) will be appended to this, so don't include it in the root otherwise it'll look for /var/www/html/storybook/storybook
        try_files $uri $uri/ /storybook/index.html; # try_files will need to be relative to root
    }

    location ~ /\.ht {
        deny all;
    }
}
