.base-input-tip:
  variables:
    COMPONENT: mds-input-tip

# TEST
input-tip-publish-test:
  extends: [.base-stencil-publish-test, .base-input-tip]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
input-tip-publish:
  extends: [.base-stencil-publish, .base-input-tip]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-tip-publish-test]

# INSTALL TEST
input-tip-install-test:
  extends: [.base-stencil-install-test, .base-input-tip]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-tip-publish]
