.base-input-tip:
  variables:
    COMPONENT: mds-input-tip

# ISOLATE
input-tip-isolate:
  extends: [.base-isolate, .base-input-tip]
  dependencies: [base-stencil-build]

# PUBLISH
input-tip-publish:
  extends: [.base-stencil-publish, .base-input-tip]
  dependencies: [base-stencil-build, input-tip-isolate]
  needs: [base-stencil-build, input-tip-isolate, input-tip-publish-test]

# INSTALL TEST
input-tip-install-test:
  extends: [.base-stencil-install-test, .base-input-tip]
  dependencies: [base-stencil-build, input-tip-isolate]
  needs: [base-stencil-build, input-tip-isolate, input-tip-publish]
