.base-modal:
  variables:
    COMPONENT: mds-modal

# TEST
modal-publish-test:
  extends: [.base-stencil-publish-test, .base-modal]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
modal-publish:
  extends: [.base-stencil-publish, .base-modal]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, modal-publish-test]

# INSTALL TEST
modal-install-test:
  extends: [.base-stencil-install-test, .base-modal]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, modal-publish]
