.base-input-field:
  variables:
    COMPONENT: mds-input-field

# TEST
input-field-publish-test:
  extends: [.base-stencil-publish-test, .base-input-field]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
input-field-publish:
  extends: [.base-stencil-publish, .base-input-field]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-field-publish-test]

# INSTALL TEST
input-field-install-test:
  extends: [.base-stencil-install-test, .base-input-field]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-field-publish]
