.base-accordion:
  variables:
    COMPONENT: mds-accordion
  rules:
    - if: $CI_COMMIT_BRANCH == "pipeline"
      changes:
        - $BUILD_DIR/**/*

# BUILD
accordion-build:
  extends: [.base-build, .base-accordion]

# ISOLATE
accordion-isolate:
  extends: [.base-isolate, .base-accordion]
  dependencies: [accordion-build]

# TEST
accordion-stencil-test:
  extends: [.base-stencil-test, .base-accordion]
  dependencies: [accordion-build, accordion-isolate]

accordion-publish-test:
  extends: [.base-publish-test, .base-accordion]
  dependencies: [accordion-build, accordion-isolate]

# PUBLISH
accordion-publish:
  extends: [.base-publish, .base-accordion]
  dependencies: [accordion-build, accordion-isolate]
