# COMMON STENCIL BUILD
base-stencil-build:
  extends: .base-build
  script:
    - nx run design-tokens:build
    - nx run styles:build
    - nx run svg-icons:build
    - nx run icons:build
    - nx run stencil:build.fixtures
    - nx run stencil:build.icons
    - nx run stencil:build
  artifacts:
    name: stencil-build
    expire_in: 1 day
    paths:
      - projects/design-tokens/dist
      - projects/design-tokens/config
      - projects/design-tokens/properties
      - projects/styles/dist
      - projects/svg-icons/dist
      - projects/icons/dist
      - projects/stencil/dist
      - projects/stencil/src/components.d.ts
      - projects/stencil/src/fixtures
      - projects/stencil/assets
      - projects/stencil/react/src
  cache:
    policy: pull-push
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - projects/stencil/**/*
        - .deploy/**/*

stencil-storybook-build:
  extends: .base-build
  stage: build:storybook
  dependencies: [base-stencil-build]
  needs: [base-stencil-build]
  script:
    - nx run stencil:storybook.build
  artifacts:
    name: stencil-storybook-build
    expire_in: 1 day
    paths:
      - projects/stencil/dist-storybook
  cache:
    policy: pull-push
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - projects/stencil/**/*
        - .deploy/**/*

# COMMON STENCIL TEST
stencil-test:
  extends: .base-test
  image: timbru31/node-chrome
  dependencies: [base-stencil-build]
  variables:
    BUILD_DIR: projects/stencil
  rules:
    - if: $CI_COMMIT_BRANCH
      changes:
        - projects/stencil/**/*

# MAGMA PUBLISH TEST
magma-publish-test:
  extends: .base-publish-test
  variables:
    BUILD_DIR: projects/stencil
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/stencil/package.json

# MAGMA PUBLISH
magma-publish:
  extends: .base-publish
  dependencies: [base-stencil-build]
  needs: [magma-publish-test, base-stencil-build]
  stage: publish
  variables:
    BUILD_DIR: projects/stencil
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/stencil/package.json

# MAGMA INSTALL TEST
magma-install-test:
  extends: .base-install-test
  needs: [magma-publish]
  variables:
    BUILD_DIR: projects/stencil
    PACK_NAME: maggioli-design-system-magma-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/stencil/package.json

include:
  - '/projects/stencil/react/.gitlab-ci.yml'
  - '/projects/stencil/angular/.gitlab-ci.yml'
  - '/projects/stencil/src/components/.gitlab-ci.yml'
