# COMMON STENCIL BUILD
base-stencil-build:
  extends: .base-build
  variables:
    COMPONENT: to_be_extended
    BUILD_DIR: projects/stencil/.build/$COMPONENT
  script:
    - nx run design-tokens:build
    - nx run styles:build
    - nx run icons:build
    - nx run stencil:build.fixtures
    - nx run stencil:build.icons
    - nx run stencil:build
  artifacts:
    name: stencil-build
    expire_in: 1 day
    paths:
      - projects/design-tokens/dist
      - projects/design-tokens/config
      - projects/design-tokens/properties
      - projects/styles/dist
      - projects/icons/dist
      - projects/stencil/dist
      - projects/stencil/src/components.d.ts
      - projects/stencil/src/fixtures
      - projects/stencil/assets
  cache:
    policy: pull-push
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(dev|main|pipeline)$/
      changes:
        - projects/stencil/**/*
        - .deploy/**/*

stencil-storybook-build:
  extends: .base-build
  stage: build:storybook
  dependencies: [base-stencil-build]
  needs: [base-stencil-build]
  script:
    - nx run stencil:storybook.build
  artifacts:
    name: stencil-storybook-build
    expire_in: 1 day
    paths:
      - projects/stencil/dist-storybook
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(dev|pipeline)$/
      changes:
        - projects/stencil/**/*
        - .deploy/**/*

# BASE ISOLATE
.base-isolate:
  extends: base-stencil-build
  stage: build:isolate
  script:
    - nx run stencil:publish.isolate.component --component=$COMPONENT
  artifacts:
    name: $COMPONENT-stencil-build
    expire_in: 1 day
    paths:
      - $BUILD_DIR
  cache:
    policy: pull
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(dev|main|pipeline)$/
      changes:
        - projects/stencil/src/components/$COMPONENT/package.json

# COMMON STENCIL TEST
stencil-test:
  extends: base-stencil-build
  image: atools/chrome-headless:java11-node16-latest
  stage: test
  dependencies: [base-stencil-build]
  before_script:
    - cd projects/stencil
  script:
    - npm run test
  cache:
    policy: pull
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(dev|main|pipeline)$/
      changes:
        - projects/stencil/**/*

# BASE STENCIL PUBLISH TEST
.base-stencil-publish-test:
  extends: .base-publish-test
  stage: test
  variables:
    BUILD_DIR: projects/stencil/.build/$COMPONENT
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(main|pipeline)$/
      changes:
        - projects/stencil/src/components/$COMPONENT/package.json

# BASE STENCIL PUBLISH
.base-stencil-publish:
  extends: .base-publish
  dependencies: [base-stencil-build]
  stage: publish
  variables:
    BUILD_DIR: projects/stencil/.build/$COMPONENT
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/stencil/src/components/$COMPONENT/package.json

# BASE STENCIL PUBLISH TEST
.base-stencil-install-test:
  extends: .base-install-test
  variables:
    BUILD_DIR: projects/stencil/.build/$COMPONENT
    PACK_NAME: maggioli-design-system-${COMPONENT}-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/stencil/src/components/$COMPONENT/package.json

include:
  # - '/projects/stencil/src/components/mds-form/.gitlab-ci.yml'
  # - '/projects/stencil/src/components/mds-input-field/.gitlab-ci.yml'
  # - '/projects/stencil/src/components/mds-input-range/.gitlab-ci.yml'
  # - '/projects/stencil/src/components/mds-input-select/.gitlab-ci.yml'
  # - '/projects/stencil/src/components/mds-input-switch-group/.gitlab-ci.yml'
  # - '/projects/stencil/src/components/mds-input-switch/.gitlab-ci.yml'
  # - '/projects/stencil/src/components/mds-kpi-item/.gitlab-ci.yml'
  # - '/projects/stencil/src/components/mds-kpi/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-accordion-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-accordion-timer-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-accordion-timer/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-accordion/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-author/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-avatar/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-badge/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-banner/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-benchmark-bar/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-bibliography/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-breadcrumb-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-breadcrumb/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-button/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-card-content/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-card-footer/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-card-header/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-card-media/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-card/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-chip/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-details/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-dropdown/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-entity/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-file/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-filter-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-filter/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-header-bar/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-header/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-help/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-horizontal-scroll/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-hr/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-icon/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-img/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-input/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-label/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-list-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-list/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-modal/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-note/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-notification/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-paginator-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-paginator/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-price-table-features-cell/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-price-table-features-row/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-price-table-features/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-price-table-header/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-price-table-list-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-price-table-list/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-price-table/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-progress/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-quote/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-separator/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-spinner/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-stepper-bar-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-stepper-bar/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-tab-bar-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-tab-bar/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-tab-item/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-tab/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-table-body/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-table-cell/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-table-footer/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-table-header/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-table-row/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-table/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-text/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-toast/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-tooltip/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-url-view/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-usage/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-video-wall/.gitlab-ci.yml'
  - '/projects/stencil/src/components/mds-zero/.gitlab-ci.yml'
