.base-text:
  variables:
    COMPONENT: mds-text

# TEST
text-publish-test:
  extends: [.base-stencil-publish-test, .base-text]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
text-publish:
  extends: [.base-stencil-publish, .base-text]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, text-publish-test]

# INSTALL TEST
text-install-test:
  extends: [.base-stencil-install-test, .base-text]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, text-publish]
