.base-text:
  variables:
    COMPONENT: mds-text

# ISOLATE
text-isolate:
  extends: [.base-isolate, .base-text]
  dependencies: [base-stencil-build]

# TEST
text-publish-test:
  extends: [.base-stencil-publish-test, .base-text]
  dependencies: [base-stencil-build, text-isolate]

# PUBLISH
text-publish:
  extends: [.base-stencil-publish, .base-text]
  dependencies: [base-stencil-build, text-isolate]
  needs: [base-stencil-build, text-isolate, text-publish-test]

# INSTALL TEST
text-install-test:
  extends: [.base-stencil-install-test, .base-text]
  dependencies: [text-publish, text-isolate]

