.base-usage:
  variables:
    COMPONENT: mds-usage

# ISOLATE
usage-isolate:
  extends: [.base-isolate, .base-usage]
  dependencies: [base-stencil-build]

# TEST
usage-publish-test:
  extends: [.base-stencil-publish-test, .base-usage]
  dependencies: [base-stencil-build, usage-isolate]

# PUBLISH
usage-publish:
  extends: [.base-stencil-publish, .base-usage]
  dependencies: [base-stencil-build, usage-isolate]
  needs: [base-stencil-build, usage-isolate, usage-publish-test]
