.base-kpi-item:
  variables:
    COMPONENT: mds-kpi-item

# TEST
kpi-item-publish-test:
  extends: [.base-stencil-publish-test, .base-kpi-item]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
kpi-item-publish:
  extends: [.base-stencil-publish, .base-kpi-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, kpi-item-publish-test]

# INSTALL TEST
kpi-item-install-test:
  extends: [.base-stencil-install-test, .base-kpi-item]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, kpi-item-publish]
