.base-table-body:
  variables:
    COMPONENT: mds-table-body

# TEST
table-body-publish-test:
  extends: [.base-stencil-publish-test, .base-table-body]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
table-body-publish:
  extends: [.base-stencil-publish, .base-table-body]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-body-publish-test]

# INSTALL TEST
table-body-install-test:
  extends: [.base-stencil-install-test, .base-table-body]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-body-publish]
