.base-table-body:
  variables:
    COMPONENT: mds-table-body

# ISOLATE
table-body-isolate:
  extends: [.base-isolate, .base-table-body]
  dependencies: [base-stencil-build]

# TEST
table-body-publish-test:
  extends: [.base-stencil-publish-test, .base-table-body]
  dependencies: [base-stencil-build, table-body-isolate]

# PUBLISH
table-body-publish:
  extends: [.base-stencil-publish, .base-table-body]
  dependencies: [base-stencil-build, table-body-isolate]
  needs: [base-stencil-build, table-body-isolate, table-body-publish-test]
