.base-url-view:
  variables:
    COMPONENT: mds-url-view

# TEST
url-view-publish-test:
  extends: [.base-stencil-publish-test, .base-url-view]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
url-view-publish:
  extends: [.base-stencil-publish, .base-url-view]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, url-view-publish-test]

# INSTALL TEST
url-view-install-test:
  extends: [.base-stencil-install-test, .base-url-view]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, url-view-publish]
