.base-mention:
  variables:
    COMPONENT: mds-mention

# TEST
mention-publish-test:
  extends: [.base-stencil-publish-test, .base-mention]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
mention-publish:
  extends: [.base-stencil-publish, .base-mention]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, mention-publish-test]

# INSTALL TEST
mention-install-test:
  extends: [.base-stencil-install-test, .base-mention]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, mention-publish]
