.base-radial-menu:
  variables:
    COMPONENT: mds-radial-menu

# TEST
radial-menu-publish-test:
  extends: [.base-stencil-publish-test, .base-radial-menu]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
radial-menu-publish:
  extends: [.base-stencil-publish, .base-radial-menu]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, radial-menu-publish-test]

# INSTALL TEST
radial-menu-install-test:
  extends: [.base-stencil-install-test, .base-radial-menu]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, radial-menu-publish]
