.base-input-select:
  variables:
    COMPONENT: mds-input-select

# ISOLATE
input-select-isolate:
  extends: [.base-isolate, .base-input-select]
  dependencies: [base-build]

# TEST
input-select-publish-test:
  extends: [.base-publish-test, .base-input-select]
  dependencies: [base-build, input-select-isolate]

# PUBLISH
input-select-publish:
  extends: [.base-publish, .base-input-select]
  dependencies: [base-build, input-select-isolate]
