.base-input-select:
  variables:
    COMPONENT: mds-input-select

# ISOLATE
input-select-isolate:
  extends: [.base-isolate, .base-input-select]
  dependencies: [base-stencil-build]

# TEST
input-select-publish-test:
  extends: [.base-stencil-publish-test, .base-input-select]
  dependencies: [base-stencil-build, input-select-isolate]

# PUBLISH
input-select-publish:
  extends: [.base-stencil-publish, .base-input-select]
  dependencies: [base-stencil-build, input-select-isolate]
  needs: [base-stencil-build, input-select-isolate, input-select-publish-test]

# INSTALL TEST
input-select-install-test:
  extends: [.base-stencil-install-test, .base-input-select]
  needs: [input-select-publish]

