.base-quote:
  variables:
    COMPONENT: mds-quote

# ISOLATE
quote-isolate:
  extends: [.base-isolate, .base-quote]
  dependencies: [base-stencil-build]

# TEST
quote-publish-test:
  extends: [.base-stencil-publish-test, .base-quote]
  dependencies: [base-stencil-build, quote-isolate]

# PUBLISH
quote-publish:
  extends: [.base-stencil-publish, .base-quote]
  dependencies: [base-stencil-build, quote-isolate]
  needs: [base-stencil-build, quote-isolate, quote-publish-test]
