.base-quote:
  variables:
    COMPONENT: mds-quote

# TEST
quote-publish-test:
  extends: [.base-stencil-publish-test, .base-quote]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
quote-publish:
  extends: [.base-stencil-publish, .base-quote]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, quote-publish-test]

# INSTALL TEST
quote-install-test:
  extends: [.base-stencil-install-test, .base-quote]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, quote-publish]
