.base-emoji:
  variables:
    COMPONENT: mds-emoji

# TEST
emoji-publish-test:
  extends: [.base-stencil-publish-test, .base-emoji]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
emoji-publish:
  extends: [.base-stencil-publish, .base-emoji]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, emoji-publish-test]

# INSTALL TEST
emoji-install-test:
  extends: [.base-stencil-install-test, .base-emoji]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, emoji-publish]
