.base-input-button:
  variables:
    COMPONENT: mds-input-button

# ISOLATE
input-button-isolate:
  extends: [.base-isolate, .base-input-button]
  dependencies: [base-stencil-build]

# TEST
input-button-publish-test:
  extends: [.base-stencil-publish-test, .base-input-button]
  dependencies: [base-stencil-build, input-button-isolate]

# PUBLISH
input-button-publish:
  extends: [.base-stencil-publish, .base-input-button]
  dependencies: [base-stencil-build, input-button-isolate]
  needs: [base-stencil-build, input-button-isolate, input-button-publish-test]

# INSTALL TEST
input-button-install-test:
  extends: [.base-stencil-install-test, .base-input-button]
  needs: [input-button-publish]

