.base-progress:
  variables:
    COMPONENT: mds-progress

# TEST
progress-publish-test:
  extends: [.base-stencil-publish-test, .base-progress]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
progress-publish:
  extends: [.base-stencil-publish, .base-progress]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, progress-publish-test]

# INSTALL TEST
progress-install-test:
  extends: [.base-stencil-install-test, .base-progress]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, progress-publish]
