.base-tooltip:
  variables:
    COMPONENT: mds-tooltip

# ISOLATE
tooltip-isolate:
  extends: [.base-isolate, .base-tooltip]
  dependencies: [base-stencil-build]

# TEST
tooltip-publish-test:
  extends: [.base-stencil-publish-test, .base-tooltip]
  dependencies: [base-stencil-build, tooltip-isolate]

# PUBLISH
tooltip-publish:
  extends: [.base-stencil-publish, .base-tooltip]
  dependencies: [base-stencil-build, tooltip-isolate]
