.base-table-footer:
  variables:
    COMPONENT: mds-table-footer

# ISOLATE
table-footer-isolate:
  extends: [.base-isolate, .base-table-footer]
  dependencies: [base-stencil-build]

# TEST
table-footer-publish-test:
  extends: [.base-stencil-publish-test, .base-table-footer]
  dependencies: [base-stencil-build, table-footer-isolate]

# PUBLISH
table-footer-publish:
  extends: [.base-stencil-publish, .base-table-footer]
  dependencies: [base-stencil-build, table-footer-isolate]
  needs: [base-stencil-build, table-footer-isolate, table-footer-publish-test]

# INSTALL TEST
table-footer-install-test:
  extends: [.base-stencil-install-test, .base-table-footer]
  needs: [table-footer-publish]

