.base-table-footer:
  variables:
    COMPONENT: mds-table-footer

# TEST
table-footer-publish-test:
  extends: [.base-stencil-publish-test, .base-table-footer]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
table-footer-publish:
  extends: [.base-stencil-publish, .base-table-footer]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-footer-publish-test]

# INSTALL TEST
table-footer-install-test:
  extends: [.base-stencil-install-test, .base-table-footer]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-footer-publish]
