.base-form:
  variables:
    COMPONENT: mds-form

# ISOLATE
form-isolate:
  extends: [.base-isolate, .base-form]
  dependencies: [base-stencil-build]

# TEST
form-publish-test:
  extends: [.base-stencil-publish-test, .base-form]
  dependencies: [base-stencil-build, form-isolate]

# PUBLISH
form-publish:
  extends: [.base-stencil-publish, .base-form]
  dependencies: [base-stencil-build, form-isolate]
  needs: [base-stencil-build, form-isolate, form-publish-test]

# INSTALL TEST
form-install-test:
  extends: [.base-stencil-install-test, .base-form]
  needs: [form-publish]

