.base-button-dropdown:
  variables:
    COMPONENT: mds-button-dropdown

# TEST
button-dropdown-publish-test:
  extends: [.base-stencil-publish-test, .base-button-dropdown]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
button-dropdown-publish:
  extends: [.base-stencil-publish, .base-button-dropdown]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, button-dropdown-publish-test]

# INSTALL TEST
button-dropdown-install-test:
  extends: [.base-stencil-install-test, .base-button-dropdown]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, button-dropdown-publish]
