.base-author:
  variables:
    COMPONENT: mds-author

# TEST
author-publish-test:
  extends: [.base-stencil-publish-test, .base-author]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
author-publish:
  extends: [.base-stencil-publish, .base-author]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, author-publish-test]

# INSTALL TEST
author-install-test:
  extends: [.base-stencil-install-test, .base-author]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, author-publish]
