server {

    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    server_name _;
    root /var/www/html;
    index index.php index.html index.htm;

    location / {
        root /var/www/html/gatsby;
        try_files $uri $uri/ /index.html;
    }

    location /storybook {
        root /var/www/html/storybook;
        try_files $uri $uri/ /index.html;
    }

}

    location ~ /\.ht {
        deny all;
    }
}
