include:
  # Maggioli Common jobs
  - project: maggiolispa/devops/templates
    file:
      - '/cicd/container-build-push.yml'

# DEPLOY STORYBOOK
container-build-push:
  stage: publish
  dependencies: [stencil-storybook-build]
  variables:
    CONTAINER_REGISTRY_URL: $CI_REGISTRY
    CONTAINER_REGISTRY_USERNAME: "$CI_REGISTRY_USR"
    CONTAINER_REGISTRY_PASSWORD: "$CI_REGISTRY_PSW"
    IMAGE_NAME: magma-storybook
    IMAGE_TAGS: $CI_REGISTRY/$IMAGE_NAME:${CI_COMMIT_SHORT_SHA}
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - projects/stencil/**/*
        - .deploy/**/*

deploy-storybook-base:
  stage: deploy:storybook
  image: maggiolieditore.azurecr.io/alpine-ssh-envsubst
  dependencies: [container-build-push]
  tags:
    - maggioli-network
  variables:
    DEPLOY_FOLDER: $DEPLOY_FOLDER_STORYBOOK
    SERVER: $CI_SERVER_IP
    SSH_PRIV_KEY: $CI_SSH_PRIV_KEY
    SSH_USER: $CI_SSH_USER
    ENV: prod
  script:
    - chmod +x .deploy/deploy-storybook.sh
    - .deploy/deploy-storybook.sh
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - projects/stencil/**/*
        - .deploy/**/*
