.base-price-table-features-row:
  variables:
    COMPONENT: mds-price-table-features-row

# TEST
price-table-features-row-publish-test:
  extends: [.base-stencil-publish-test, .base-price-table-features-row]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
price-table-features-row-publish:
  extends: [.base-stencil-publish, .base-price-table-features-row]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, price-table-features-row-publish-test]

# INSTALL TEST
price-table-features-row-install-test:
  extends: [.base-stencil-install-test, .base-price-table-features-row]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, price-table-features-row-publish]
