.base-badge:
  variables:
    COMPONENT: mds-badge

# ISOLATE
badge-isolate:
  extends: [.base-isolate, .base-badge]
  dependencies: [base-stencil-build]

# TEST
badge-publish-test:
  extends: [.base-stencil-publish-test, .base-badge]
  dependencies: [base-stencil-build, badge-isolate]

# PUBLISH
badge-publish:
  extends: [.base-stencil-publish, .base-badge]
  dependencies: [base-stencil-build, badge-isolate]
  needs: [base-stencil-build, badge-isolate, badge-publish-test]
