.base-entity:
  variables:
    COMPONENT: mds-entity

# ISOLATE
entity-isolate:
  extends: [.base-isolate, .base-entity]
  dependencies: [base-stencil-build]

# TEST
entity-publish-test:
  extends: [.base-stencil-publish-test, .base-entity]
  dependencies: [base-stencil-build, entity-isolate]

# PUBLISH
entity-publish:
  extends: [.base-stencil-publish, .base-entity]
  dependencies: [base-stencil-build, entity-isolate]
  needs: [base-stencil-build, entity-isolate, entity-publish-test]

# INSTALL TEST
entity-install-test:
  extends: [.base-stencil-install-test, .base-entity]
  dependencies: [entity-publish, entity-isolate]

