.base-entity:
  variables:
    COMPONENT: mds-entity

# TEST
entity-publish-test:
  extends: [.base-stencil-publish-test, .base-entity]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
entity-publish:
  extends: [.base-stencil-publish, .base-entity]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, entity-publish-test]

# INSTALL TEST
entity-install-test:
  extends: [.base-stencil-install-test, .base-entity]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, entity-publish]
