.base-price-table-features:
  variables:
    COMPONENT: mds-price-table-features

# ISOLATE
price-table-features-isolate:
  extends: [.base-isolate, .base-price-table-features]
  dependencies: [base-stencil-build]

# TEST
price-table-features-publish-test:
  extends: [.base-stencil-publish-test, .base-price-table-features]
  dependencies: [base-stencil-build, price-table-features-isolate]

# PUBLISH
price-table-features-publish:
  extends: [.base-stencil-publish, .base-price-table-features]
  dependencies: [base-stencil-build, price-table-features-isolate]
  needs: [base-stencil-build, price-table-features-isolate, price-table-features-publish-test]

# INSTALL TEST
price-table-features-install-test:
  extends: [.base-stencil-install-test, .base-price-table-features]
  dependencies: [base-stencil-build, price-table-features-isolate]
  needs: [base-stencil-build, price-table-features-isolate, price-table-features-publish]
