.base-price-table-features:
  variables:
    COMPONENT: mds-price-table-features

# TEST
price-table-features-publish-test:
  extends: [.base-stencil-publish-test, .base-price-table-features]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
price-table-features-publish:
  extends: [.base-stencil-publish, .base-price-table-features]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, price-table-features-publish-test]

# INSTALL TEST
price-table-features-install-test:
  extends: [.base-stencil-install-test, .base-price-table-features]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, price-table-features-publish]
