.base-{{ componentName }}:
  variables:
    COMPONENT: mds-{{ componentName }}

# ISOLATE
{{ componentName }}-isolate:
  extends: [.base-isolate, .base-{{ componentName }}]
  dependencies: [base-stencil-build]

# TEST
{{ componentName }}-publish-test:
  extends: [.base-stencil-publish-test, .base-{{ componentName }}]
  dependencies: [base-stencil-build, {{ componentName }}-isolate]

# PUBLISH
{{ componentName }}-publish:
  extends: [.base-stencil-publish, .base-{{ componentName }}]
  dependencies: [base-stencil-build, {{ componentName }}-isolate]
  needs: [base-stencil-build, {{ componentName }}-isolate, {{ componentName }}-publish-test]

# INSTALL TEST
{{ componentName }}-install-test:
  extends: [.base-stencil-install-test, .base-{{ componentName }}]
  dependencies: [base-stencil-build, {{ componentName }}-isolate]
  needs: [base-stencil-build, {{ componentName }}-isolate, {{ componentName }}-publish]
