.base-hr:
  variables:
    COMPONENT: mds-hr

# TEST
hr-publish-test:
  extends: [.base-stencil-publish-test, .base-hr]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
hr-publish:
  extends: [.base-stencil-publish, .base-hr]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, hr-publish-test]

# INSTALL TEST
hr-install-test:
  extends: [.base-stencil-install-test, .base-hr]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, hr-publish]
