.base-hr:
  variables:
    COMPONENT: mds-hr

# ISOLATE
hr-isolate:
  extends: [.base-isolate, .base-hr]
  dependencies: [base-stencil-build]

# TEST
hr-publish-test:
  extends: [.base-stencil-publish-test, .base-hr]
  dependencies: [base-stencil-build, hr-isolate]

# PUBLISH
hr-publish:
  extends: [.base-stencil-publish, .base-hr]
  dependencies: [base-stencil-build, hr-isolate]
  needs: [base-stencil-build, hr-isolate, hr-publish-test]

# INSTALL TEST
hr-install-test:
  extends: [.base-stencil-install-test, .base-hr]
  dependencies: [base-stencil-build, hr-isolate]
  needs: [base-stencil-build, hr-isolate, hr-publish]
