.base-dropdown:
  variables:
    COMPONENT: mds-dropdown

# ISOLATE
dropdown-isolate:
  extends: [.base-isolate, .base-dropdown]
  dependencies: [base-stencil-build]

# TEST
dropdown-publish-test:
  extends: [.base-stencil-publish-test, .base-dropdown]
  dependencies: [base-stencil-build, dropdown-isolate]

# PUBLISH
dropdown-publish:
  extends: [.base-stencil-publish, .base-dropdown]
  dependencies: [base-stencil-build, dropdown-isolate]

