.base-dropdown:
  variables:
    COMPONENT: mds-dropdown

# TEST
dropdown-publish-test:
  extends: [.base-stencil-publish-test, .base-dropdown]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
dropdown-publish:
  extends: [.base-stencil-publish, .base-dropdown]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, dropdown-publish-test]

# INSTALL TEST
dropdown-install-test:
  extends: [.base-stencil-install-test, .base-dropdown]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, dropdown-publish]
