.base-input-upload:
  variables:
    COMPONENT: mds-input-upload

# TEST
input-upload-publish-test:
  extends: [.base-stencil-publish-test, .base-input-upload]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
input-upload-publish:
  extends: [.base-stencil-publish, .base-input-upload]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-upload-publish-test]

# INSTALL TEST
input-upload-install-test:
  extends: [.base-stencil-install-test, .base-input-upload]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-upload-publish]
