# DESIGN TOKENS BUILD
design-tokens-build:
  extends: .base-build
  script:
    - nx run design-tokens:build
  artifacts:
    name: design-tokens-build
    expire_in: 1 day
    paths:
      - projects/design-tokens/dist
      - projects/design-tokens/config
      - projects/design-tokens/properties
  cache:
    policy: pull-push
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(dev|main|pipeline)$/
      changes:
        - projects/design-tokens/**/*

# DESIGN TOKENS PUBLISH TEST
design-tokens-publish-test:
  extends: .base-publish-test
  dependencies: [design-tokens-build]
  stage: test
  variables:
    BUILD_DIR: projects/design-tokens
    COMPONENT: design-tokens
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(main|pipeline)$/
      changes:
        - projects/design-tokens/package.json

# DESIGN TOKENS PUBLISH
design-tokens-publish:
  extends: .base-publish
  dependencies: [design-tokens-build]
  needs: [design-tokens-publish-test, design-tokens-build]
  stage: publish
  variables:
    BUILD_DIR: projects/design-tokens
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/design-tokens/package.json

# DESIGN INSTALL TEST
design-tokens-install-test:
  extends: .base-install-test
  needs: [design-tokens-publish]
  variables:
    BUILD_DIR: projects/design-tokens
    COMPONENT: design-tokens
    PACK_NAME: maggioli-design-system-design-tokens-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/design-tokens/package.json
