# DESIGN TOKENS BUILD
design-tokens-build:
  extends: .base-build
  script:
    - nx run design-tokens:build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(dev|main|pipeline)$/
      changes:
        - projects/design-tokens/**/*

# DESIGN TOKENS PUBLISH TEST
design-tokens-publish-test:
  extends: .base-publish-test
  stage: test
  variables:
    BUILD_DIR: projects/design-tokens
    PACK_NAME: maggioli-design-system-design-tokens-*.tgz
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(main|pipeline)$/
      changes:
        - projects/design-tokens/**/*

# DESIGN TOKENS PUBLISH
design-tokens-publish:
  extends: .base-publish
  stage: publish
  variables:
    BUILD_DIR: projects/design-tokens
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/design-tokens/**/*
