.base-input-range:
  variables:
    COMPONENT: mds-input-range

# ISOLATE
input-range-isolate:
  extends: [.base-isolate, .base-input-range]
  dependencies: [base-stencil-build]

# TEST
input-range-publish-test:
  extends: [.base-stencil-publish-test, .base-input-range]
  dependencies: [base-stencil-build, input-range-isolate]

# PUBLISH
input-range-publish:
  extends: [.base-stencil-publish, .base-input-range]
  dependencies: [base-stencil-build, input-range-isolate]
  needs: [base-stencil-build, input-range-isolate, input-range-publish-test]

# INSTALL TEST
input-range-install-test:
  extends: [.base-stencil-install-test, .base-input-range]
  dependencies: [input-range-publish, input-range-isolate]
