.base-input-range:
  variables:
    COMPONENT: mds-input-range

# TEST
input-range-publish-test:
  extends: [.base-stencil-publish-test, .base-input-range]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
input-range-publish:
  extends: [.base-stencil-publish, .base-input-range]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-range-publish-test]

# INSTALL TEST
input-range-install-test:
  extends: [.base-stencil-install-test, .base-input-range]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, input-range-publish]
