.base-header:
  variables:
    COMPONENT: mds-header

# ISOLATE
header-isolate:
  extends: [.base-isolate, .base-header]
  dependencies: [base-stencil-build]

# TEST
header-publish-test:
  extends: [.base-stencil-publish-test, .base-header]
  dependencies: [base-stencil-build, header-isolate]

# PUBLISH
header-publish:
  extends: [.base-stencil-publish, .base-header]
  dependencies: [base-stencil-build, header-isolate]
  needs: [base-stencil-build, header-isolate, header-publish-test]

# INSTALL TEST
header-install-test:
  extends: [.base-stencil-install-test, .base-header]
  needs: [header-publish]

