.base-header:
  variables:
    COMPONENT: mds-header

# ISOLATE
header-isolate:
  extends: [.base-isolate, .base-header]
  dependencies: [base-build]

# TEST
header-publish-test:
  extends: [.base-publish-test, .base-header]
  dependencies: [base-build, header-isolate]

# PUBLISH
header-publish:
  extends: [.base-publish, .base-header]
  dependencies: [base-build, header-isolate]
