version: '3.1'

services:
  designsystem:
    image: maggiolieditore.azurecr.io/desingsystem:${CI_COMMIT_SHORT_SHA}
    restart: always
    container_name: designsystem
    expose:
      - "443"
    environment:
      - VIRTUAL_HOST=design-system.maggiolicloud.it
      - CERT_NAME=shared
    
networks: 
  default: 
    external: 
      name: nginx-proxy
