.base-push-notifications:
  variables:
    COMPONENT: mds-push-notifications

# TEST
push-notifications-publish-test:
  extends: [.base-stencil-publish-test, .base-push-notifications]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
push-notifications-publish:
  extends: [.base-stencil-publish, .base-push-notifications]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, push-notifications-publish-test]

# INSTALL TEST
push-notifications-install-test:
  extends: [.base-stencil-install-test, .base-push-notifications]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, push-notifications-publish]
