.base-toast:
  variables:
    COMPONENT: mds-toast

# ISOLATE
toast-isolate:
  extends: [.base-isolate, .base-toast]
  dependencies: [base-stencil-build]

# TEST
toast-publish-test:
  extends: [.base-stencil-publish-test, .base-toast]
  dependencies: [base-stencil-build, toast-isolate]

# PUBLISH
toast-publish:
  extends: [.base-stencil-publish, .base-toast]
  dependencies: [base-stencil-build, toast-isolate]
  needs: [base-stencil-build, toast-isolate, toast-publish-test]

# INSTALL TEST
toast-install-test:
  extends: [.base-stencil-install-test, .base-toast]
  needs: [toast-publish]

