.base-tag:
  variables:
    COMPONENT: mds-tag

# ISOLATE
tag-isolate:
  extends: [.base-isolate, .base-tag]
  dependencies: [base-stencil-build]

# TEST
tag-publish-test:
  extends: [.base-stencil-publish-test, .base-tag]
  dependencies: [base-stencil-build, tag-isolate]

# PUBLISH
tag-publish:
  extends: [.base-stencil-publish, .base-tag]
  dependencies: [base-stencil-build, tag-isolate]
  needs: [base-stencil-build, tag-isolate, tag-publish-test]

# INSTALL TEST
tag-install-test:
  extends: [.base-stencil-install-test, .base-tag]
  dependencies: [tag-publish, tag-isolate]

