.base-video-wall:
  variables:
    COMPONENT: mds-video-wall

# ISOLATE
video-wall-isolate:
  extends: [.base-isolate, .base-video-wall]
  dependencies: [base-build]

# TEST
video-wall-publish-test:
  extends: [.base-publish-test, .base-video-wall]
  dependencies: [base-build, video-wall-isolate]

# PUBLISH
video-wall-publish:
  extends: [.base-publish, .base-video-wall]
  dependencies: [base-build, video-wall-isolate]
