.base-video-wall:
  variables:
    COMPONENT: mds-video-wall

# ISOLATE
video-wall-isolate:
  extends: [.base-isolate, .base-video-wall]
  dependencies: [base-stencil-build]

# TEST
video-wall-publish-test:
  extends: [.base-stencil-publish-test, .base-video-wall]
  dependencies: [base-stencil-build, video-wall-isolate]

# PUBLISH
video-wall-publish:
  extends: [.base-stencil-publish, .base-video-wall]
  dependencies: [base-stencil-build, video-wall-isolate]
  needs: [base-stencil-build, video-wall-isolate, video-wall-publish-test]

# INSTALL TEST
video-wall-install-test:
  extends: [.base-stencil-install-test, .base-video-wall]
  dependencies: [video-wall-publish, video-wall-isolate]

