.base-video-wall:
  variables:
    COMPONENT: mds-video-wall

# TEST
video-wall-publish-test:
  extends: [.base-stencil-publish-test, .base-video-wall]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
video-wall-publish:
  extends: [.base-stencil-publish, .base-video-wall]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, video-wall-publish-test]

# INSTALL TEST
video-wall-install-test:
  extends: [.base-stencil-install-test, .base-video-wall]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, video-wall-publish]
