.base-stepper-bar-item:
  variables:
    COMPONENT: mds-stepper-bar-item

# ISOLATE
stepper-bar-item-isolate:
  extends: [.base-isolate, .base-stepper-bar-item]
  dependencies: [base-stencil-build]

# TEST
stepper-bar-item-publish-test:
  extends: [.base-stencil-publish-test, .base-stepper-bar-item]
  dependencies: [base-stencil-build, stepper-bar-item-isolate]

# PUBLISH
stepper-bar-item-publish:
  extends: [.base-stencil-publish, .base-stepper-bar-item]
  dependencies: [base-stencil-build, stepper-bar-item-isolate]
  needs: [base-stencil-build, stepper-bar-item-isolate, stepper-bar-item-publish-test]

# INSTALL TEST
stepper-bar-item-install-test:
  extends: [.base-stencil-install-test, .base-stepper-bar-item]
  dependencies: [base-stencil-build, stepper-bar-item-isolate]
  needs: [base-stencil-build, stepper-bar-item-isolate, stepper-bar-item-publish]
