.base-input:
  variables:
    COMPONENT: mds-input

# ISOLATE
input-isolate:
  extends: [.base-isolate, .base-input]
  dependencies: [base-stencil-build]

# TEST
input-publish-test:
  extends: [.base-stencil-publish-test, .base-input]
  dependencies: [base-stencil-build, input-isolate]

# PUBLISH
input-publish:
  extends: [.base-stencil-publish, .base-input]
  dependencies: [base-stencil-build, input-isolate]
  needs: [base-stencil-build, input-isolate, input-publish-test]
