.base-benchmark-bar:
  variables:
    COMPONENT: mds-benchmark-bar

# ISOLATE
benchmark-bar-isolate:
  extends: [.base-isolate, .base-benchmark-bar]
  dependencies: [base-stencil-build]

# TEST
benchmark-bar-publish-test:
  extends: [.base-stencil-publish-test, .base-benchmark-bar]
  dependencies: [base-stencil-build, benchmark-bar-isolate]

# PUBLISH
benchmark-bar-publish:
  extends: [.base-stencil-publish, .base-benchmark-bar]
  dependencies: [base-stencil-build, benchmark-bar-isolate]
  needs: [base-stencil-build, benchmark-bar-isolate, benchmark-bar-publish-test]

# INSTALL TEST
benchmark-bar-install-test:
  extends: [.base-stencil-install-test, .base-benchmark-bar]
  needs: [benchmark-bar-publish]

