# SVG-ICONS PUBLISH TEST
svg-icons-publish-test:
  extends: .base-publish-test
  stage: test
  variables:
    BUILD_DIR: projects/svg-icons
    COMPONENT: svg-icons
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/svg-icons/package.json

# SVG-ICONS PUBLISH
svg-icons-publish:
  extends: .base-publish
  stage: publish
  needs: [svg-icons-publish-test]
  variables:
    BUILD_DIR: projects/svg-icons
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/svg-icons/package.json

# SVG-ICONS INSTALL TEST
svg-icons-install-test:
  extends: .base-install-test
  needs: [svg-icons-publish]
  variables:
    COMPONENT: svg-icons
    BUILD_DIR: projects/svg-icons
    PACK_NAME: maggioli-design-system-svg-icons-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/svg-icons/package.json
