# SVG ICONS CACHE
.svg-icons-cache:
  cache:
    key:
      files:
        - yarn.lock
      prefix: "${CI_PROJECT_NAME}-svg-icons"
    policy: pull

# SVG-ICONS PUBLISH TEST
svg-icons-publish-test:
  extends: [.base-publish-test, .svg-icons-cache]
  stage: test
  variables:
    BUILD_DIR: projects/svg-icons
    COMPONENT: svg-icons
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(main|pipeline)$/
      changes:
        - projects/svg-icons/package.json

# SVG-ICONS PUBLISH
svg-icons-publish:
  extends: [.base-publish, .svg-icons-cache]
  stage: publish
  needs: [svg-icons-publish-test]
  variables:
    BUILD_DIR: projects/svg-icons
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/svg-icons/package.json

# SVG-ICONS INSTALL TEST
svg-icons-install-test:
  extends: [.base-install-test, .svg-icons-cache]
  needs: [svg-icons-publish]
  variables:
    COMPONENT: svg-icons
    BUILD_DIR: projects/svg-icons
    PACK_NAME: maggioli-design-system-svg-icons-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/svg-icons/package.json
