version: '3.1'

services:
  stage_designsystem:
    image: maggiolieditore.azurecr.io/desingsystem:${CI_COMMIT_SHORT_SHA}
    restart: always
    container_name: stage_designsystem
    ports:
      - "8280:80"