.base-table-cell:
  variables:
    COMPONENT: mds-table-cell

# TEST
table-cell-publish-test:
  extends: [.base-stencil-publish-test, .base-table-cell]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
table-cell-publish:
  extends: [.base-stencil-publish, .base-table-cell]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-cell-publish-test]

# INSTALL TEST
table-cell-install-test:
  extends: [.base-stencil-install-test, .base-table-cell]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, table-cell-publish]
