.base-flex-table-cell:
  variables:
    COMPONENT: mds-flex-table-cell

# ISOLATE
flex-table-cell-isolate:
  extends: [.base-isolate, .base-flex-table-cell]
  dependencies: [base-stencil-build]

# TEST
flex-table-cell-publish-test:
  extends: [.base-stencil-publish-test, .base-flex-table-cell]
  dependencies: [base-stencil-build, flex-table-cell-isolate]

# PUBLISH
flex-table-cell-publish:
  extends: [.base-stencil-publish, .base-flex-table-cell]
  dependencies: [base-stencil-build, flex-table-cell-isolate]
  needs: [base-stencil-build, flex-table-cell-isolate, flex-table-cell-publish-test]

# INSTALL TEST
flex-table-cell-install-test:
  extends: [.base-stencil-install-test, .base-flex-table-cell]
  dependencies: [base-stencil-build, flex-table-cell-isolate]
  needs: [base-stencil-build, flex-table-cell-isolate, flex-table-cell-publish]
