.base-notification:
  variables:
    COMPONENT: mds-notification

# TEST
notification-publish-test:
  extends: [.base-stencil-publish-test, .base-notification]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
notification-publish:
  extends: [.base-stencil-publish, .base-notification]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, notification-publish-test]

# INSTALL TEST
notification-install-test:
  extends: [.base-stencil-install-test, .base-notification]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, notification-publish]
