.base-chip:
  variables:
    COMPONENT: mds-chip

# TEST
chip-publish-test:
  extends: [.base-stencil-publish-test, .base-chip]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
chip-publish:
  extends: [.base-stencil-publish, .base-chip]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, chip-publish-test]

# INSTALL TEST
chip-install-test:
  extends: [.base-stencil-install-test, .base-chip]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, chip-publish]
