/* AUTO-GENERATED by scripts/build-semantic-table.ts - do not edit by hand.
 * Regenerate with `npx nx run codemod:generate.semantic` after a tokens change. */
import { type SemanticTable } from './table.js';

export const semanticTable: SemanticTable = {
  primitives: {
    'tone-porcelain-01': [
      [4, 5, 6],
      [252, 252, 253],
    ],
    'tone-porcelain-02': [
      [35, 43, 53],
      [243, 244, 247],
    ],
    'tone-porcelain-03': [
      [61, 73, 91],
      [225, 229, 235],
    ],
    'tone-porcelain-04': [
      [83, 100, 125],
      [205, 212, 221],
    ],
    'tone-porcelain-05': [
      [99, 120, 150],
      [187, 197, 210],
    ],
    'tone-porcelain-06': [
      [153, 168, 187],
      [140, 156, 178],
    ],
    'tone-porcelain-07': [
      [179, 189, 204],
      [112, 132, 160],
    ],
    'tone-porcelain-08': [
      [201, 208, 219],
      [89, 107, 134],
    ],
    'tone-porcelain-09': [
      [221, 226, 232],
      [69, 83, 103],
    ],
    'tone-porcelain-10': [
      [235, 237, 241],
      [52, 63, 79],
    ],
    'tone-porcelain-seed': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'tone-kaolin-01': [
      [5, 5, 6],
      [252, 252, 253],
    ],
    'tone-kaolin-02': [
      [39, 42, 48],
      [244, 244, 246],
    ],
    'tone-kaolin-03': [
      [67, 72, 82],
      [227, 229, 233],
    ],
    'tone-kaolin-04': [
      [91, 99, 113],
      [208, 211, 217],
    ],
    'tone-kaolin-05': [
      [110, 119, 136],
      [192, 196, 204],
    ],
    'tone-kaolin-06': [
      [160, 166, 178],
      [148, 155, 168],
    ],
    'tone-kaolin-07': [
      [183, 188, 197],
      [122, 132, 148],
    ],
    'tone-kaolin-08': [
      [205, 208, 215],
      [99, 107, 122],
    ],
    'tone-kaolin-09': [
      [223, 225, 229],
      [76, 82, 94],
    ],
    'tone-kaolin-10': [
      [236, 237, 240],
      [58, 63, 71],
    ],
    'tone-kaolin-seed': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'tone-neutral-01': [
      [5, 5, 5],
      [252, 252, 252],
    ],
    'tone-neutral-02': [
      [42, 42, 42],
      [244, 244, 244],
    ],
    'tone-neutral-03': [
      [73, 73, 73],
      [228, 228, 228],
    ],
    'tone-neutral-04': [
      [99, 99, 99],
      [211, 211, 211],
    ],
    'tone-neutral-05': [
      [119, 119, 119],
      [196, 196, 196],
    ],
    'tone-neutral-06': [
      [165, 165, 165],
      [154, 154, 154],
    ],
    'tone-neutral-07': [
      [188, 188, 188],
      [130, 130, 130],
    ],
    'tone-neutral-08': [
      [208, 208, 208],
      [107, 107, 107],
    ],
    'tone-neutral-09': [
      [225, 225, 225],
      [83, 83, 83],
    ],
    'tone-neutral-10': [
      [237, 237, 237],
      [62, 62, 62],
    ],
    'tone-neutral-seed': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'tone-fireclay-01': [
      [6, 5, 5],
      [253, 252, 252],
    ],
    'tone-fireclay-02': [
      [46, 41, 37],
      [246, 244, 243],
    ],
    'tone-fireclay-03': [
      [79, 71, 64],
      [231, 228, 226],
    ],
    'tone-fireclay-04': [
      [108, 97, 87],
      [215, 210, 206],
    ],
    'tone-fireclay-05': [
      [130, 117, 105],
      [202, 195, 189],
    ],
    'tone-fireclay-06': [
      [174, 165, 155],
      [163, 153, 142],
    ],
    'tone-fireclay-07': [
      [195, 187, 180],
      [142, 128, 115],
    ],
    'tone-fireclay-08': [
      [212, 207, 203],
      [115, 105, 94],
    ],
    'tone-fireclay-09': [
      [228, 225, 221],
      [89, 81, 72],
    ],
    'tone-fireclay-10': [
      [238, 237, 235],
      [68, 61, 55],
    ],
    'tone-fireclay-seed': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'tone-bisque-01': [
      [6, 5, 5],
      [252, 252, 252],
    ],
    'tone-bisque-02': [
      [48, 41, 39],
      [246, 245, 244],
    ],
    'tone-bisque-03': [
      [82, 69, 66],
      [232, 228, 227],
    ],
    'tone-bisque-04': [
      [113, 96, 90],
      [217, 210, 207],
    ],
    'tone-bisque-05': [
      [135, 115, 108],
      [204, 194, 191],
    ],
    'tone-bisque-06': [
      [178, 163, 158],
      [168, 151, 146],
    ],
    'tone-bisque-07': [
      [197, 186, 183],
      [147, 126, 120],
    ],
    'tone-bisque-08': [
      [214, 206, 204],
      [121, 103, 97],
    ],
    'tone-bisque-09': [
      [229, 224, 223],
      [94, 79, 75],
    ],
    'tone-bisque-10': [
      [239, 236, 236],
      [71, 60, 57],
    ],
    'tone-bisque-seed': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'status-info-01': [
      [0, 45, 86],
      [232, 245, 252],
    ],
    'status-info-02': [
      [0, 71, 114],
      [207, 235, 248],
    ],
    'status-info-03': [
      [0, 94, 137],
      [180, 224, 244],
    ],
    'status-info-04': [
      [0, 119, 164],
      [145, 210, 239],
    ],
    'status-info-05': [
      [0, 138, 184],
      [112, 198, 234],
    ],
    'status-info-06': [
      [63, 183, 227],
      [0, 159, 206],
    ],
    'status-info-07': [
      [124, 202, 235],
      [0, 134, 180],
    ],
    'status-info-08': [
      [168, 219, 242],
      [0, 107, 151],
    ],
    'status-info-09': [
      [193, 230, 246],
      [0, 88, 131],
    ],
    'status-info-10': [
      [220, 240, 250],
      [0, 63, 105],
    ],
    'status-info': [
      [35, 178, 225],
      [35, 178, 225],
    ],
    'status-success-01': [
      [0, 53, 0],
      [231, 247, 236],
    ],
    'status-success-02': [
      [0, 80, 7],
      [206, 238, 216],
    ],
    'status-success-03': [
      [0, 102, 32],
      [179, 230, 196],
    ],
    'status-success-04': [
      [0, 128, 57],
      [143, 217, 170],
    ],
    'status-success-05': [
      [0, 148, 76],
      [107, 206, 147],
    ],
    'status-success-06': [
      [51, 193, 120],
      [0, 169, 95],
    ],
    'status-success-07': [
      [120, 210, 155],
      [0, 144, 72],
    ],
    'status-success-08': [
      [165, 225, 186],
      [0, 116, 46],
    ],
    'status-success-09': [
      [191, 233, 205],
      [0, 97, 27],
    ],
    'status-success-10': [
      [220, 243, 227],
      [0, 72, 0],
    ],
    'status-success': [
      [33, 191, 115],
      [33, 191, 115],
    ],
    'status-error-01': [
      [89, 0, 0],
      [255, 239, 238],
    ],
    'status-error-02': [
      [132, 0, 11],
      [255, 223, 221],
    ],
    'status-error-03': [
      [165, 33, 40],
      [255, 206, 202],
    ],
    'status-error-04': [
      [196, 64, 65],
      [253, 184, 178],
    ],
    'status-error-05': [
      [217, 83, 82],
      [250, 165, 160],
    ],
    'status-error-06': [
      [246, 142, 136],
      [238, 105, 102],
    ],
    'status-error-07': [
      [251, 171, 166],
      [212, 80, 79],
    ],
    'status-error-08': [
      [254, 198, 194],
      [182, 50, 54],
    ],
    'status-error-09': [
      [255, 214, 211],
      [158, 24, 35],
    ],
    'status-error-10': [
      [255, 232, 230],
      [119, 0, 0],
    ],
    'status-error': [
      [237, 102, 99],
      [237, 102, 99],
    ],
    'status-warning-01': [
      [58, 44, 0],
      [255, 242, 205],
    ],
    'status-warning-02': [
      [88, 66, 0],
      [255, 229, 149],
    ],
    'status-warning-03': [
      [113, 85, 0],
      [255, 213, 89],
    ],
    'status-warning-04': [
      [142, 106, 0],
      [254, 190, 0],
    ],
    'status-warning-05': [
      [164, 123, 0],
      [237, 177, 0],
    ],
    'status-warning-06': [
      [217, 162, 0],
      [187, 141, 0],
    ],
    'status-warning-07': [
      [242, 181, 0],
      [159, 120, 0],
    ],
    'status-warning-08': [
      [255, 205, 57],
      [129, 96, 0],
    ],
    'status-warning-09': [
      [255, 220, 117],
      [107, 80, 0],
    ],
    'status-warning-10': [
      [255, 237, 181],
      [79, 59, 0],
    ],
    'status-warning': [
      [255, 193, 7],
      [255, 193, 7],
    ],
    'label-red-01': [
      [87, 11, 11],
      [253, 240, 240],
    ],
    'label-red-02': [
      [131, 17, 17],
      [251, 225, 225],
    ],
    'label-red-03': [
      [169, 22, 22],
      [249, 208, 208],
    ],
    'label-red-04': [
      [212, 28, 28],
      [246, 187, 187],
    ],
    'label-red-05': [
      [230, 66, 66],
      [244, 167, 167],
    ],
    'label-red-06': [
      [241, 144, 144],
      [236, 106, 106],
    ],
    'label-red-07': [
      [244, 173, 173],
      [229, 56, 56],
    ],
    'label-red-08': [
      [248, 201, 201],
      [192, 25, 25],
    ],
    'label-red-09': [
      [250, 215, 215],
      [159, 21, 21],
    ],
    'label-red-10': [
      [252, 233, 233],
      [118, 15, 15],
    ],
    'label-red': [
      [208, 27, 27],
      [208, 27, 27],
    ],
    'label-amaranth-01': [
      [88, 5, 19],
      [254, 239, 242],
    ],
    'label-amaranth-02': [
      [131, 8, 29],
      [253, 223, 229],
    ],
    'label-amaranth-03': [
      [170, 10, 37],
      [252, 207, 214],
    ],
    'label-amaranth-04': [
      [213, 12, 47],
      [251, 183, 195],
    ],
    'label-amaranth-05': [
      [242, 37, 72],
      [250, 163, 178],
    ],
    'label-amaranth-06': [
      [248, 138, 157],
      [246, 95, 121],
    ],
    'label-amaranth-07': [
      [250, 170, 183],
      [239, 14, 52],
    ],
    'label-amaranth-08': [
      [252, 197, 207],
      [193, 11, 42],
    ],
    'label-amaranth-09': [
      [253, 214, 221],
      [160, 9, 35],
    ],
    'label-amaranth-10': [
      [254, 232, 236],
      [118, 7, 26],
    ],
    'label-amaranth': [
      [244, 63, 94],
      [244, 63, 94],
    ],
    'label-orchid-01': [
      [85, 9, 47],
      [253, 240, 246],
    ],
    'label-orchid-02': [
      [127, 13, 70],
      [252, 223, 237],
    ],
    'label-orchid-03': [
      [165, 17, 90],
      [250, 205, 227],
    ],
    'label-orchid-04': [
      [206, 21, 113],
      [247, 182, 215],
    ],
    'label-orchid-05': [
      [233, 44, 137],
      [245, 163, 203],
    ],
    'label-orchid-06': [
      [243, 137, 189],
      [238, 95, 166],
    ],
    'label-orchid-07': [
      [246, 169, 207],
      [231, 28, 129],
    ],
    'label-orchid-08': [
      [249, 197, 223],
      [187, 19, 102],
    ],
    'label-orchid-09': [
      [251, 213, 232],
      [156, 16, 85],
    ],
    'label-orchid-10': [
      [253, 231, 242],
      [115, 12, 63],
    ],
    'label-orchid': [
      [236, 72, 153],
      [236, 72, 153],
    ],
    'label-purple-01': [
      [60, 5, 112],
      [248, 240, 254],
    ],
    'label-purple-02': [
      [90, 8, 168],
      [240, 225, 254],
    ],
    'label-purple-03': [
      [116, 10, 217],
      [232, 209, 253],
    ],
    'label-purple-04': [
      [150, 51, 245],
      [221, 188, 252],
    ],
    'label-purple-05': [
      [168, 86, 247],
      [212, 170, 251],
    ],
    'label-purple-06': [
      [201, 149, 250],
      [184, 116, 248],
    ],
    'label-purple-07': [
      [215, 176, 251],
      [165, 79, 247],
    ],
    'label-purple-08': [
      [228, 202, 252],
      [133, 17, 244],
    ],
    'label-purple-09': [
      [235, 216, 253],
      [109, 10, 205],
    ],
    'label-purple-10': [
      [244, 233, 254],
      [81, 7, 151],
    ],
    'label-purple': [
      [168, 85, 247],
      [168, 85, 247],
    ],
    'label-violet-01': [
      [43, 7, 127],
      [245, 241, 254],
    ],
    'label-violet-02': [
      [65, 11, 190],
      [235, 226, 253],
    ],
    'label-violet-03': [
      [87, 20, 242],
      [224, 211, 253],
    ],
    'label-violet-04': [
      [126, 73, 245],
      [210, 192, 252],
    ],
    'label-violet-05': [
      [145, 100, 246],
      [198, 175, 251],
    ],
    'label-violet-06': [
      [184, 156, 250],
      [164, 126, 248],
    ],
    'label-violet-07': [
      [202, 181, 251],
      [141, 95, 246],
    ],
    'label-violet-08': [
      [219, 205, 252],
      [111, 53, 244],
    ],
    'label-violet-09': [
      [229, 218, 253],
      [80, 13, 232],
    ],
    'label-violet-10': [
      [240, 234, 254],
      [59, 9, 171],
    ],
    'label-violet': [
      [139, 92, 246],
      [139, 92, 246],
    ],
    'label-blue-01': [
      [5, 26, 127],
      [240, 242, 254],
    ],
    'label-blue-02': [
      [7, 39, 192],
      [224, 229, 254],
    ],
    'label-blue-03': [
      [11, 51, 246],
      [209, 216, 253],
    ],
    'label-blue-04': [
      [63, 94, 248],
      [187, 199, 252],
    ],
    'label-blue-05': [
      [90, 117, 249],
      [170, 184, 252],
    ],
    'label-blue-06': [
      [149, 166, 251],
      [118, 141, 250],
    ],
    'label-blue-07': [
      [175, 189, 252],
      [85, 113, 249],
    ],
    'label-blue-08': [
      [200, 210, 253],
      [42, 77, 247],
    ],
    'label-blue-09': [
      [216, 222, 254],
      [9, 47, 233],
    ],
    'label-blue-10': [
      [233, 236, 254],
      [6, 35, 172],
    ],
    'label-blue': [
      [14, 54, 246],
      [14, 54, 246],
    ],
    'label-sky-01': [
      [4, 48, 68],
      [229, 246, 253],
    ],
    'label-sky-02': [
      [6, 73, 104],
      [201, 236, 252],
    ],
    'label-sky-03': [
      [8, 94, 133],
      [171, 225, 250],
    ],
    'label-sky-04': [
      [10, 118, 167],
      [131, 211, 248],
    ],
    'label-sky-05': [
      [12, 136, 193],
      [94, 198, 245],
    ],
    'label-sky-06': [
      [47, 182, 243],
      [13, 156, 221],
    ],
    'label-sky-07': [
      [106, 203, 246],
      [11, 133, 188],
    ],
    'label-sky-08': [
      [157, 220, 249],
      [9, 107, 152],
    ],
    'label-sky-09': [
      [185, 231, 251],
      [8, 89, 126],
    ],
    'label-sky-10': [
      [217, 241, 253],
      [6, 66, 94],
    ],
    'label-sky': [
      [14, 165, 233],
      [14, 165, 233],
    ],
    'label-aqua-01': [
      [2, 50, 59],
      [217, 248, 254],
    ],
    'label-aqua-02': [
      [2, 75, 88],
      [175, 241, 253],
    ],
    'label-aqua-03': [
      [3, 97, 114],
      [126, 233, 251],
    ],
    'label-aqua-04': [
      [4, 122, 143],
      [40, 218, 249],
    ],
    'label-aqua-05': [
      [5, 141, 165],
      [7, 203, 237],
    ],
    'label-aqua-06': [
      [6, 186, 217],
      [5, 161, 188],
    ],
    'label-aqua-07': [
      [7, 208, 243],
      [5, 137, 160],
    ],
    'label-aqua-08': [
      [99, 229, 251],
      [4, 110, 129],
    ],
    'label-aqua-09': [
      [151, 237, 252],
      [3, 92, 108],
    ],
    'label-aqua-10': [
      [199, 245, 253],
      [2, 68, 80],
    ],
    'label-aqua': [
      [6, 182, 212],
      [6, 182, 212],
    ],
    'label-green-01': [
      [9, 52, 25],
      [223, 249, 233],
    ],
    'label-green-02': [
      [14, 80, 38],
      [188, 243, 209],
    ],
    'label-green-03': [
      [18, 103, 49],
      [148, 236, 180],
    ],
    'label-green-04': [
      [22, 128, 61],
      [85, 226, 136],
    ],
    'label-green-05': [
      [26, 148, 71],
      [37, 213, 102],
    ],
    'label-green-06': [
      [34, 195, 93],
      [29, 169, 81],
    ],
    'label-green-07': [
      [44, 218, 108],
      [25, 145, 69],
    ],
    'label-green-08': [
      [125, 232, 164],
      [20, 116, 56],
    ],
    'label-green-09': [
      [165, 240, 193],
      [17, 97, 46],
    ],
    'label-green-10': [
      [206, 247, 221],
      [12, 71, 34],
    ],
    'label-green': [
      [34, 197, 94],
      [34, 197, 94],
    ],
    'label-lime-01': [
      [33, 51, 6],
      [231, 249, 204],
    ],
    'label-lime-02': [
      [49, 76, 8],
      [206, 243, 148],
    ],
    'label-lime-03': [
      [64, 99, 11],
      [175, 236, 80],
    ],
    'label-lime-04': [
      [81, 124, 13],
      [143, 222, 24],
    ],
    'label-lime-05': [
      [93, 143, 15],
      [134, 207, 22],
    ],
    'label-lime-06': [
      [123, 189, 20],
      [106, 164, 18],
    ],
    'label-lime-07': [
      [137, 211, 23],
      [90, 139, 15],
    ],
    'label-lime-08': [
      [159, 232, 46],
      [73, 112, 12],
    ],
    'label-lime-09': [
      [189, 239, 111],
      [60, 93, 10],
    ],
    'label-lime-10': [
      [219, 247, 178],
      [45, 69, 7],
    ],
    'label-lime': [
      [132, 204, 22],
      [132, 204, 22],
    ],
    'label-yellow-01': [
      [58, 44, 2],
      [253, 243, 210],
    ],
    'label-yellow-02': [
      [87, 67, 3],
      [252, 230, 160],
    ],
    'label-yellow-03': [
      [112, 85, 4],
      [250, 215, 105],
    ],
    'label-yellow-04': [
      [141, 107, 5],
      [247, 193, 27],
    ],
    'label-yellow-05': [
      [161, 124, 6],
      [234, 179, 8],
    ],
    'label-yellow-06': [
      [214, 163, 7],
      [185, 142, 6],
    ],
    'label-yellow-07': [
      [239, 183, 8],
      [158, 120, 5],
    ],
    'label-yellow-08': [
      [249, 207, 78],
      [127, 97, 4],
    ],
    'label-yellow-09': [
      [251, 221, 131],
      [105, 81, 4],
    ],
    'label-yellow-10': [
      [253, 236, 186],
      [78, 59, 3],
    ],
    'label-yellow': [
      [234, 179, 8],
      [234, 179, 8],
    ],
    'label-orange-01': [
      [76, 32, 2],
      [254, 240, 231],
    ],
    'label-orange-02': [
      [114, 48, 3],
      [254, 225, 206],
    ],
    'label-orange-03': [
      [147, 63, 4],
      [253, 210, 179],
    ],
    'label-orange-04': [
      [185, 78, 5],
      [252, 187, 143],
    ],
    'label-orange-05': [
      [213, 90, 5],
      [251, 168, 111],
    ],
    'label-orange-06': [
      [250, 143, 69],
      [244, 103, 6],
    ],
    'label-orange-07': [
      [252, 174, 121],
      [208, 88, 5],
    ],
    'label-orange-08': [
      [253, 201, 166],
      [167, 71, 4],
    ],
    'label-orange-09': [
      [253, 217, 191],
      [139, 59, 4],
    ],
    'label-orange-10': [
      [254, 233, 219],
      [102, 44, 3],
    ],
    'label-orange': [
      [249, 115, 22],
      [249, 115, 22],
    ],
    'variant-primary-01': [
      [5, 40, 103],
      [242, 243, 244],
    ],
    'variant-primary-02': [
      [0, 57, 163],
      [228, 230, 235],
    ],
    'variant-primary-03': [
      [7, 76, 204],
      [213, 218, 228],
    ],
    'variant-primary-04': [
      [36, 103, 231],
      [190, 202, 222],
    ],
    'variant-primary-05': [
      [74, 126, 224],
      [172, 188, 220],
    ],
    'variant-primary-06': [
      [148, 172, 218],
      [110, 148, 220],
    ],
    'variant-primary-07': [
      [178, 192, 220],
      [68, 122, 225],
    ],
    'variant-primary-08': [
      [204, 212, 226],
      [16, 88, 224],
    ],
    'variant-primary-09': [
      [220, 224, 231],
      [4, 70, 195],
    ],
    'variant-primary-10': [
      [236, 237, 240],
      [0, 51, 147],
    ],
    'variant-primary': [
      [0, 55, 158],
      [0, 55, 158],
    ],
    'variant-secondary-01': [
      [25, 43, 88],
      [242, 243, 244],
    ],
    'variant-secondary-02': [
      [18, 59, 156],
      [228, 230, 236],
    ],
    'variant-secondary-03': [
      [15, 73, 210],
      [212, 218, 230],
    ],
    'variant-secondary-04': [
      [46, 101, 233],
      [191, 201, 225],
    ],
    'variant-secondary-05': [
      [81, 125, 228],
      [172, 187, 223],
    ],
    'variant-secondary-06': [
      [150, 171, 223],
      [114, 147, 224],
    ],
    'variant-secondary-07': [
      [179, 192, 224],
      [74, 120, 229],
    ],
    'variant-secondary-08': [
      [205, 211, 228],
      [20, 84, 236],
    ],
    'variant-secondary-09': [
      [220, 223, 232],
      [15, 69, 198],
    ],
    'variant-secondary-10': [
      [236, 237, 240],
      [21, 55, 135],
    ],
    'variant-secondary': [
      [15, 74, 213],
      [15, 74, 213],
    ],
    'variant-ai-01': [
      [43, 7, 127],
      [245, 241, 254],
    ],
    'variant-ai-02': [
      [65, 11, 190],
      [235, 226, 253],
    ],
    'variant-ai-03': [
      [87, 20, 242],
      [224, 211, 253],
    ],
    'variant-ai-04': [
      [126, 73, 245],
      [210, 192, 252],
    ],
    'variant-ai-05': [
      [145, 100, 246],
      [198, 175, 251],
    ],
    'variant-ai-06': [
      [184, 156, 250],
      [164, 126, 248],
    ],
    'variant-ai-07': [
      [202, 181, 251],
      [141, 95, 246],
    ],
    'variant-ai-08': [
      [219, 205, 252],
      [111, 53, 244],
    ],
    'variant-ai-09': [
      [229, 218, 253],
      [80, 13, 232],
    ],
    'variant-ai-10': [
      [240, 234, 254],
      [59, 9, 171],
    ],
    'variant-ai': [
      [139, 92, 246],
      [139, 92, 246],
    ],
    'brand-maggioli-01': [
      [5, 40, 103],
      [242, 243, 244],
    ],
    'brand-maggioli-02': [
      [0, 57, 163],
      [228, 230, 235],
    ],
    'brand-maggioli-03': [
      [7, 76, 204],
      [213, 218, 228],
    ],
    'brand-maggioli-04': [
      [36, 103, 231],
      [190, 202, 222],
    ],
    'brand-maggioli-05': [
      [74, 126, 224],
      [172, 188, 220],
    ],
    'brand-maggioli-06': [
      [148, 172, 218],
      [110, 148, 220],
    ],
    'brand-maggioli-07': [
      [178, 192, 220],
      [68, 122, 225],
    ],
    'brand-maggioli-08': [
      [204, 212, 226],
      [16, 88, 224],
    ],
    'brand-maggioli-09': [
      [220, 224, 231],
      [4, 70, 195],
    ],
    'brand-maggioli-10': [
      [236, 237, 240],
      [0, 51, 147],
    ],
    'brand-maggioli': [
      [0, 55, 158],
      [0, 55, 158],
    ],
    'brand-maggioli-editore-01': [
      [25, 43, 88],
      [242, 243, 244],
    ],
    'brand-maggioli-editore-02': [
      [18, 59, 156],
      [228, 230, 236],
    ],
    'brand-maggioli-editore-03': [
      [15, 73, 210],
      [212, 218, 230],
    ],
    'brand-maggioli-editore-04': [
      [46, 101, 233],
      [191, 201, 225],
    ],
    'brand-maggioli-editore-05': [
      [81, 125, 228],
      [172, 187, 223],
    ],
    'brand-maggioli-editore-06': [
      [150, 171, 223],
      [114, 147, 224],
    ],
    'brand-maggioli-editore-07': [
      [179, 192, 224],
      [74, 120, 229],
    ],
    'brand-maggioli-editore-08': [
      [205, 211, 228],
      [20, 84, 236],
    ],
    'brand-maggioli-editore-09': [
      [220, 223, 232],
      [15, 69, 198],
    ],
    'brand-maggioli-editore-10': [
      [236, 237, 240],
      [21, 55, 135],
    ],
    'brand-maggioli-editore': [
      [15, 74, 213],
      [15, 74, 213],
    ],
    'brand-rnd-01': [
      [52, 45, 37],
      [243, 243, 241],
    ],
    'brand-rnd-02': [
      [81, 67, 49],
      [234, 230, 225],
    ],
    'brand-rnd-03': [
      [107, 86, 57],
      [226, 216, 204],
    ],
    'brand-rnd-04': [
      [139, 106, 64],
      [218, 198, 173],
    ],
    'brand-rnd-05': [
      [163, 122, 68],
      [212, 183, 145],
    ],
    'brand-rnd-06': [
      [204, 165, 111],
      [187, 139, 75],
    ],
    'brand-rnd-07': [
      [214, 188, 154],
      [158, 119, 67],
    ],
    'brand-rnd-08': [
      [222, 210, 193],
      [124, 97, 61],
    ],
    'brand-rnd-09': [
      [229, 223, 214],
      [101, 81, 55],
    ],
    'brand-rnd-10': [
      [239, 237, 234],
      [72, 60, 46],
    ],
    'brand-rnd': [
      [203, 162, 107],
      [203, 162, 107],
    ],
    'surface-porcelain-sunken': [
      [228, 232, 238],
      [1, 2, 5],
    ],
    'surface-porcelain-muted': [
      [232, 235, 241],
      [8, 14, 21],
    ],
    'surface-porcelain-default': [
      [239, 242, 245],
      [21, 29, 41],
    ],
    'surface-porcelain-raised': [
      [247, 248, 250],
      [39, 49, 64],
    ],
    'surface-porcelain-overlay': [
      [255, 255, 255],
      [63, 75, 93],
    ],
    'surface-neutral-sunken': [
      [232, 232, 232],
      [2, 2, 2],
    ],
    'surface-neutral-muted': [
      [235, 235, 235],
      [13, 13, 13],
    ],
    'surface-neutral-default': [
      [242, 242, 242],
      [29, 29, 29],
    ],
    'surface-neutral-raised': [
      [248, 248, 248],
      [48, 48, 48],
    ],
    'surface-neutral-overlay': [
      [255, 255, 255],
      [74, 74, 74],
    ],
    'surface-bisque-sunken': [
      [235, 231, 229],
      [4, 2, 2],
    ],
    'surface-bisque-muted': [
      [238, 234, 233],
      [18, 12, 10],
    ],
    'surface-bisque-default': [
      [244, 241, 240],
      [35, 27, 24],
    ],
    'surface-bisque-raised': [
      [249, 248, 248],
      [56, 45, 42],
    ],
    'surface-bisque-overlay': [
      [255, 255, 255],
      [84, 71, 67],
    ],
    'surface-info-sunken': [
      [209, 237, 250],
      [0, 3, 11],
    ],
    'surface-info-muted': [
      [216, 240, 251],
      [0, 17, 36],
    ],
    'surface-info-default': [
      [229, 245, 252],
      [0, 34, 61],
    ],
    'surface-info-raised': [
      [242, 250, 254],
      [0, 56, 91],
    ],
    'surface-info-overlay': [
      [255, 255, 255],
      [0, 85, 126],
    ],
    'surface-success-sunken': [
      [210, 241, 220],
      [0, 5, 0],
    ],
    'surface-success-muted': [
      [216, 243, 225],
      [0, 22, 0],
    ],
    'surface-success-default': [
      [229, 247, 235],
      [0, 42, 0],
    ],
    'surface-success-raised': [
      [242, 251, 245],
      [0, 66, 7],
    ],
    'surface-success-overlay': [
      [255, 255, 255],
      [0, 97, 30],
    ],
    'surface-error-sunken': [
      [255, 221, 218],
      [14, 0, 0],
    ],
    'surface-error-muted': [
      [255, 226, 223],
      [41, 0, 0],
    ],
    'surface-error-default': [
      [255, 236, 233],
      [70, 0, 0],
    ],
    'surface-error-raised': [
      [255, 245, 244],
      [102, 0, 4],
    ],
    'surface-error-overlay': [
      [255, 255, 255],
      [142, 5, 25],
    ],
    'surface-warning-sunken': [
      [246, 230, 199],
      [8, 1, 0],
    ],
    'surface-warning-muted': [
      [247, 234, 206],
      [30, 5, 0],
    ],
    'surface-warning-default': [
      [250, 241, 222],
      [54, 17, 0],
    ],
    'surface-warning-raised': [
      [253, 248, 238],
      [81, 35, 0],
    ],
    'surface-warning-overlay': [
      [255, 255, 255],
      [114, 60, 0],
    ],
    'border-porcelain-muted': [
      [213, 219, 228],
      [53, 65, 81],
    ],
    'border-porcelain-default': [
      [188, 197, 210],
      [98, 112, 131],
    ],
    'border-porcelain-strong': [
      [128, 141, 160],
      [160, 172, 188],
    ],
    'border-neutral-muted': [
      [219, 219, 219],
      [64, 64, 64],
    ],
    'border-neutral-default': [
      [196, 196, 196],
      [111, 111, 111],
    ],
    'border-neutral-strong': [
      [140, 140, 140],
      [171, 171, 171],
    ],
    'border-bisque-muted': [
      [224, 217, 215],
      [73, 60, 57],
    ],
    'border-bisque-default': [
      [203, 194, 191],
      [122, 107, 102],
    ],
    'border-bisque-strong': [
      [151, 137, 132],
      [180, 168, 164],
    ],
    'border-info-muted': [
      [184, 226, 245],
      [0, 73, 112],
    ],
    'border-info-default': [
      [141, 207, 235],
      [0, 124, 168],
    ],
    'border-info-strong': [
      [18, 154, 196],
      [94, 184, 220],
    ],
    'border-success-muted': [
      [185, 232, 201],
      [0, 85, 20],
    ],
    'border-success-default': [
      [143, 215, 169],
      [0, 137, 65],
    ],
    'border-success-strong': [
      [17, 166, 98],
      [95, 195, 136],
    ],
    'border-error-muted': [
      [255, 203, 198],
      [126, 0, 15],
    ],
    'border-error-default': [
      [254, 171, 165],
      [188, 58, 60],
    ],
    'border-error-strong': [
      [218, 96, 93],
      [241, 136, 131],
    ],
    'border-warning-muted': [
      [239, 216, 168],
      [101, 49, 0],
    ],
    'border-warning-default': [
      [226, 191, 117],
      [155, 98, 0],
    ],
    'border-warning-strong': [
      [184, 130, 0],
      [209, 163, 55],
    ],
    'text-porcelain-default': [
      [4, 5, 6],
      [252, 252, 253],
    ],
    'text-porcelain-muted': [
      [61, 73, 91],
      [225, 229, 235],
    ],
    'text-porcelain-subtle': [
      [83, 100, 125],
      [205, 212, 221],
    ],
    'text-porcelain-disabled': [
      [99, 120, 150],
      [187, 197, 210],
    ],
    'text-neutral-default': [
      [5, 5, 5],
      [252, 252, 252],
    ],
    'text-neutral-muted': [
      [73, 73, 73],
      [228, 228, 228],
    ],
    'text-neutral-subtle': [
      [99, 99, 99],
      [211, 211, 211],
    ],
    'text-neutral-disabled': [
      [119, 119, 119],
      [196, 196, 196],
    ],
    'text-bisque-default': [
      [6, 5, 5],
      [252, 252, 252],
    ],
    'text-bisque-muted': [
      [82, 69, 66],
      [232, 228, 227],
    ],
    'text-bisque-subtle': [
      [113, 96, 90],
      [217, 210, 207],
    ],
    'text-bisque-disabled': [
      [135, 115, 108],
      [204, 194, 191],
    ],
    'text-info-default': [
      [0, 45, 86],
      [232, 245, 252],
    ],
    'text-info-muted': [
      [0, 71, 114],
      [207, 235, 248],
    ],
    'text-info-subtle': [
      [0, 94, 137],
      [180, 224, 244],
    ],
    'text-info-disabled': [
      [0, 138, 184],
      [112, 198, 234],
    ],
    'text-success-default': [
      [0, 53, 0],
      [231, 247, 236],
    ],
    'text-success-muted': [
      [0, 80, 7],
      [206, 238, 216],
    ],
    'text-success-subtle': [
      [0, 102, 32],
      [179, 230, 196],
    ],
    'text-success-disabled': [
      [0, 148, 76],
      [107, 206, 147],
    ],
    'text-error-default': [
      [89, 0, 0],
      [255, 239, 238],
    ],
    'text-error-muted': [
      [132, 0, 11],
      [255, 223, 221],
    ],
    'text-error-subtle': [
      [165, 33, 40],
      [255, 206, 202],
    ],
    'text-error-disabled': [
      [217, 83, 82],
      [250, 165, 160],
    ],
    'text-warning-default': [
      [58, 44, 0],
      [255, 242, 205],
    ],
    'text-warning-muted': [
      [88, 66, 0],
      [255, 229, 149],
    ],
    'text-warning-subtle': [
      [113, 85, 0],
      [255, 213, 89],
    ],
    'text-warning-disabled': [
      [164, 123, 0],
      [237, 177, 0],
    ],
  },
  roles: {
    'surface-sunken': {
      channel: 'background',
      hue: 'neutral',
      light: [232, 232, 232],
      dark: [2, 2, 2],
    },
    'surface-muted': {
      channel: 'background',
      hue: 'neutral',
      light: [235, 235, 235],
      dark: [13, 13, 13],
    },
    'surface-default': {
      channel: 'background',
      hue: 'neutral',
      light: [242, 242, 242],
      dark: [29, 29, 29],
    },
    'surface-raised': {
      channel: 'background',
      hue: 'neutral',
      light: [248, 248, 248],
      dark: [48, 48, 48],
    },
    'surface-overlay': {
      channel: 'background',
      hue: 'neutral',
      light: [255, 255, 255],
      dark: [74, 74, 74],
    },
    'wash-soft': {
      channel: 'background',
      hue: 'neutral',
      light: [237, 237, 237],
      dark: [62, 62, 62],
    },
    'wash-base': {
      channel: 'background',
      hue: 'neutral',
      light: [225, 225, 225],
      dark: [83, 83, 83],
    },
    'wash-strong': {
      channel: 'background',
      hue: 'neutral',
      light: [208, 208, 208],
      dark: [107, 107, 107],
    },
    'fg-default': {
      channel: 'foreground',
      hue: 'neutral',
      light: [5, 5, 5],
      dark: [252, 252, 252],
    },
    'fg-muted': {
      channel: 'foreground',
      hue: 'neutral',
      light: [73, 73, 73],
      dark: [228, 228, 228],
    },
    'fg-subtle': {
      channel: 'foreground',
      hue: 'neutral',
      light: [99, 99, 99],
      dark: [211, 211, 211],
    },
    'fg-disabled': {
      channel: 'foreground',
      hue: 'neutral',
      light: [119, 119, 119],
      dark: [196, 196, 196],
    },
    'fg-on-emphasis': {
      channel: 'foreground',
      hue: 'neutral',
      light: [255, 255, 255],
      dark: [29, 29, 29],
    },
    'border-muted': {
      channel: 'border',
      hue: 'neutral',
      light: [219, 219, 219],
      dark: [64, 64, 64],
    },
    'border-default': {
      channel: 'border',
      hue: 'neutral',
      light: [196, 196, 196],
      dark: [111, 111, 111],
    },
    'border-strong': {
      channel: 'border',
      hue: 'neutral',
      light: [140, 140, 140],
      dark: [171, 171, 171],
    },
    'border-focus': {
      channel: 'border',
      hue: 'neutral',
      light: [36, 103, 231],
      dark: [190, 202, 222],
    },
    'info-wash-soft': {
      channel: 'background',
      hue: 'info',
      light: [220, 240, 250],
      dark: [0, 63, 105],
    },
    'info-wash-base': {
      channel: 'background',
      hue: 'info',
      light: [193, 230, 246],
      dark: [0, 88, 131],
    },
    'info-wash-strong': {
      channel: 'background',
      hue: 'info',
      light: [168, 219, 242],
      dark: [0, 107, 151],
    },
    'info-fg-default': {
      channel: 'foreground',
      hue: 'info',
      light: [0, 45, 86],
      dark: [232, 245, 252],
    },
    'info-fg-muted': {
      channel: 'foreground',
      hue: 'info',
      light: [0, 71, 114],
      dark: [207, 235, 248],
    },
    'info-fg-subtle': {
      channel: 'foreground',
      hue: 'info',
      light: [0, 94, 137],
      dark: [180, 224, 244],
    },
    'info-fg-disabled': {
      channel: 'foreground',
      hue: 'info',
      light: [0, 138, 184],
      dark: [112, 198, 234],
    },
    'info-border-muted': {
      channel: 'border',
      hue: 'info',
      light: [184, 226, 245],
      dark: [0, 73, 112],
    },
    'info-border-default': {
      channel: 'border',
      hue: 'info',
      light: [141, 207, 235],
      dark: [0, 124, 168],
    },
    'info-border-strong': {
      channel: 'border',
      hue: 'info',
      light: [18, 154, 196],
      dark: [94, 184, 220],
    },
    'info-emphasis': {
      channel: 'background',
      hue: 'info',
      light: [0, 119, 164],
      dark: [145, 210, 239],
    },
    'info-emphasis-hover': {
      channel: 'background',
      hue: 'info',
      light: [0, 94, 137],
      dark: [180, 224, 244],
    },
    'info-emphasis-active': {
      channel: 'background',
      hue: 'info',
      light: [0, 71, 114],
      dark: [207, 235, 248],
    },
    'info-on-emphasis': {
      channel: 'foreground',
      hue: 'info',
      light: [255, 255, 255],
      dark: [29, 29, 29],
    },
    'success-wash-soft': {
      channel: 'background',
      hue: 'success',
      light: [220, 243, 227],
      dark: [0, 72, 0],
    },
    'success-wash-base': {
      channel: 'background',
      hue: 'success',
      light: [191, 233, 205],
      dark: [0, 97, 27],
    },
    'success-wash-strong': {
      channel: 'background',
      hue: 'success',
      light: [165, 225, 186],
      dark: [0, 116, 46],
    },
    'success-fg-default': {
      channel: 'foreground',
      hue: 'success',
      light: [0, 53, 0],
      dark: [231, 247, 236],
    },
    'success-fg-muted': {
      channel: 'foreground',
      hue: 'success',
      light: [0, 80, 7],
      dark: [206, 238, 216],
    },
    'success-fg-subtle': {
      channel: 'foreground',
      hue: 'success',
      light: [0, 102, 32],
      dark: [179, 230, 196],
    },
    'success-fg-disabled': {
      channel: 'foreground',
      hue: 'success',
      light: [0, 148, 76],
      dark: [107, 206, 147],
    },
    'success-border-muted': {
      channel: 'border',
      hue: 'success',
      light: [185, 232, 201],
      dark: [0, 85, 20],
    },
    'success-border-default': {
      channel: 'border',
      hue: 'success',
      light: [143, 215, 169],
      dark: [0, 137, 65],
    },
    'success-border-strong': {
      channel: 'border',
      hue: 'success',
      light: [17, 166, 98],
      dark: [95, 195, 136],
    },
    'success-emphasis': {
      channel: 'background',
      hue: 'success',
      light: [0, 128, 57],
      dark: [143, 217, 170],
    },
    'success-emphasis-hover': {
      channel: 'background',
      hue: 'success',
      light: [0, 102, 32],
      dark: [179, 230, 196],
    },
    'success-emphasis-active': {
      channel: 'background',
      hue: 'success',
      light: [0, 80, 7],
      dark: [206, 238, 216],
    },
    'success-on-emphasis': {
      channel: 'foreground',
      hue: 'success',
      light: [255, 255, 255],
      dark: [29, 29, 29],
    },
    'warning-wash-soft': {
      channel: 'background',
      hue: 'warning',
      light: [255, 237, 181],
      dark: [79, 59, 0],
    },
    'warning-wash-base': {
      channel: 'background',
      hue: 'warning',
      light: [255, 220, 117],
      dark: [107, 80, 0],
    },
    'warning-wash-strong': {
      channel: 'background',
      hue: 'warning',
      light: [255, 205, 57],
      dark: [129, 96, 0],
    },
    'warning-fg-default': {
      channel: 'foreground',
      hue: 'warning',
      light: [58, 44, 0],
      dark: [255, 242, 205],
    },
    'warning-fg-muted': {
      channel: 'foreground',
      hue: 'warning',
      light: [88, 66, 0],
      dark: [255, 229, 149],
    },
    'warning-fg-subtle': {
      channel: 'foreground',
      hue: 'warning',
      light: [113, 85, 0],
      dark: [255, 213, 89],
    },
    'warning-fg-disabled': {
      channel: 'foreground',
      hue: 'warning',
      light: [164, 123, 0],
      dark: [237, 177, 0],
    },
    'warning-border-muted': {
      channel: 'border',
      hue: 'warning',
      light: [239, 216, 168],
      dark: [101, 49, 0],
    },
    'warning-border-default': {
      channel: 'border',
      hue: 'warning',
      light: [226, 191, 117],
      dark: [155, 98, 0],
    },
    'warning-border-strong': {
      channel: 'border',
      hue: 'warning',
      light: [184, 130, 0],
      dark: [209, 163, 55],
    },
    'warning-emphasis': {
      channel: 'background',
      hue: 'warning',
      light: [142, 106, 0],
      dark: [254, 190, 0],
    },
    'warning-emphasis-hover': {
      channel: 'background',
      hue: 'warning',
      light: [113, 85, 0],
      dark: [255, 213, 89],
    },
    'warning-emphasis-active': {
      channel: 'background',
      hue: 'warning',
      light: [88, 66, 0],
      dark: [255, 229, 149],
    },
    'warning-on-emphasis': {
      channel: 'foreground',
      hue: 'warning',
      light: [255, 255, 255],
      dark: [29, 29, 29],
    },
    'danger-wash-soft': {
      channel: 'background',
      hue: 'danger',
      light: [255, 232, 230],
      dark: [119, 0, 0],
    },
    'danger-wash-base': {
      channel: 'background',
      hue: 'danger',
      light: [255, 214, 211],
      dark: [158, 24, 35],
    },
    'danger-wash-strong': {
      channel: 'background',
      hue: 'danger',
      light: [254, 198, 194],
      dark: [182, 50, 54],
    },
    'danger-fg-default': {
      channel: 'foreground',
      hue: 'danger',
      light: [89, 0, 0],
      dark: [255, 239, 238],
    },
    'danger-fg-muted': {
      channel: 'foreground',
      hue: 'danger',
      light: [132, 0, 11],
      dark: [255, 223, 221],
    },
    'danger-fg-subtle': {
      channel: 'foreground',
      hue: 'danger',
      light: [165, 33, 40],
      dark: [255, 206, 202],
    },
    'danger-fg-disabled': {
      channel: 'foreground',
      hue: 'danger',
      light: [217, 83, 82],
      dark: [250, 165, 160],
    },
    'danger-border-muted': {
      channel: 'border',
      hue: 'danger',
      light: [255, 203, 198],
      dark: [126, 0, 15],
    },
    'danger-border-default': {
      channel: 'border',
      hue: 'danger',
      light: [254, 171, 165],
      dark: [188, 58, 60],
    },
    'danger-border-strong': {
      channel: 'border',
      hue: 'danger',
      light: [218, 96, 93],
      dark: [241, 136, 131],
    },
    'danger-emphasis': {
      channel: 'background',
      hue: 'danger',
      light: [196, 64, 65],
      dark: [253, 184, 178],
    },
    'danger-emphasis-hover': {
      channel: 'background',
      hue: 'danger',
      light: [165, 33, 40],
      dark: [255, 206, 202],
    },
    'danger-emphasis-active': {
      channel: 'background',
      hue: 'danger',
      light: [132, 0, 11],
      dark: [255, 223, 221],
    },
    'danger-on-emphasis': {
      channel: 'foreground',
      hue: 'danger',
      light: [255, 255, 255],
      dark: [29, 29, 29],
    },
    'neutral-border': {
      channel: 'border',
      hue: 'neutral',
      light: [165, 165, 165],
      dark: [154, 154, 154],
    },
    'surface-inverse': {
      channel: 'background',
      hue: 'neutral',
      light: [42, 42, 42],
      dark: [244, 244, 244],
    },
    'surface-inverse-muted': {
      channel: 'background',
      hue: 'neutral',
      light: [73, 73, 73],
      dark: [228, 228, 228],
    },
    'on-inverse': {
      channel: 'foreground',
      hue: 'neutral',
      light: [255, 255, 255],
      dark: [29, 29, 29],
    },
    'accent-surface': {
      channel: 'background',
      hue: 'accent',
      light: [220, 224, 231],
      dark: [4, 70, 195],
    },
    'accent-fg': {
      channel: 'foreground',
      hue: 'accent',
      light: [7, 76, 204],
      dark: [213, 218, 228],
    },
    'accent-border': {
      channel: 'border',
      hue: 'accent',
      light: [148, 172, 218],
      dark: [110, 148, 220],
    },
    'accent-emphasis': {
      channel: 'background',
      hue: 'accent',
      light: [36, 103, 231],
      dark: [190, 202, 222],
    },
    'accent-emphasis-hover': {
      channel: 'background',
      hue: 'accent',
      light: [7, 76, 204],
      dark: [213, 218, 228],
    },
    'accent-emphasis-active': {
      channel: 'background',
      hue: 'accent',
      light: [0, 57, 163],
      dark: [228, 230, 235],
    },
    'accent-surface-hover': {
      channel: 'background',
      hue: 'accent',
      light: [204, 212, 226],
      dark: [16, 88, 224],
    },
    'accent-surface-subtle': {
      channel: 'background',
      hue: 'accent',
      light: [236, 237, 240],
      dark: [0, 51, 147],
    },
    'accent-on-emphasis': {
      channel: 'foreground',
      hue: 'accent',
      light: [255, 255, 255],
      dark: [29, 29, 29],
    },
    'accent-ai-surface': {
      channel: 'background',
      hue: 'accent-ai',
      light: [229, 218, 253],
      dark: [80, 13, 232],
    },
    'accent-ai-fg': {
      channel: 'foreground',
      hue: 'accent-ai',
      light: [87, 20, 242],
      dark: [224, 211, 253],
    },
    'accent-ai-border': {
      channel: 'border',
      hue: 'accent-ai',
      light: [184, 156, 250],
      dark: [164, 126, 248],
    },
    'accent-ai-emphasis': {
      channel: 'background',
      hue: 'accent-ai',
      light: [126, 73, 245],
      dark: [210, 192, 252],
    },
    'accent-ai-emphasis-hover': {
      channel: 'background',
      hue: 'accent-ai',
      light: [87, 20, 242],
      dark: [224, 211, 253],
    },
    'accent-ai-emphasis-active': {
      channel: 'background',
      hue: 'accent-ai',
      light: [65, 11, 190],
      dark: [235, 226, 253],
    },
    'accent-ai-surface-hover': {
      channel: 'background',
      hue: 'accent-ai',
      light: [219, 205, 252],
      dark: [111, 53, 244],
    },
    'accent-ai-surface-subtle': {
      channel: 'background',
      hue: 'accent-ai',
      light: [240, 234, 254],
      dark: [59, 9, 171],
    },
    'accent-ai-on-emphasis': {
      channel: 'foreground',
      hue: 'accent-ai',
      light: [255, 255, 255],
      dark: [29, 29, 29],
    },
  },
  removed: {
    'tone-slate-01': [
      [28, 34, 42],
      [221, 225, 232],
    ],
    'tone-slate-02': [
      [33, 41, 50],
      [210, 216, 225],
    ],
    'tone-slate-03': [
      [54, 65, 81],
      [171, 182, 199],
    ],
    'tone-slate-04': [
      [71, 85, 106],
      [140, 156, 179],
    ],
    'tone-slate-05': [
      [95, 115, 143],
      [101, 123, 152],
    ],
    'tone-slate-06': [
      [149, 164, 184],
      [66, 79, 99],
    ],
    'tone-slate-07': [
      [207, 213, 223],
      [35, 43, 53],
    ],
    'tone-slate-08': [
      [226, 230, 236],
      [24, 29, 36],
    ],
    'tone-slate-09': [
      [241, 243, 246],
      [14, 17, 21],
    ],
    'tone-slate-10': [
      [247, 248, 250],
      [7, 9, 11],
    ],
    'tone-slate': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'tone-grey-01': [
      [31, 33, 38],
      [222, 225, 229],
    ],
    'tone-grey-02': [
      [37, 40, 46],
      [212, 215, 221],
    ],
    'tone-grey-03': [
      [59, 64, 73],
      [177, 182, 192],
    ],
    'tone-grey-04': [
      [78, 85, 96],
      [148, 155, 168],
    ],
    'tone-grey-05': [
      [105, 114, 130],
      [112, 122, 138],
    ],
    'tone-grey-06': [
      [156, 163, 175],
      [72, 79, 90],
    ],
    'tone-grey-07': [
      [210, 213, 218],
      [39, 43, 49],
    ],
    'tone-grey-08': [
      [230, 231, 234],
      [27, 29, 33],
    ],
    'tone-grey-09': [
      [242, 243, 245],
      [14, 15, 17],
    ],
    'tone-grey-10': [
      [248, 248, 249],
      [8, 9, 10],
    ],
    'tone-grey': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'tone-zinc-01': [
      [33, 33, 37],
      [224, 224, 227],
    ],
    'tone-zinc-02': [
      [40, 40, 44],
      [215, 215, 219],
    ],
    'tone-zinc-03': [
      [64, 64, 70],
      [181, 181, 189],
    ],
    'tone-zinc-04': [
      [84, 84, 92],
      [154, 154, 164],
    ],
    'tone-zinc-05': [
      [112, 112, 124],
      [121, 121, 133],
    ],
    'tone-zinc-06': [
      [161, 161, 170],
      [78, 78, 87],
    ],
    'tone-zinc-07': [
      [212, 212, 216],
      [42, 42, 46],
    ],
    'tone-zinc-08': [
      [230, 230, 232],
      [28, 28, 31],
    ],
    'tone-zinc-09': [
      [243, 243, 244],
      [17, 17, 19],
    ],
    'tone-zinc-10': [
      [248, 248, 249],
      [9, 9, 9],
    ],
    'tone-zinc': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'tone-neutral': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'tone-stone-01': [
      [35, 33, 32],
      [226, 224, 223],
    ],
    'tone-stone-02': [
      [42, 40, 38],
      [218, 215, 214],
    ],
    'tone-stone-03': [
      [68, 64, 61],
      [185, 181, 177],
    ],
    'tone-stone-04': [
      [89, 83, 79],
      [160, 154, 150],
    ],
    'tone-stone-05': [
      [120, 112, 108],
      [127, 120, 114],
    ],
    'tone-stone-06': [
      [167, 161, 157],
      [83, 78, 74],
    ],
    'tone-stone-07': [
      [215, 212, 210],
      [45, 42, 41],
    ],
    'tone-stone-08': [
      [232, 230, 229],
      [30, 28, 27],
    ],
    'tone-stone-09': [
      [244, 243, 242],
      [16, 15, 15],
    ],
    'tone-stone-10': [
      [249, 248, 248],
      [9, 9, 8],
    ],
    'tone-stone': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'status-info-v1-01': [
      [7, 42, 54],
      [174, 226, 244],
    ],
    'status-info-v1-02': [
      [10, 57, 72],
      [128, 210, 238],
    ],
    'status-info-v1-03': [
      [12, 70, 89],
      [82, 194, 231],
    ],
    'status-info-v1-04': [
      [14, 83, 106],
      [34, 177, 225],
    ],
    'status-info-v1-05': [
      [17, 96, 123],
      [28, 160, 204],
    ],
    'status-info-v1-06': [
      [19, 110, 140],
      [25, 144, 184],
    ],
    'status-info-v1-07': [
      [21, 123, 157],
      [23, 130, 166],
    ],
    'status-info-v1-08': [
      [24, 137, 175],
      [20, 117, 149],
    ],
    'status-info-v1-09': [
      [26, 153, 194],
      [18, 103, 132],
    ],
    'status-info-v1-10': [
      [29, 169, 216],
      [16, 89, 114],
    ],
    'status-info-v1-11': [
      [57, 186, 228],
      [13, 77, 98],
    ],
    'status-info-v1-12': [
      [99, 200, 234],
      [11, 65, 83],
    ],
    'status-info-v1-13': [
      [132, 212, 238],
      [9, 55, 70],
    ],
    'status-info-v1-14': [
      [156, 220, 242],
      [9, 49, 62],
    ],
    'status-info-v1-15': [
      [172, 226, 244],
      [7, 43, 55],
    ],
    'status-info-v1-16': [
      [188, 231, 246],
      [7, 38, 48],
    ],
    'status-info-v1-17': [
      [200, 236, 247],
      [6, 32, 41],
    ],
    'status-info-v1-18': [
      [215, 241, 250],
      [4, 25, 32],
    ],
    'status-info-v1-19': [
      [231, 247, 252],
      [3, 17, 22],
    ],
    'status-info-v1-20': [
      [243, 251, 253],
      [2, 10, 13],
    ],
    'status-info-v1': [
      [35, 178, 225],
      [35, 178, 225],
    ],
    'status-success-v1-01': [
      [8, 44, 27],
      [147, 236, 193],
    ],
    'status-success-v1-02': [
      [10, 60, 36],
      [78, 224, 154],
    ],
    'status-success-v1-03': [
      [13, 75, 45],
      [36, 207, 125],
    ],
    'status-success-v1-04': [
      [15, 88, 53],
      [33, 188, 113],
    ],
    'status-success-v1-05': [
      [18, 102, 61],
      [29, 170, 103],
    ],
    'status-success-v1-06': [
      [20, 116, 70],
      [26, 153, 92],
    ],
    'status-success-v1-07': [
      [23, 130, 79],
      [24, 138, 83],
    ],
    'status-success-v1-08': [
      [25, 145, 88],
      [21, 124, 74],
    ],
    'status-success-v1-09': [
      [28, 161, 97],
      [19, 109, 66],
    ],
    'status-success-v1-10': [
      [31, 179, 108],
      [16, 94, 57],
    ],
    'status-success-v1-11': [
      [34, 197, 119],
      [14, 82, 49],
    ],
    'status-success-v1-12': [
      [37, 214, 129],
      [12, 69, 41],
    ],
    'status-success-v1-13': [
      [85, 226, 158],
      [10, 59, 36],
    ],
    'status-success-v1-14': [
      [116, 231, 176],
      [9, 52, 31],
    ],
    'status-success-v1-15': [
      [143, 236, 191],
      [8, 46, 28],
    ],
    'status-success-v1-16': [
      [165, 240, 204],
      [7, 40, 24],
    ],
    'status-success-v1-17': [
      [183, 243, 214],
      [6, 34, 20],
    ],
    'status-success-v1-18': [
      [201, 246, 224],
      [5, 27, 16],
    ],
    'status-success-v1-19': [
      [224, 250, 237],
      [3, 18, 11],
    ],
    'status-success-v1-20': [
      [237, 252, 245],
      [2, 10, 6],
    ],
    'status-success-v1': [
      [33, 191, 115],
      [33, 191, 115],
    ],
    'status-error-v1-01': [
      [80, 11, 9],
      [250, 208, 208],
    ],
    'status-error-v1-02': [
      [106, 14, 12],
      [247, 183, 182],
    ],
    'status-error-v1-03': [
      [130, 17, 15],
      [244, 159, 158],
    ],
    'status-error-v1-04': [
      [153, 21, 18],
      [241, 134, 132],
    ],
    'status-error-v1-05': [
      [176, 24, 20],
      [238, 108, 106],
    ],
    'status-error-v1-06': [
      [201, 27, 23],
      [234, 80, 77],
    ],
    'status-error-v1-07': [
      [224, 30, 26],
      [230, 47, 43],
    ],
    'status-error-v1-08': [
      [232, 64, 60],
      [213, 29, 25],
    ],
    'status-error-v1-09': [
      [236, 95, 92],
      [189, 25, 22],
    ],
    'status-error-v1-10': [
      [239, 123, 120],
      [164, 22, 19],
    ],
    'status-error-v1-11': [
      [242, 146, 144],
      [142, 19, 16],
    ],
    'status-error-v1-12': [
      [245, 168, 166],
      [122, 16, 14],
    ],
    'status-error-v1-13': [
      [247, 186, 184],
      [104, 14, 12],
    ],
    'status-error-v1-14': [
      [248, 197, 196],
      [93, 12, 11],
    ],
    'status-error-v1-15': [
      [249, 206, 205],
      [82, 11, 9],
    ],
    'status-error-v1-16': [
      [250, 215, 214],
      [73, 10, 8],
    ],
    'status-error-v1-17': [
      [251, 224, 224],
      [62, 8, 7],
    ],
    'status-error-v1-18': [
      [252, 232, 231],
      [53, 7, 6],
    ],
    'status-error-v1-19': [
      [253, 240, 239],
      [40, 5, 5],
    ],
    'status-error-v1-20': [
      [254, 247, 247],
      [26, 4, 3],
    ],
    'status-error-v1': [
      [237, 102, 99],
      [237, 102, 99],
    ],
    'status-warning-v1-01': [
      [50, 37, 0],
      [255, 214, 89],
    ],
    'status-warning-v1-02': [
      [66, 49, 0],
      [253, 189, 0],
    ],
    'status-warning-v1-03': [
      [82, 61, 0],
      [230, 172, 0],
    ],
    'status-warning-v1-04': [
      [97, 73, 0],
      [209, 156, 0],
    ],
    'status-warning-v1-05': [
      [113, 85, 0],
      [189, 141, 0],
    ],
    'status-warning-v1-06': [
      [129, 97, 0],
      [170, 127, 0],
    ],
    'status-warning-v1-07': [
      [145, 109, 0],
      [153, 115, 0],
    ],
    'status-warning-v1-08': [
      [161, 121, 0],
      [137, 103, 0],
    ],
    'status-warning-v1-09': [
      [179, 134, 0],
      [121, 91, 0],
    ],
    'status-warning-v1-10': [
      [199, 150, 0],
      [105, 79, 0],
    ],
    'status-warning-v1-11': [
      [219, 164, 0],
      [90, 68, 0],
    ],
    'status-warning-v1-12': [
      [238, 178, 0],
      [77, 57, 0],
    ],
    'status-warning-v1-13': [
      [255, 191, 0],
      [65, 49, 0],
    ],
    'status-warning-v1-14': [
      [255, 203, 48],
      [57, 43, 0],
    ],
    'status-warning-v1-15': [
      [255, 212, 81],
      [51, 38, 0],
    ],
    'status-warning-v1-16': [
      [255, 220, 114],
      [44, 33, 0],
    ],
    'status-warning-v1-17': [
      [255, 228, 147],
      [37, 28, 0],
    ],
    'status-warning-v1-18': [
      [255, 236, 180],
      [29, 22, 0],
    ],
    'status-warning-v1-19': [
      [255, 243, 205],
      [21, 16, 0],
    ],
    'status-warning-v1-20': [
      [255, 249, 230],
      [11, 8, 0],
    ],
    'status-warning-v1': [
      [255, 193, 7],
      [255, 193, 7],
    ],
    'label-amaranth-v1-01': [
      [81, 8, 27],
      [250, 207, 218],
    ],
    'label-amaranth-v1-02': [
      [106, 11, 36],
      [247, 181, 199],
    ],
    'label-amaranth-v1-03': [
      [129, 13, 44],
      [245, 156, 180],
    ],
    'label-amaranth-v1-04': [
      [152, 16, 52],
      [242, 130, 160],
    ],
    'label-amaranth-v1-05': [
      [176, 18, 60],
      [239, 103, 139],
    ],
    'label-amaranth-v1-06': [
      [200, 21, 68],
      [236, 72, 116],
    ],
    'label-amaranth-v1-07': [
      [223, 23, 76],
      [232, 35, 87],
    ],
    'label-amaranth-v1-08': [
      [234, 55, 102],
      [212, 22, 72],
    ],
    'label-amaranth-v1-09': [
      [238, 88, 128],
      [188, 19, 64],
    ],
    'label-amaranth-v1-10': [
      [241, 118, 150],
      [163, 17, 56],
    ],
    'label-amaranth-v1-11': [
      [243, 143, 169],
      [142, 15, 48],
    ],
    'label-amaranth-v1-12': [
      [246, 165, 186],
      [121, 12, 41],
    ],
    'label-amaranth-v1-13': [
      [248, 184, 201],
      [103, 11, 35],
    ],
    'label-amaranth-v1-14': [
      [249, 196, 210],
      [92, 10, 31],
    ],
    'label-amaranth-v1-15': [
      [250, 205, 217],
      [83, 9, 28],
    ],
    'label-amaranth-v1-16': [
      [251, 214, 223],
      [72, 7, 25],
    ],
    'label-amaranth-v1-17': [
      [252, 223, 230],
      [61, 6, 21],
    ],
    'label-amaranth-v1-18': [
      [253, 231, 237],
      [53, 5, 18],
    ],
    'label-amaranth-v1-19': [
      [253, 240, 244],
      [39, 4, 13],
    ],
    'label-amaranth-v1-20': [
      [254, 246, 248],
      [26, 3, 9],
    ],
    'label-amaranth-v1': [
      [234, 52, 100],
      [234, 52, 100],
    ],
    'label-orchid-v1-01': [
      [71, 10, 68],
      [248, 204, 245],
    ],
    'label-orchid-v1-02': [
      [94, 13, 90],
      [244, 177, 240],
    ],
    'label-orchid-v1-03': [
      [115, 16, 110],
      [240, 150, 235],
    ],
    'label-orchid-v1-04': [
      [136, 19, 130],
      [236, 123, 230],
    ],
    'label-orchid-v1-05': [
      [158, 23, 150],
      [232, 91, 224],
    ],
    'label-orchid-v1-06': [
      [179, 26, 170],
      [226, 54, 217],
    ],
    'label-orchid-v1-07': [
      [200, 29, 190],
      [211, 30, 201],
    ],
    'label-orchid-v1-08': [
      [222, 32, 211],
      [190, 27, 181],
    ],
    'label-orchid-v1-09': [
      [229, 74, 221],
      [168, 24, 160],
    ],
    'label-orchid-v1-10': [
      [234, 108, 227],
      [146, 21, 139],
    ],
    'label-orchid-v1-11': [
      [238, 136, 233],
      [126, 18, 121],
    ],
    'label-orchid-v1-12': [
      [241, 160, 237],
      [108, 15, 103],
    ],
    'label-orchid-v1-13': [
      [244, 181, 241],
      [93, 13, 88],
    ],
    'label-orchid-v1-14': [
      [246, 194, 244],
      [81, 12, 77],
    ],
    'label-orchid-v1-15': [
      [248, 203, 245],
      [73, 10, 70],
    ],
    'label-orchid-v1-16': [
      [249, 213, 247],
      [63, 9, 60],
    ],
    'label-orchid-v1-17': [
      [250, 222, 249],
      [55, 8, 53],
    ],
    'label-orchid-v1-18': [
      [252, 231, 250],
      [45, 6, 43],
    ],
    'label-orchid-v1-19': [
      [253, 240, 252],
      [32, 5, 30],
    ],
    'label-orchid-v1-20': [
      [254, 246, 253],
      [24, 3, 23],
    ],
    'label-orchid-v1': [
      [227, 59, 218],
      [227, 59, 218],
    ],
    'label-violet-v1-01': [
      [46, 5, 118],
      [227, 211, 253],
    ],
    'label-violet-v1-02': [
      [60, 7, 153],
      [212, 188, 252],
    ],
    'label-violet-v1-03': [
      [73, 8, 186],
      [198, 166, 251],
    ],
    'label-violet-v1-04': [
      [87, 9, 219],
      [184, 146, 250],
    ],
    'label-violet-v1-05': [
      [103, 20, 245],
      [170, 125, 249],
    ],
    'label-violet-v1-06': [
      [123, 51, 246],
      [157, 103, 248],
    ],
    'label-violet-v1-07': [
      [137, 73, 247],
      [144, 84, 248],
    ],
    'label-violet-v1-08': [
      [150, 94, 248],
      [130, 63, 247],
    ],
    'label-violet-v1-09': [
      [164, 114, 249],
      [113, 37, 246],
    ],
    'label-violet-v1-10': [
      [177, 136, 250],
      [93, 10, 235],
    ],
    'label-violet-v1-11': [
      [190, 156, 251],
      [80, 9, 204],
    ],
    'label-violet-v1-12': [
      [203, 175, 252],
      [69, 8, 175],
    ],
    'label-violet-v1-13': [
      [214, 191, 252],
      [59, 6, 150],
    ],
    'label-violet-v1-14': [
      [221, 202, 253],
      [52, 6, 133],
    ],
    'label-violet-v1-15': [
      [225, 209, 253],
      [47, 5, 119],
    ],
    'label-violet-v1-16': [
      [231, 218, 253],
      [42, 5, 105],
    ],
    'label-violet-v1-17': [
      [236, 226, 254],
      [36, 4, 92],
    ],
    'label-violet-v1-18': [
      [241, 233, 254],
      [29, 3, 75],
    ],
    'label-violet-v1-19': [
      [246, 241, 254],
      [23, 3, 58],
    ],
    'label-violet-v1-20': [
      [250, 248, 255],
      [16, 2, 41],
    ],
    'label-violet-v1': [
      [120, 47, 246],
      [120, 47, 246],
    ],
    'label-blue-v1-01': [
      [4, 24, 118],
      [209, 216, 253],
    ],
    'label-blue-v1-02': [
      [6, 31, 155],
      [185, 197, 252],
    ],
    'label-blue-v1-03': [
      [7, 39, 189],
      [162, 178, 252],
    ],
    'label-blue-v1-04': [
      [8, 45, 224],
      [140, 159, 251],
    ],
    'label-blue-v1-05': [
      [21, 59, 246],
      [119, 141, 250],
    ],
    'label-blue-v1-06': [
      [47, 81, 247],
      [97, 124, 249],
    ],
    'label-blue-v1-07': [
      [67, 99, 248],
      [78, 107, 248],
    ],
    'label-blue-v1-08': [
      [88, 115, 249],
      [58, 90, 248],
    ],
    'label-blue-v1-09': [
      [108, 133, 250],
      [34, 71, 247],
    ],
    'label-blue-v1-10': [
      [130, 151, 250],
      [9, 49, 240],
    ],
    'label-blue-v1-11': [
      [150, 168, 251],
      [8, 42, 209],
    ],
    'label-blue-v1-12': [
      [171, 185, 252],
      [7, 36, 178],
    ],
    'label-blue-v1-13': [
      [188, 199, 253],
      [6, 31, 151],
    ],
    'label-blue-v1-14': [
      [198, 208, 253],
      [5, 28, 135],
    ],
    'label-blue-v1-15': [
      [207, 215, 253],
      [4, 24, 120],
    ],
    'label-blue-v1-16': [
      [217, 223, 254],
      [4, 22, 106],
    ],
    'label-blue-v1-17': [
      [225, 230, 254],
      [3, 18, 91],
    ],
    'label-blue-v1-18': [
      [232, 236, 254],
      [3, 15, 74],
    ],
    'label-blue-v1-19': [
      [240, 242, 254],
      [2, 11, 54],
    ],
    'label-blue-v1-20': [
      [247, 249, 255],
      [1, 6, 31],
    ],
    'label-blue-v1': [
      [14, 54, 246],
      [14, 54, 246],
    ],
    'label-sky-v1-01': [
      [2, 40, 70],
      [184, 223, 253],
    ],
    'label-sky-v1-02': [
      [3, 54, 92],
      [146, 206, 252],
    ],
    'label-sky-v1-03': [
      [3, 66, 115],
      [107, 189, 251],
    ],
    'label-sky-v1-04': [
      [4, 78, 136],
      [69, 171, 250],
    ],
    'label-sky-v1-05': [
      [4, 91, 158],
      [29, 153, 249],
    ],
    'label-sky-v1-06': [
      [5, 104, 180],
      [7, 136, 236],
    ],
    'label-sky-v1-07': [
      [6, 117, 201],
      [6, 123, 213],
    ],
    'label-sky-v1-08': [
      [6, 129, 224],
      [5, 110, 191],
    ],
    'label-sky-v1-09': [
      [7, 144, 248],
      [5, 97, 168],
    ],
    'label-sky-v1-10': [
      [50, 163, 249],
      [4, 85, 146],
    ],
    'label-sky-v1-11': [
      [89, 180, 250],
      [4, 73, 126],
    ],
    'label-sky-v1-12': [
      [122, 195, 251],
      [3, 62, 107],
    ],
    'label-sky-v1-13': [
      [151, 208, 252],
      [3, 53, 91],
    ],
    'label-sky-v1-14': [
      [169, 216, 253],
      [2, 46, 79],
    ],
    'label-sky-v1-15': [
      [182, 222, 253],
      [2, 41, 71],
    ],
    'label-sky-v1-16': [
      [195, 228, 253],
      [2, 36, 62],
    ],
    'label-sky-v1-17': [
      [209, 234, 254],
      [2, 31, 54],
    ],
    'label-sky-v1-18': [
      [222, 240, 254],
      [1, 25, 43],
    ],
    'label-sky-v1-19': [
      [235, 246, 254],
      [1, 17, 30],
    ],
    'label-sky-v1-20': [
      [242, 249, 255],
      [0, 10, 17],
    ],
    'label-sky-v1': [
      [77, 175, 250],
      [77, 175, 250],
    ],
    'label-aqua-v1-01': [
      [2, 44, 39],
      [9, 244, 216],
    ],
    'label-aqua-v1-02': [
      [2, 59, 53],
      [8, 223, 198],
    ],
    'label-aqua-v1-03': [
      [3, 73, 65],
      [7, 204, 180],
    ],
    'label-aqua-v1-04': [
      [3, 86, 77],
      [7, 185, 164],
    ],
    'label-aqua-v1-05': [
      [4, 101, 89],
      [6, 167, 148],
    ],
    'label-aqua-v1-06': [
      [4, 115, 102],
      [5, 150, 133],
    ],
    'label-aqua-v1-07': [
      [5, 128, 114],
      [5, 136, 120],
    ],
    'label-aqua-v1-08': [
      [5, 143, 127],
      [4, 122, 108],
    ],
    'label-aqua-v1-09': [
      [6, 159, 141],
      [4, 107, 95],
    ],
    'label-aqua-v1-10': [
      [6, 177, 157],
      [3, 93, 83],
    ],
    'label-aqua-v1-11': [
      [7, 194, 172],
      [3, 80, 71],
    ],
    'label-aqua-v1-12': [
      [8, 211, 187],
      [2, 68, 61],
    ],
    'label-aqua-v1-13': [
      [8, 226, 200],
      [2, 58, 51],
    ],
    'label-aqua-v1-14': [
      [8, 236, 209],
      [2, 51, 45],
    ],
    'label-aqua-v1-15': [
      [9, 244, 216],
      [2, 46, 40],
    ],
    'label-aqua-v1-16': [
      [68, 248, 227],
      [1, 39, 35],
    ],
    'label-aqua-v1-17': [
      [125, 250, 235],
      [1, 33, 29],
    ],
    'label-aqua-v1-18': [
      [169, 252, 242],
      [1, 28, 24],
    ],
    'label-aqua-v1-19': [
      [205, 253, 247],
      [1, 20, 17],
    ],
    'label-aqua-v1-20': [
      [226, 254, 251],
      [0, 13, 12],
    ],
    'label-aqua-v1': [
      [116, 250, 234],
      [116, 250, 234],
    ],
    'label-green-v1-01': [
      [7, 45, 2],
      [95, 248, 73],
    ],
    'label-green-v1-02': [
      [10, 61, 2],
      [36, 230, 9],
    ],
    'label-green-v1-03': [
      [12, 75, 3],
      [33, 210, 8],
    ],
    'label-green-v1-04': [
      [14, 89, 4],
      [30, 191, 7],
    ],
    'label-green-v1-05': [
      [16, 103, 4],
      [27, 172, 7],
    ],
    'label-green-v1-06': [
      [19, 118, 5],
      [24, 155, 6],
    ],
    'label-green-v1-07': [
      [21, 132, 5],
      [22, 140, 6],
    ],
    'label-green-v1-08': [
      [23, 148, 6],
      [20, 125, 5],
    ],
    'label-green-v1-09': [
      [26, 164, 6],
      [17, 111, 4],
    ],
    'label-green-v1-10': [
      [29, 182, 7],
      [15, 96, 4],
    ],
    'label-green-v1-11': [
      [31, 200, 8],
      [13, 83, 3],
    ],
    'label-green-v1-12': [
      [34, 217, 8],
      [11, 70, 3],
    ],
    'label-green-v1-13': [
      [37, 233, 9],
      [9, 60, 2],
    ],
    'label-green-v1-14': [
      [38, 243, 10],
      [8, 53, 2],
    ],
    'label-green-v1-15': [
      [85, 247, 62],
      [7, 47, 2],
    ],
    'label-green-v1-16': [
      [132, 250, 115],
      [6, 41, 2],
    ],
    'label-green-v1-17': [
      [163, 251, 151],
      [5, 34, 1],
    ],
    'label-green-v1-18': [
      [192, 252, 184],
      [5, 29, 1],
    ],
    'label-green-v1-19': [
      [221, 253, 216],
      [3, 19, 1],
    ],
    'label-green-v1-20': [
      [232, 254, 229],
      [2, 13, 1],
    ],
    'label-green-v1': [
      [120, 249, 102],
      [120, 249, 102],
    ],
    'label-lime-v1-01': [
      [32, 42, 1],
      [178, 237, 5],
    ],
    'label-lime-v1-02': [
      [42, 57, 1],
      [162, 217, 5],
    ],
    'label-lime-v1-03': [
      [53, 70, 2],
      [148, 197, 5],
    ],
    'label-lime-v1-04': [
      [62, 83, 2],
      [134, 180, 4],
    ],
    'label-lime-v1-05': [
      [73, 97, 2],
      [122, 162, 4],
    ],
    'label-lime-v1-06': [
      [83, 111, 3],
      [109, 146, 3],
    ],
    'label-lime-v1-07': [
      [93, 124, 3],
      [98, 131, 3],
    ],
    'label-lime-v1-08': [
      [104, 138, 3],
      [88, 118, 3],
    ],
    'label-lime-v1-09': [
      [115, 154, 4],
      [78, 104, 2],
    ],
    'label-lime-v1-10': [
      [128, 171, 4],
      [67, 90, 2],
    ],
    'label-lime-v1-11': [
      [141, 188, 4],
      [58, 77, 2],
    ],
    'label-lime-v1-12': [
      [153, 204, 5],
      [49, 66, 2],
    ],
    'label-lime-v1-13': [
      [164, 219, 5],
      [42, 56, 1],
    ],
    'label-lime-v1-14': [
      [171, 228, 5],
      [37, 49, 1],
    ],
    'label-lime-v1-15': [
      [177, 236, 5],
      [32, 43, 1],
    ],
    'label-lime-v1-16': [
      [183, 244, 6],
      [29, 38, 1],
    ],
    'label-lime-v1-17': [
      [193, 250, 29],
      [24, 32, 1],
    ],
    'label-lime-v1-18': [
      [214, 252, 104],
      [19, 26, 1],
    ],
    'label-lime-v1-19': [
      [231, 253, 167],
      [13, 17, 0],
    ],
    'label-lime-v1-20': [
      [241, 254, 205],
      [8, 11, 0],
    ],
    'label-lime-v1': [
      [207, 251, 80],
      [207, 251, 80],
    ],
    'label-yellow-v1-01': [
      [45, 38, 2],
      [247, 217, 34],
    ],
    'label-yellow-v1-02': [
      [60, 52, 2],
      [230, 198, 8],
    ],
    'label-yellow-v1-03': [
      [75, 65, 3],
      [209, 180, 7],
    ],
    'label-yellow-v1-04': [
      [88, 76, 3],
      [190, 164, 6],
    ],
    'label-yellow-v1-05': [
      [102, 89, 3],
      [172, 149, 6],
    ],
    'label-yellow-v1-06': [
      [117, 101, 4],
      [154, 133, 5],
    ],
    'label-yellow-v1-07': [
      [131, 114, 4],
      [139, 120, 5],
    ],
    'label-yellow-v1-08': [
      [146, 126, 5],
      [124, 108, 4],
    ],
    'label-yellow-v1-09': [
      [163, 141, 6],
      [110, 95, 4],
    ],
    'label-yellow-v1-10': [
      [181, 157, 6],
      [95, 82, 3],
    ],
    'label-yellow-v1-11': [
      [199, 172, 7],
      [82, 71, 3],
    ],
    'label-yellow-v1-12': [
      [216, 187, 7],
      [69, 60, 2],
    ],
    'label-yellow-v1-13': [
      [231, 200, 8],
      [59, 51, 2],
    ],
    'label-yellow-v1-14': [
      [242, 209, 8],
      [52, 45, 2],
    ],
    'label-yellow-v1-15': [
      [247, 216, 27],
      [46, 40, 2],
    ],
    'label-yellow-v1-16': [
      [249, 224, 73],
      [40, 35, 1],
    ],
    'label-yellow-v1-17': [
      [250, 232, 120],
      [33, 29, 1],
    ],
    'label-yellow-v1-18': [
      [252, 239, 159],
      [27, 24, 1],
    ],
    'label-yellow-v1-19': [
      [253, 245, 197],
      [20, 17, 1],
    ],
    'label-yellow-v1-20': [
      [254, 250, 226],
      [12, 10, 0],
    ],
    'label-yellow-v1': [
      [249, 225, 78],
      [249, 225, 78],
    ],
    'label-orange-v1-01': [
      [69, 25, 5],
      [251, 209, 190],
    ],
    'label-orange-v1-02': [
      [92, 34, 6],
      [248, 185, 155],
    ],
    'label-orange-v1-03': [
      [113, 42, 8],
      [246, 161, 121],
    ],
    'label-orange-v1-04': [
      [133, 49, 9],
      [243, 136, 85],
    ],
    'label-orange-v1-05': [
      [155, 57, 11],
      [241, 110, 48],
    ],
    'label-orange-v1-06': [
      [177, 66, 12],
      [231, 86, 16],
    ],
    'label-orange-v1-07': [
      [198, 73, 14],
      [209, 78, 14],
    ],
    'label-orange-v1-08': [
      [220, 81, 15],
      [187, 69, 13],
    ],
    'label-orange-v1-09': [
      [239, 96, 27],
      [166, 61, 11],
    ],
    'label-orange-v1-10': [
      [242, 124, 67],
      [144, 53, 10],
    ],
    'label-orange-v1-11': [
      [245, 148, 101],
      [124, 46, 8],
    ],
    'label-orange-v1-12': [
      [247, 170, 133],
      [106, 39, 7],
    ],
    'label-orange-v1-13': [
      [248, 188, 159],
      [90, 33, 6],
    ],
    'label-orange-v1-14': [
      [250, 200, 176],
      [79, 29, 5],
    ],
    'label-orange-v1-15': [
      [250, 208, 187],
      [71, 26, 5],
    ],
    'label-orange-v1-16': [
      [251, 216, 200],
      [62, 23, 4],
    ],
    'label-orange-v1-17': [
      [252, 225, 212],
      [52, 19, 4],
    ],
    'label-orange-v1-18': [
      [253, 233, 223],
      [42, 16, 3],
    ],
    'label-orange-v1-19': [
      [254, 240, 234],
      [31, 11, 2],
    ],
    'label-orange-v1-20': [
      [254, 248, 244],
      [15, 6, 1],
    ],
    'label-orange-v1': [
      [241, 112, 50],
      [241, 112, 50],
    ],
    'brand-eolo-v1-01': [
      [26, 38, 61],
      [209, 218, 235],
    ],
    'brand-eolo-v1-02': [
      [35, 52, 82],
      [186, 200, 226],
    ],
    'brand-eolo-v1-03': [
      [43, 64, 102],
      [163, 182, 216],
    ],
    'brand-eolo-v1-04': [
      [51, 76, 121],
      [142, 166, 207],
    ],
    'brand-eolo-v1-05': [
      [59, 89, 141],
      [122, 150, 199],
    ],
    'brand-eolo-v1-06': [
      [68, 101, 160],
      [102, 134, 191],
    ],
    'brand-eolo-v1-07': [
      [76, 114, 180],
      [85, 121, 183],
    ],
    'brand-eolo-v1-08': [
      [93, 128, 187],
      [72, 108, 170],
    ],
    'brand-eolo-v1-09': [
      [112, 142, 195],
      [64, 95, 151],
    ],
    'brand-eolo-v1-10': [
      [133, 158, 203],
      [55, 82, 130],
    ],
    'brand-eolo-v1-11': [
      [152, 174, 212],
      [47, 71, 112],
    ],
    'brand-eolo-v1-12': [
      [172, 189, 220],
      [40, 60, 94],
    ],
    'brand-eolo-v1-13': [
      [188, 202, 227],
      [34, 51, 81],
    ],
    'brand-eolo-v1-14': [
      [198, 210, 231],
      [30, 45, 71],
    ],
    'brand-eolo-v1-15': [
      [207, 217, 235],
      [27, 40, 63],
    ],
    'brand-eolo-v1-16': [
      [216, 224, 238],
      [23, 35, 55],
    ],
    'brand-eolo-v1-17': [
      [224, 231, 242],
      [19, 29, 46],
    ],
    'brand-eolo-v1-18': [
      [233, 238, 246],
      [16, 23, 37],
    ],
    'brand-eolo-v1-19': [
      [240, 243, 249],
      [11, 16, 26],
    ],
    'brand-eolo-v1-20': [
      [246, 248, 251],
      [6, 9, 15],
    ],
    'brand-eolo-v1': [
      [89, 124, 185],
      [89, 124, 185],
    ],
    'brand-mindy-01': [
      [9, 29, 34],
      [228, 233, 235],
    ],
    'brand-mindy-02': [
      [4, 71, 86],
      [114, 193, 212],
    ],
    'brand-mindy-03': [
      [3, 84, 103],
      [31, 178, 213],
    ],
    'brand-mindy-04': [
      [3, 100, 123],
      [18, 158, 191],
    ],
    'brand-mindy-05': [
      [5, 119, 146],
      [9, 137, 166],
    ],
    'brand-mindy-06': [
      [16, 154, 187],
      [3, 104, 127],
    ],
    'brand-mindy-07': [
      [147, 200, 212],
      [5, 63, 76],
    ],
    'brand-mindy-08': [
      [203, 219, 223],
      [7, 44, 52],
    ],
    'brand-mindy-09': [
      [228, 233, 234],
      [8, 31, 36],
    ],
    'brand-mindy-10': [
      [244, 245, 245],
      [8, 16, 17],
    ],
    'brand-mindy': [
      [3, 98, 120],
      [3, 98, 120],
    ],
    'brand-synbee-eolo-01': [
      [18, 27, 43],
      [227, 233, 243],
    ],
    'brand-synbee-eolo-02': [
      [43, 64, 102],
      [163, 182, 216],
    ],
    'brand-synbee-eolo-03': [
      [51, 77, 122],
      [142, 166, 207],
    ],
    'brand-synbee-eolo-04': [
      [61, 91, 145],
      [118, 146, 197],
    ],
    'brand-synbee-eolo-05': [
      [73, 109, 173],
      [91, 126, 186],
    ],
    'brand-synbee-eolo-06': [
      [112, 142, 195],
      [63, 95, 150],
    ],
    'brand-synbee-eolo-07': [
      [176, 193, 222],
      [38, 57, 91],
    ],
    'brand-synbee-eolo-08': [
      [207, 217, 235],
      [27, 40, 63],
    ],
    'brand-synbee-eolo-09': [
      [227, 233, 243],
      [19, 28, 44],
    ],
    'brand-synbee-eolo-10': [
      [242, 245, 249],
      [9, 14, 22],
    ],
    'brand-synbee-eolo': [
      [89, 124, 185],
      [89, 124, 185],
    ],
    'brand-synbee-01': [
      [35, 26, 0],
      [255, 231, 155],
    ],
    'brand-synbee-02': [
      [81, 62, 0],
      [227, 173, 0],
    ],
    'brand-synbee-03': [
      [96, 74, 0],
      [206, 157, 0],
    ],
    'brand-synbee-04': [
      [115, 88, 0],
      [182, 139, 0],
    ],
    'brand-synbee-05': [
      [137, 105, 0],
      [158, 120, 0],
    ],
    'brand-synbee-06': [
      [177, 136, 0],
      [120, 91, 0],
    ],
    'brand-synbee-07': [
      [240, 184, 0],
      [72, 55, 0],
    ],
    'brand-synbee-08': [
      [255, 212, 72],
      [50, 39, 0],
    ],
    'brand-synbee-09': [
      [255, 230, 150],
      [34, 26, 0],
    ],
    'brand-synbee-10': [
      [255, 245, 211],
      [18, 14, 0],
    ],
    'brand-synbee': [
      [255, 195, 0],
      [255, 195, 0],
    ],
    'brand-apksic-01': [
      [9, 28, 47],
      [221, 235, 248],
    ],
    'brand-apksic-02': [
      [22, 66, 111],
      [140, 186, 232],
    ],
    'brand-apksic-03': [
      [26, 78, 133],
      [112, 168, 227],
    ],
    'brand-apksic-04': [
      [31, 93, 158],
      [80, 149, 221],
    ],
    'brand-apksic-05': [
      [37, 112, 188],
      [44, 127, 214],
    ],
    'brand-apksic-06': [
      [73, 145, 219],
      [32, 97, 163],
    ],
    'brand-apksic-07': [
      [157, 196, 236],
      [19, 59, 99],
    ],
    'brand-apksic-08': [
      [195, 219, 243],
      [13, 41, 68],
    ],
    'brand-apksic-09': [
      [221, 234, 248],
      [9, 28, 47],
    ],
    'brand-apksic-10': [
      [238, 245, 252],
      [5, 15, 26],
    ],
    'brand-apksic': [
      [35, 106, 179],
      [35, 106, 179],
    ],
    'adjust-tone-v1-01': [
      [38, 38, 38],
      [217, 217, 217],
    ],
    'adjust-tone-v1-02': [
      [52, 52, 52],
      [199, 199, 199],
    ],
    'adjust-tone-v1-03': [
      [64, 64, 64],
      [181, 181, 181],
    ],
    'adjust-tone-v1-04': [
      [76, 76, 76],
      [164, 164, 164],
    ],
    'adjust-tone-v1-05': [
      [89, 89, 89],
      [149, 149, 149],
    ],
    'adjust-tone-v1-06': [
      [101, 101, 101],
      [133, 133, 133],
    ],
    'adjust-tone-v1-07': [
      [114, 114, 114],
      [120, 120, 120],
    ],
    'adjust-tone-v1-08': [
      [127, 127, 127],
      [108, 108, 108],
    ],
    'adjust-tone-v1-09': [
      [141, 141, 141],
      [96, 96, 96],
    ],
    'adjust-tone-v1-10': [
      [157, 157, 157],
      [82, 82, 82],
    ],
    'adjust-tone-v1-11': [
      [172, 172, 172],
      [71, 71, 71],
    ],
    'adjust-tone-v1-12': [
      [188, 188, 188],
      [60, 60, 60],
    ],
    'adjust-tone-v1-13': [
      [201, 201, 201],
      [51, 51, 51],
    ],
    'adjust-tone-v1-14': [
      [210, 210, 210],
      [45, 45, 45],
    ],
    'adjust-tone-v1-15': [
      [217, 217, 217],
      [40, 40, 40],
    ],
    'adjust-tone-v1-16': [
      [223, 223, 223],
      [34, 34, 34],
    ],
    'adjust-tone-v1-17': [
      [231, 231, 231],
      [29, 29, 29],
    ],
    'adjust-tone-v1-18': [
      [237, 237, 237],
      [24, 24, 24],
    ],
    'adjust-tone-v1-19': [
      [243, 243, 243],
      [16, 16, 16],
    ],
    'adjust-tone-v1-20': [
      [249, 249, 249],
      [8, 8, 8],
    ],
    'adjust-tone-v1': [
      [255, 255, 255],
      [0, 0, 0],
    ],
    'area-demographic-01': [
      [21, 29, 6],
      [220, 240, 185],
    ],
    'area-demographic-02': [
      [50, 70, 15],
      [141, 199, 41],
    ],
    'area-demographic-03': [
      [60, 85, 17],
      [127, 180, 37],
    ],
    'area-demographic-04': [
      [71, 100, 21],
      [113, 159, 33],
    ],
    'area-demographic-05': [
      [85, 120, 25],
      [97, 137, 28],
    ],
    'area-demographic-06': [
      [109, 155, 32],
      [74, 104, 21],
    ],
    'area-demographic-07': [
      [149, 210, 43],
      [45, 63, 13],
    ],
    'area-demographic-08': [
      [191, 229, 127],
      [31, 44, 9],
    ],
    'area-demographic-09': [
      [218, 240, 180],
      [22, 31, 6],
    ],
    'area-demographic-10': [
      [239, 248, 223],
      [12, 17, 3],
    ],
    'area-demographic': [
      [148, 209, 43],
      [148, 209, 43],
    ],
    'area-accounting-01': [
      [61, 3, 11],
      [253, 226, 230],
    ],
    'area-accounting-02': [
      [132, 8, 23],
      [249, 155, 167],
    ],
    'area-accounting-03': [
      [156, 9, 28],
      [248, 127, 143],
    ],
    'area-accounting-04': [
      [184, 11, 32],
      [246, 93, 112],
    ],
    'area-accounting-05': [
      [219, 12, 39],
      [243, 36, 62],
    ],
    'area-accounting-06': [
      [245, 85, 105],
      [191, 11, 34],
    ],
    'area-accounting-07': [
      [250, 171, 181],
      [119, 7, 21],
    ],
    'area-accounting-08': [
      [252, 205, 211],
      [87, 5, 15],
    ],
    'area-accounting-09': [
      [253, 225, 229],
      [62, 4, 11],
    ],
    'area-accounting-10': [
      [254, 243, 245],
      [37, 2, 7],
    ],
    'area-accounting': [
      [244, 62, 85],
      [244, 62, 85],
    ],
    'area-general-affairs-01': [
      [41, 23, 1],
      [254, 229, 198],
    ],
    'area-general-affairs-02': [
      [96, 55, 3],
      [250, 162, 54],
    ],
    'area-general-affairs-03': [
      [115, 65, 3],
      [243, 138, 6],
    ],
    'area-general-affairs-04': [
      [137, 77, 4],
      [216, 122, 6],
    ],
    'area-general-affairs-05': [
      [163, 92, 4],
      [187, 105, 5],
    ],
    'area-general-affairs-06': [
      [210, 119, 5],
      [142, 80, 4],
    ],
    'area-general-affairs-07': [
      [251, 177, 86],
      [86, 48, 2],
    ],
    'area-general-affairs-08': [
      [252, 209, 154],
      [60, 34, 2],
    ],
    'area-general-affairs-09': [
      [254, 229, 200],
      [42, 24, 1],
    ],
    'area-general-affairs-10': [
      [254, 243, 230],
      [23, 13, 1],
    ],
    'area-general-affairs': [
      [249, 149, 25],
      [249, 149, 25],
    ],
    'area-tributes-01': [
      [4, 30, 31],
      [185, 243, 245],
    ],
    'area-tributes-02': [
      [11, 72, 74],
      [30, 201, 205],
    ],
    'area-tributes-03': [
      [13, 86, 87],
      [27, 182, 186],
    ],
    'area-tributes-04': [
      [15, 102, 104],
      [24, 161, 165],
    ],
    'area-tributes-05': [
      [18, 121, 124],
      [21, 139, 142],
    ],
    'area-tributes-06': [
      [23, 157, 160],
      [16, 106, 108],
    ],
    'area-tributes-07': [
      [31, 212, 216],
      [9, 64, 65],
    ],
    'area-tributes-08': [
      [122, 233, 236],
      [7, 45, 46],
    ],
    'area-tributes-09': [
      [180, 243, 244],
      [5, 31, 32],
    ],
    'area-tributes-10': [
      [226, 250, 251],
      [3, 17, 18],
    ],
    'area-tributes': [
      [41, 220, 224],
      [41, 220, 224],
    ],
    'area-personnel-01': [
      [37, 0, 88],
      [239, 228, 255],
    ],
    'area-personnel-02': [
      [78, 0, 187],
      [202, 164, 255],
    ],
    'area-personnel-03': [
      [91, 0, 220],
      [189, 141, 255],
    ],
    'area-personnel-04': [
      [109, 5, 255],
      [174, 115, 255],
    ],
    'area-personnel-05': [
      [139, 55, 255],
      [156, 84, 255],
    ],
    'area-personnel-06': [
      [170, 110, 255],
      [117, 18, 255],
    ],
    'area-personnel-07': [
      [210, 178, 255],
      [70, 0, 168],
    ],
    'area-personnel-08': [
      [228, 208, 255],
      [51, 0, 123],
    ],
    'area-personnel-09': [
      [239, 228, 255],
      [37, 0, 89],
    ],
    'area-personnel-10': [
      [247, 242, 255],
      [24, 0, 57],
    ],
    'area-personnel': [
      [171, 111, 255],
      [171, 111, 255],
    ],
    'area-technical-01': [
      [30, 27, 0],
      [255, 236, 4],
    ],
    'area-technical-02': [
      [71, 65, 0],
      [199, 184, 0],
    ],
    'area-technical-03': [
      [85, 78, 0],
      [180, 166, 0],
    ],
    'area-technical-04': [
      [101, 93, 0],
      [160, 147, 0],
    ],
    'area-technical-05': [
      [121, 111, 0],
      [138, 127, 0],
    ],
    'area-technical-06': [
      [156, 143, 0],
      [105, 96, 0],
    ],
    'area-technical-07': [
      [210, 194, 0],
      [63, 58, 0],
    ],
    'area-technical-08': [
      [237, 219, 0],
      [44, 41, 0],
    ],
    'area-technical-09': [
      [255, 236, 4],
      [30, 28, 0],
    ],
    'area-technical-10': [
      [255, 248, 164],
      [16, 15, 0],
    ],
    'area-technical': [
      [255, 236, 10],
      [255, 236, 10],
    ],
    'area-personal-services-01': [
      [57, 0, 48],
      [255, 223, 250],
    ],
    'area-personal-services-02': [
      [123, 0, 103],
      [255, 141, 236],
    ],
    'area-personal-services-03': [
      [146, 0, 121],
      [255, 106, 230],
    ],
    'area-personal-services-04': [
      [171, 0, 143],
      [255, 48, 220],
    ],
    'area-personal-services-05': [
      [202, 0, 168],
      [230, 0, 192],
    ],
    'area-personal-services-06': [
      [255, 25, 216],
      [177, 0, 147],
    ],
    'area-personal-services-07': [
      [255, 160, 239],
      [111, 0, 92],
    ],
    'area-personal-services-08': [
      [255, 198, 245],
      [81, 0, 68],
    ],
    'area-personal-services-09': [
      [255, 222, 250],
      [59, 0, 49],
    ],
    'area-personal-services-10': [
      [255, 240, 253],
      [36, 0, 30],
    ],
    'area-personal-services': [
      [255, 77, 225],
      [255, 77, 225],
    ],
    'theme-default-01-primary-action': [
      [2, 66, 185],
      [137, 165, 218],
    ],
    'theme-default-01-primary-icon': [
      [2, 66, 185],
      [137, 165, 218],
    ],
    'theme-default-02-primary-text': [
      [33, 33, 33],
      [225, 225, 225],
    ],
    'theme-default-03-secondary-action': [
      [64, 64, 64],
      [181, 181, 181],
    ],
    'theme-default-03-secondary-icon': [
      [64, 64, 64],
      [181, 181, 181],
    ],
    'theme-default-03-secondary-text': [
      [64, 64, 64],
      [181, 181, 181],
    ],
    'theme-default-04-primary-decoration': [
      [162, 162, 162],
      [78, 78, 78],
    ],
    'theme-default-05-secondary-decoration': [
      [231, 231, 231],
      [29, 29, 29],
    ],
    'theme-default-06-secondary-background': [
      [248, 248, 248],
      [9, 9, 9],
    ],
    'theme-default-07-primary-background': [
      [255, 255, 255],
      [0, 0, 0],
    ],
  },
};
