# STYLES CACHE
.styles-cache:
  cache:
    key:
      files:
        - yarn.lock
      prefix: "${CI_PROJECT_NAME}-styles"
    policy: pull

# STYLES BUILD
styles-build:
  extends: [.base-build, .styles-cache]
  script:
    - nx run design-tokens:build
    - nx run styles:build
    - ls
    - ls ./projects/design-tokens
    - ls ./projects/styles
    - |
      if [[ ! -d ./projects/styles/dist/ ]]; then
        echo "STYLES DIST DOES NOT EXIST"
        exit 128
      fi
    - |
      if [[ ! -d ./projects/design-tokens/dist/ ]]; then
        echo "DESIGN-TOKENS DIST DOES NOT EXIST"
        exit 128
      fi
  artifacts:
    name: styles-build
    expire_in: 1 day
    paths:
      - projects/design-tokens/dist
      - projects/design-tokens/config
      - projects/design-tokens/properties
      - projects/styles/dist
  cache:
    policy: pull-push
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(dev|main|pipeline)$/
      changes:
        - projects/styles/**/*

# STYLES PUBLISH TEST
styles-publish-test:
  extends: [.base-publish-test, .styles-cache]
  dependencies: [styles-build]
  stage: test
  variables:
    BUILD_DIR: projects/styles
    COMPONENT: styles
    PACK_NAME: maggioli-design-system-styles-*.tgz
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH =~ /^(main|pipeline)$/
      changes:
        - projects/styles/package.json

# STYLES PUBLISH
styles-publish:
  extends: [.base-publish, .styles-cache]
  dependencies: [styles-build]
  needs: [styles-publish-test, styles-build]
  stage: publish
  variables:
    BUILD_DIR: projects/styles
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/styles/package.json

# STYLES INSTALL TEST
styles-install-test:
  extends: [.base-install-test, .styles-cache]
  needs: [styles-publish]
  variables:
    BUILD_DIR: projects/styles
    COMPONENT: styles
    PACK_NAME: maggioli-design-system-styles-*.tgz
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - projects/styles/package.json
