.base-avatar:
  variables:
    COMPONENT: mds-avatar

# TEST
avatar-publish-test:
  extends: [.base-stencil-publish-test, .base-avatar]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
avatar-publish:
  extends: [.base-stencil-publish, .base-avatar]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, avatar-publish-test]

# INSTALL TEST
avatar-install-test:
  extends: [.base-stencil-install-test, .base-avatar]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, avatar-publish]
