.base-avatar:
  variables:
    COMPONENT: mds-avatar

# ISOLATE
avatar-isolate:
  extends: [.base-isolate, .base-avatar]
  dependencies: [base-stencil-build]

# TEST
avatar-publish-test:
  extends: [.base-stencil-publish-test, .base-avatar]
  dependencies: [base-stencil-build, avatar-isolate]

# PUBLISH
avatar-publish:
  extends: [.base-stencil-publish, .base-avatar]
  dependencies: [base-stencil-build, avatar-isolate]
  needs: [base-stencil-build, avatar-isolate, avatar-publish-test]

# INSTALL TEST
avatar-install-test:
  extends: [.base-stencil-install-test, .base-avatar]
  needs: [avatar-publish]

