.base-avatar:
  variables:
    COMPONENT: mds-avatar

# BUILD
avatar-build:
  extends: [.base-build, .base-avatar]

# ISOLATE
avatar-isolate:
  extends: [.base-isolate, .base-avatar]
  dependencies: [avatar-build]

# TEST
avatar-stencil-test:
  extends: [.base-stencil-test, .base-avatar]
  dependencies: [avatar-build, avatar-isolate]

avatar-publish-test:
  extends: [.base-publish-test, .base-avatar]
  dependencies: [avatar-build, avatar-isolate]

# PUBLISH
avatar-publish:
  extends: [.base-publish, .base-avatar]
  dependencies: [avatar-build, avatar-isolate]
