.base-img:
  variables:
    COMPONENT: mds-img

# ISOLATE
img-isolate:
  extends: [.base-isolate, .base-img]
  dependencies: [base-stencil-build]

# TEST
img-publish-test:
  extends: [.base-stencil-publish-test, .base-img]
  dependencies: [base-stencil-build, img-isolate]

# PUBLISH
img-publish:
  extends: [.base-stencil-publish, .base-img]
  dependencies: [base-stencil-build, img-isolate]
  needs: [base-stencil-build, img-isolate, img-publish-test]

# INSTALL TEST
img-install-test:
  extends: [.base-stencil-install-test, .base-img]
  dependencies: [img-publish, img-isolate]
