.base-row:
  variables:
    COMPONENT: mds-row

# ISOLATE
row-isolate:
  extends: [.base-isolate, .base-row]
  dependencies: [base-stencil-build]

# TEST
row-publish-test:
  extends: [.base-stencil-publish-test, .base-row]
  dependencies: [base-stencil-build, row-isolate]

# PUBLISH
row-publish:
  extends: [.base-stencil-publish, .base-row]
  dependencies: [base-stencil-build, row-isolate]
  needs: [base-stencil-build, row-isolate, row-publish-test]
