name: design-tokens

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  design-tokens:
    uses: ./.github/workflows/_package-pipeline.yml
    with:
      path: projects/design-tokens/**
      nx-project: design-tokens
      artifact-paths: projects/design-tokens/dist
      artifact-download-path: projects/design-tokens/dist
      run-tests: true
      test-working-directory: projects/design-tokens
