name: icons

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  icons:
    uses: ./.github/workflows/_package-pipeline.yml
    with:
      path: projects/icons/**
      nx-project: icons
      # icons build also produces svg-icons dist (nx implicit dependency)
      artifact-paths: |
        projects/icons/dist
        projects/svg-icons/dist
      artifact-download-path: projects
