name: styles

on:
  push:
    branches: [dev, main]
    paths:
      - 'projects/styles/**'
  pull_request:
    paths:
      - 'projects/styles/**'

jobs:
  pipeline:
    uses: ./.github/workflows/_package-pipeline.yml
    with:
      nx-project: styles
      component: styles
      publish-working-directory: projects/styles
      # styles build also produces design-tokens dist (nx implicit dependency)
      artifact-paths: |
        projects/design-tokens/dist
        projects/styles/dist
      artifact-download-path: projects
      package-json-filter: projects/styles/package.json
      pack-name: maggioli-design-system-styles-*.tgz
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
