name: svg-icons

on:
  push:
    branches: [dev, main]
    paths:
      - 'projects/svg-icons/**'
  pull_request:
    paths:
      - 'projects/svg-icons/**'

jobs:
  pipeline:
    uses: ./.github/workflows/_package-pipeline.yml
    with:
      nx-project: svg-icons
      artifact-paths: projects/svg-icons/dist
      artifact-download-path: projects/svg-icons/dist
