.base-flex-table:
  variables:
    COMPONENT: mds-flex-table

# BUILD
flex-table-build:
  extends: [.base-build, .base-flex-table]

# ISOLATE
flex-table-isolate:
  extends: [.base-isolate, .base-flex-table]
  dependencies: [flex-table-build]

# TEST
flex-table-stencil-test:
  extends: [.base-stencil-test, .base-flex-table]
  dependencies: [flex-table-build, flex-table-isolate]

flex-table-publish-test:
  extends: [.base-publish-test, .base-flex-table]
  dependencies: [flex-table-build, flex-table-isolate]

# PUBLISH
flex-table-publish:
  extends: [.base-publish, .base-flex-table]
  dependencies: [flex-table-build, flex-table-isolate]
