.base-kpi:
  variables:
    COMPONENT: mds-kpi

# TEST
kpi-publish-test:
  extends: [.base-stencil-publish-test, .base-kpi]
  dependencies: [base-stencil-build, base-isolate]

# PUBLISH
kpi-publish:
  extends: [.base-stencil-publish, .base-kpi]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, kpi-publish-test]

# INSTALL TEST
kpi-install-test:
  extends: [.base-stencil-install-test, .base-kpi]
  dependencies: [base-stencil-build, base-isolate]
  needs: [base-stencil-build, base-isolate, kpi-publish]
