.base-kpi:
  variables:
    COMPONENT: mds-kpi

# BUILD
kpi-build:
  extends: [.base-build, .base-kpi]

# ISOLATE
kpi-isolate:
  extends: [.base-isolate, .base-kpi]
  dependencies: [kpi-build]

# TEST
kpi-stencil-test:
  extends: [.base-stencil-test, .base-kpi]
  dependencies: [kpi-build, kpi-isolate]

kpi-publish-test:
  extends: [.base-publish-test, .base-kpi]
  dependencies: [kpi-build, kpi-isolate]

# PUBLISH
kpi-publish:
  extends: [.base-publish, .base-kpi]
  dependencies: [kpi-build, kpi-isolate]
